package mnj.ont.model.lov.views;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Feb 13 23:36:34 BDT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AmendmentTypeVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public AmendmentTypeVOImpl() {
    }
}
