package mnj.ont.model.lov.views;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Feb 16 00:36:42 BDT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class NewInsuranceCompanyVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public NewInsuranceCompanyVOImpl() {
    }
}
