package mnj.ont.model.views;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Dec 06 12:58:00 BDT 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class BankHeadBranchesVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public BankHeadBranchesVOImpl() {
    }
}
