package mnj.ont.model.views;

import mnj.ont.model.entities.BBLCLinesEOImpl;

import oracle.jbo.RowIterator;
import oracle.jbo.RowSet;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Jan 18 20:14:27 BDT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class BBLCLinesVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        ImpBblcLineId {
            public Object get(BBLCLinesVORowImpl obj) {
                return obj.getImpBblcLineId();
            }

            public void put(BBLCLinesVORowImpl obj, Object value) {
                obj.setImpBblcLineId((Number)value);
            }
        }
        ,
        ImpBblcHeaderId {
            public Object get(BBLCLinesVORowImpl obj) {
                return obj.getImpBblcHeaderId();
            }

            public void put(BBLCLinesVORowImpl obj, Object value) {
                obj.setImpBblcHeaderId((Number)value);
            }
        }
        ,
        BblcType {
            public Object get(BBLCLinesVORowImpl obj) {
                return obj.getBblcType();
            }

            public void put(BBLCLinesVORowImpl obj, Object value) {
                obj.setBblcType((String)value);
            }
        }
        ,
        BblcNo {
            public Object get(BBLCLinesVORowImpl obj) {
                return obj.getBblcNo();
            }

            public void put(BBLCLinesVORowImpl obj, Object value) {
                obj.setBblcNo((String)value);
            }
        }
        ,
        LcIssueDate {
            public Object get(BBLCLinesVORowImpl obj) {
                return obj.getLcIssueDate();
            }

            public void put(BBLCLinesVORowImpl obj, Object value) {
                obj.setLcIssueDate((Date)value);
            }
        }
        ,
        LastShipmentDate {
            public Object get(BBLCLinesVORowImpl obj) {
                return obj.getLastShipmentDate();
            }

            public void put(BBLCLinesVORowImpl obj, Object value) {
                obj.setLastShipmentDate((Date)value);
            }
        }
        ,
        NegotiationDay {
            public Object get(BBLCLinesVORowImpl obj) {
                return obj.getNegotiationDay();
            }

            public void put(BBLCLinesVORowImpl obj, Object value) {
                obj.setNegotiationDay((String)value);
            }
        }
        ,
        ExpiryDate {
            public Object get(BBLCLinesVORowImpl obj) {
                return obj.getExpiryDate();
            }

            public void put(BBLCLinesVORowImpl obj, Object value) {
                obj.setExpiryDate((Date)value);
            }
        }
        ,
        IncoTerm {
            public Object get(BBLCLinesVORowImpl obj) {
                return obj.getIncoTerm();
            }

            public void put(BBLCLinesVORowImpl obj, Object value) {
                obj.setIncoTerm((String)value);
            }
        }
        ,
        UsancePeriod {
            public Object get(BBLCLinesVORowImpl obj) {
                return obj.getUsancePeriod();
            }

            public void put(BBLCLinesVORowImpl obj, Object value) {
                obj.setUsancePeriod((String)value);
            }
        }
        ,
        ShipmentMode {
            public Object get(BBLCLinesVORowImpl obj) {
                return obj.getShipmentMode();
            }

            public void put(BBLCLinesVORowImpl obj, Object value) {
                obj.setShipmentMode((String)value);
            }
        }
        ,
        BeneficiaryName {
            public Object get(BBLCLinesVORowImpl obj) {
                return obj.getBeneficiaryName();
            }

            public void put(BBLCLinesVORowImpl obj, Object value) {
                obj.setBeneficiaryName((String)value);
            }
        }
        ,
        PiNo {
            public Object get(BBLCLinesVORowImpl obj) {
                return obj.getPiNo();
            }

            public void put(BBLCLinesVORowImpl obj, Object value) {
                obj.setPiNo((String)value);
            }
        }
        ,
        TotalBblcValue {
            public Object get(BBLCLinesVORowImpl obj) {
                return obj.getTotalBblcValue();
            }

            public void put(BBLCLinesVORowImpl obj, Object value) {
                obj.setTotalBblcValue((Number)value);
            }
        }
        ,
        Item {
            public Object get(BBLCLinesVORowImpl obj) {
                return obj.getItem();
            }

            public void put(BBLCLinesVORowImpl obj, Object value) {
                obj.setItem((String)value);
            }
        }
        ,
        LcafNo {
            public Object get(BBLCLinesVORowImpl obj) {
                return obj.getLcafNo();
            }

            public void put(BBLCLinesVORowImpl obj, Object value) {
                obj.setLcafNo((String)value);
            }
        }
        ,
        CountryOfOrigion {
            public Object get(BBLCLinesVORowImpl obj) {
                return obj.getCountryOfOrigion();
            }

            public void put(BBLCLinesVORowImpl obj, Object value) {
                obj.setCountryOfOrigion((String)value);
            }
        }
        ,
        Confirmation {
            public Object get(BBLCLinesVORowImpl obj) {
                return obj.getConfirmation();
            }

            public void put(BBLCLinesVORowImpl obj, Object value) {
                obj.setConfirmation((String)value);
            }
        }
        ,
        ConfiramtionCharges {
            public Object get(BBLCLinesVORowImpl obj) {
                return obj.getConfiramtionCharges();
            }

            public void put(BBLCLinesVORowImpl obj, Object value) {
                obj.setConfiramtionCharges((Number)value);
            }
        }
        ,
        FreightCharge {
            public Object get(BBLCLinesVORowImpl obj) {
                return obj.getFreightCharge();
            }

            public void put(BBLCLinesVORowImpl obj, Object value) {
                obj.setFreightCharge((Number)value);
            }
        }
        ,
        OtherCharge {
            public Object get(BBLCLinesVORowImpl obj) {
                return obj.getOtherCharge();
            }

            public void put(BBLCLinesVORowImpl obj, Object value) {
                obj.setOtherCharge((Number)value);
            }
        }
        ,
        Commission {
            public Object get(BBLCLinesVORowImpl obj) {
                return obj.getCommission();
            }

            public void put(BBLCLinesVORowImpl obj, Object value) {
                obj.setCommission((String)value);
            }
        }
        ,
        InsuranceCompanyName {
            public Object get(BBLCLinesVORowImpl obj) {
                return obj.getInsuranceCompanyName();
            }

            public void put(BBLCLinesVORowImpl obj, Object value) {
                obj.setInsuranceCompanyName((String)value);
            }
        }
        ,
        InsurancePolicyNo {
            public Object get(BBLCLinesVORowImpl obj) {
                return obj.getInsurancePolicyNo();
            }

            public void put(BBLCLinesVORowImpl obj, Object value) {
                obj.setInsurancePolicyNo((String)value);
            }
        }
        ,
        UdAmendmentNo {
            public Object get(BBLCLinesVORowImpl obj) {
                return obj.getUdAmendmentNo();
            }

            public void put(BBLCLinesVORowImpl obj, Object value) {
                obj.setUdAmendmentNo((String)value);
            }
        }
        ,
        LcStatus {
            public Object get(BBLCLinesVORowImpl obj) {
                return obj.getLcStatus();
            }

            public void put(BBLCLinesVORowImpl obj, Object value) {
                obj.setLcStatus((String)value);
            }
        }
        ,
        LastUpdateLogin {
            public Object get(BBLCLinesVORowImpl obj) {
                return obj.getLastUpdateLogin();
            }

            public void put(BBLCLinesVORowImpl obj, Object value) {
                obj.setLastUpdateLogin((Number)value);
            }
        }
        ,
        LastUpdateDate {
            public Object get(BBLCLinesVORowImpl obj) {
                return obj.getLastUpdateDate();
            }

            public void put(BBLCLinesVORowImpl obj, Object value) {
                obj.setLastUpdateDate((Date)value);
            }
        }
        ,
        LastUpdatedBy {
            public Object get(BBLCLinesVORowImpl obj) {
                return obj.getLastUpdatedBy();
            }

            public void put(BBLCLinesVORowImpl obj, Object value) {
                obj.setLastUpdatedBy((Number)value);
            }
        }
        ,
        CreationDate {
            public Object get(BBLCLinesVORowImpl obj) {
                return obj.getCreationDate();
            }

            public void put(BBLCLinesVORowImpl obj, Object value) {
                obj.setCreationDate((Date)value);
            }
        }
        ,
        CreatedBy {
            public Object get(BBLCLinesVORowImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(BBLCLinesVORowImpl obj, Object value) {
                obj.setCreatedBy((Number)value);
            }
        }
        ,
        Attribute1 {
            public Object get(BBLCLinesVORowImpl obj) {
                return obj.getAttribute1();
            }

            public void put(BBLCLinesVORowImpl obj, Object value) {
                obj.setAttribute1((String)value);
            }
        }
        ,
        Attribute2 {
            public Object get(BBLCLinesVORowImpl obj) {
                return obj.getAttribute2();
            }

            public void put(BBLCLinesVORowImpl obj, Object value) {
                obj.setAttribute2((String)value);
            }
        }
        ,
        Attribute3 {
            public Object get(BBLCLinesVORowImpl obj) {
                return obj.getAttribute3();
            }

            public void put(BBLCLinesVORowImpl obj, Object value) {
                obj.setAttribute3((String)value);
            }
        }
        ,
        Attribute4 {
            public Object get(BBLCLinesVORowImpl obj) {
                return obj.getAttribute4();
            }

            public void put(BBLCLinesVORowImpl obj, Object value) {
                obj.setAttribute4((String)value);
            }
        }
        ,
        Attribute5 {
            public Object get(BBLCLinesVORowImpl obj) {
                return obj.getAttribute5();
            }

            public void put(BBLCLinesVORowImpl obj, Object value) {
                obj.setAttribute5((String)value);
            }
        }
        ,
        Attribute6 {
            public Object get(BBLCLinesVORowImpl obj) {
                return obj.getAttribute6();
            }

            public void put(BBLCLinesVORowImpl obj, Object value) {
                obj.setAttribute6((String)value);
            }
        }
        ,
        Attribute7 {
            public Object get(BBLCLinesVORowImpl obj) {
                return obj.getAttribute7();
            }

            public void put(BBLCLinesVORowImpl obj, Object value) {
                obj.setAttribute7((String)value);
            }
        }
        ,
        Attribute8 {
            public Object get(BBLCLinesVORowImpl obj) {
                return obj.getAttribute8();
            }

            public void put(BBLCLinesVORowImpl obj, Object value) {
                obj.setAttribute8((String)value);
            }
        }
        ,
        Attribute9 {
            public Object get(BBLCLinesVORowImpl obj) {
                return obj.getAttribute9();
            }

            public void put(BBLCLinesVORowImpl obj, Object value) {
                obj.setAttribute9((String)value);
            }
        }
        ,
        Attribute10 {
            public Object get(BBLCLinesVORowImpl obj) {
                return obj.getAttribute10();
            }

            public void put(BBLCLinesVORowImpl obj, Object value) {
                obj.setAttribute10((String)value);
            }
        }
        ,
        Attribute11 {
            public Object get(BBLCLinesVORowImpl obj) {
                return obj.getAttribute11();
            }

            public void put(BBLCLinesVORowImpl obj, Object value) {
                obj.setAttribute11((String)value);
            }
        }
        ,
        Attribute12 {
            public Object get(BBLCLinesVORowImpl obj) {
                return obj.getAttribute12();
            }

            public void put(BBLCLinesVORowImpl obj, Object value) {
                obj.setAttribute12((String)value);
            }
        }
        ,
        Attribute13 {
            public Object get(BBLCLinesVORowImpl obj) {
                return obj.getAttribute13();
            }

            public void put(BBLCLinesVORowImpl obj, Object value) {
                obj.setAttribute13((String)value);
            }
        }
        ,
        Attribute14 {
            public Object get(BBLCLinesVORowImpl obj) {
                return obj.getAttribute14();
            }

            public void put(BBLCLinesVORowImpl obj, Object value) {
                obj.setAttribute14((String)value);
            }
        }
        ,
        Attribute15 {
            public Object get(BBLCLinesVORowImpl obj) {
                return obj.getAttribute15();
            }

            public void put(BBLCLinesVORowImpl obj, Object value) {
                obj.setAttribute15((String)value);
            }
        }
        ,
        Attribute16 {
            public Object get(BBLCLinesVORowImpl obj) {
                return obj.getAttribute16();
            }

            public void put(BBLCLinesVORowImpl obj, Object value) {
                obj.setAttribute16((String)value);
            }
        }
        ,
        Attribute17 {
            public Object get(BBLCLinesVORowImpl obj) {
                return obj.getAttribute17();
            }

            public void put(BBLCLinesVORowImpl obj, Object value) {
                obj.setAttribute17((String)value);
            }
        }
        ,
        Attribute18 {
            public Object get(BBLCLinesVORowImpl obj) {
                return obj.getAttribute18();
            }

            public void put(BBLCLinesVORowImpl obj, Object value) {
                obj.setAttribute18((String)value);
            }
        }
        ,
        Attribute19 {
            public Object get(BBLCLinesVORowImpl obj) {
                return obj.getAttribute19();
            }

            public void put(BBLCLinesVORowImpl obj, Object value) {
                obj.setAttribute19((String)value);
            }
        }
        ,
        Attribute20 {
            public Object get(BBLCLinesVORowImpl obj) {
                return obj.getAttribute20();
            }

            public void put(BBLCLinesVORowImpl obj, Object value) {
                obj.setAttribute20((String)value);
            }
        }
        ,
        Attribute21 {
            public Object get(BBLCLinesVORowImpl obj) {
                return obj.getAttribute21();
            }

            public void put(BBLCLinesVORowImpl obj, Object value) {
                obj.setAttribute21((String)value);
            }
        }
        ,
        Attribute22 {
            public Object get(BBLCLinesVORowImpl obj) {
                return obj.getAttribute22();
            }

            public void put(BBLCLinesVORowImpl obj, Object value) {
                obj.setAttribute22((String)value);
            }
        }
        ,
        Attribute23 {
            public Object get(BBLCLinesVORowImpl obj) {
                return obj.getAttribute23();
            }

            public void put(BBLCLinesVORowImpl obj, Object value) {
                obj.setAttribute23((String)value);
            }
        }
        ,
        Attribute24 {
            public Object get(BBLCLinesVORowImpl obj) {
                return obj.getAttribute24();
            }

            public void put(BBLCLinesVORowImpl obj, Object value) {
                obj.setAttribute24((String)value);
            }
        }
        ,
        Attribute25 {
            public Object get(BBLCLinesVORowImpl obj) {
                return obj.getAttribute25();
            }

            public void put(BBLCLinesVORowImpl obj, Object value) {
                obj.setAttribute25((String)value);
            }
        }
        ,
        Attribute26 {
            public Object get(BBLCLinesVORowImpl obj) {
                return obj.getAttribute26();
            }

            public void put(BBLCLinesVORowImpl obj, Object value) {
                obj.setAttribute26((String)value);
            }
        }
        ,
        Attribute27 {
            public Object get(BBLCLinesVORowImpl obj) {
                return obj.getAttribute27();
            }

            public void put(BBLCLinesVORowImpl obj, Object value) {
                obj.setAttribute27((String)value);
            }
        }
        ,
        Attribute28 {
            public Object get(BBLCLinesVORowImpl obj) {
                return obj.getAttribute28();
            }

            public void put(BBLCLinesVORowImpl obj, Object value) {
                obj.setAttribute28((String)value);
            }
        }
        ,
        Attribute29 {
            public Object get(BBLCLinesVORowImpl obj) {
                return obj.getAttribute29();
            }

            public void put(BBLCLinesVORowImpl obj, Object value) {
                obj.setAttribute29((String)value);
            }
        }
        ,
        Attribute30 {
            public Object get(BBLCLinesVORowImpl obj) {
                return obj.getAttribute30();
            }

            public void put(BBLCLinesVORowImpl obj, Object value) {
                obj.setAttribute30((String)value);
            }
        }
        ,
        CommunicationType {
            public Object get(BBLCLinesVORowImpl obj) {
                return obj.getCommunicationType();
            }

            public void put(BBLCLinesVORowImpl obj, Object value) {
                obj.setCommunicationType((String)value);
            }
        }
        ,
        UpassDays {
            public Object get(BBLCLinesVORowImpl obj) {
                return obj.getUpassDays();
            }

            public void put(BBLCLinesVORowImpl obj, Object value) {
                obj.setUpassDays((Number)value);
            }
        }
        ,
        InsuranceCoverNoteDate {
            public Object get(BBLCLinesVORowImpl obj) {
                return obj.getInsuranceCoverNoteDate();
            }

            public void put(BBLCLinesVORowImpl obj, Object value) {
                obj.setInsuranceCoverNoteDate((Date)value);
            }
        }
        ,
        Currency {
            public Object get(BBLCLinesVORowImpl obj) {
                return obj.getCurrency();
            }

            public void put(BBLCLinesVORowImpl obj, Object value) {
                obj.setCurrency((String)value);
            }
        }
        ,
        ConversionRate {
            public Object get(BBLCLinesVORowImpl obj) {
                return obj.getConversionRate();
            }

            public void put(BBLCLinesVORowImpl obj, Object value) {
                obj.setConversionRate((Number)value);
            }
        }
        ,
        ConvertedAmount {
            public Object get(BBLCLinesVORowImpl obj) {
                return obj.getConvertedAmount();
            }

            public void put(BBLCLinesVORowImpl obj, Object value) {
                obj.setConvertedAmount((Number)value);
            }
        }
        ,
        UdAmendmentNumber {
            public Object get(BBLCLinesVORowImpl obj) {
                return obj.getUdAmendmentNumber();
            }

            public void put(BBLCLinesVORowImpl obj, Object value) {
                obj.setUdAmendmentNumber((String)value);
            }
        }
        ,
        AmendmentDate {
            public Object get(BBLCLinesVORowImpl obj) {
                return obj.getAmendmentDate();
            }

            public void put(BBLCLinesVORowImpl obj, Object value) {
                obj.setAmendmentDate((Date)value);
            }
        }
        ,
        Curr {
            public Object get(BBLCLinesVORowImpl obj) {
                return obj.getCurr();
            }

            public void put(BBLCLinesVORowImpl obj, Object value) {
                obj.setCurr((String)value);
            }
        }
        ,
        BeneficiaryId {
            public Object get(BBLCLinesVORowImpl obj) {
                return obj.getBeneficiaryId();
            }

            public void put(BBLCLinesVORowImpl obj, Object value) {
                obj.setBeneficiaryId((Number)value);
            }
        }
        ,
        AmendedValue {
            public Object get(BBLCLinesVORowImpl obj) {
                return obj.getAmendedValue();
            }

            public void put(BBLCLinesVORowImpl obj, Object value) {
                obj.setAmendedValue((Number)value);
            }
        }
        ,
        PaidAmountForBblc {
            public Object get(BBLCLinesVORowImpl obj) {
                return obj.getPaidAmountForBblc();
            }

            public void put(BBLCLinesVORowImpl obj, Object value) {
                obj.setPaidAmountForBblc((Number)value);
            }
        }
        ,
        BBLCDetails {
            public Object get(BBLCLinesVORowImpl obj) {
                return obj.getBBLCDetails();
            }

            public void put(BBLCLinesVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        BBLCPiDetails {
            public Object get(BBLCLinesVORowImpl obj) {
                return obj.getBBLCPiDetails();
            }

            public void put(BBLCLinesVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        BBLCAcceptance {
            public Object get(BBLCLinesVORowImpl obj) {
                return obj.getBBLCAcceptance();
            }

            public void put(BBLCLinesVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        BBLCTypeVO1 {
            public Object get(BBLCLinesVORowImpl obj) {
                return obj.getBBLCTypeVO1();
            }

            public void put(BBLCLinesVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        IncoTermsVO1 {
            public Object get(BBLCLinesVORowImpl obj) {
                return obj.getIncoTermsVO1();
            }

            public void put(BBLCLinesVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        UsanceVO1 {
            public Object get(BBLCLinesVORowImpl obj) {
                return obj.getUsanceVO1();
            }

            public void put(BBLCLinesVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        ShipModeVO1 {
            public Object get(BBLCLinesVORowImpl obj) {
                return obj.getShipModeVO1();
            }

            public void put(BBLCLinesVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        SupplierVO1 {
            public Object get(BBLCLinesVORowImpl obj) {
                return obj.getSupplierVO1();
            }

            public void put(BBLCLinesVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        ItemTypeVO1 {
            public Object get(BBLCLinesVORowImpl obj) {
                return obj.getItemTypeVO1();
            }

            public void put(BBLCLinesVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        ConfirmTypeVO1 {
            public Object get(BBLCLinesVORowImpl obj) {
                return obj.getConfirmTypeVO1();
            }

            public void put(BBLCLinesVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LCStatusVO1 {
            public Object get(BBLCLinesVORowImpl obj) {
                return obj.getLCStatusVO1();
            }

            public void put(BBLCLinesVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        CommTypeVO1 {
            public Object get(BBLCLinesVORowImpl obj) {
                return obj.getCommTypeVO1();
            }

            public void put(BBLCLinesVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        CountryVO1 {
            public Object get(BBLCLinesVORowImpl obj) {
                return obj.getCountryVO1();
            }

            public void put(BBLCLinesVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        CurrencyVO1 {
            public Object get(BBLCLinesVORowImpl obj) {
                return obj.getCurrencyVO1();
            }

            public void put(BBLCLinesVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        AmendmentTypeVO1 {
            public Object get(BBLCLinesVORowImpl obj) {
                return obj.getAmendmentTypeVO1();
            }

            public void put(BBLCLinesVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        PaymentModeVO1 {
            public Object get(BBLCLinesVORowImpl obj) {
                return obj.getPaymentModeVO1();
            }

            public void put(BBLCLinesVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        InsuranceCompanyNameLOV1 {
            public Object get(BBLCLinesVORowImpl obj) {
                return obj.getInsuranceCompanyNameLOV1();
            }

            public void put(BBLCLinesVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        InsuranceCompanyVO1 {
            public Object get(BBLCLinesVORowImpl obj) {
                return obj.getInsuranceCompanyVO1();
            }

            public void put(BBLCLinesVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(BBLCLinesVORowImpl object);

        public abstract void put(BBLCLinesVORowImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() +
                AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int IMPBBLCLINEID = AttributesEnum.ImpBblcLineId.index();
    public static final int IMPBBLCHEADERID = AttributesEnum.ImpBblcHeaderId.index();
    public static final int BBLCTYPE = AttributesEnum.BblcType.index();
    public static final int BBLCNO = AttributesEnum.BblcNo.index();
    public static final int LCISSUEDATE = AttributesEnum.LcIssueDate.index();
    public static final int LASTSHIPMENTDATE = AttributesEnum.LastShipmentDate.index();
    public static final int NEGOTIATIONDAY = AttributesEnum.NegotiationDay.index();
    public static final int EXPIRYDATE = AttributesEnum.ExpiryDate.index();
    public static final int INCOTERM = AttributesEnum.IncoTerm.index();
    public static final int USANCEPERIOD = AttributesEnum.UsancePeriod.index();
    public static final int SHIPMENTMODE = AttributesEnum.ShipmentMode.index();
    public static final int BENEFICIARYNAME = AttributesEnum.BeneficiaryName.index();
    public static final int PINO = AttributesEnum.PiNo.index();
    public static final int TOTALBBLCVALUE = AttributesEnum.TotalBblcValue.index();
    public static final int ITEM = AttributesEnum.Item.index();
    public static final int LCAFNO = AttributesEnum.LcafNo.index();
    public static final int COUNTRYOFORIGION = AttributesEnum.CountryOfOrigion.index();
    public static final int CONFIRMATION = AttributesEnum.Confirmation.index();
    public static final int CONFIRAMTIONCHARGES = AttributesEnum.ConfiramtionCharges.index();
    public static final int FREIGHTCHARGE = AttributesEnum.FreightCharge.index();
    public static final int OTHERCHARGE = AttributesEnum.OtherCharge.index();
    public static final int COMMISSION = AttributesEnum.Commission.index();
    public static final int INSURANCECOMPANYNAME = AttributesEnum.InsuranceCompanyName.index();
    public static final int INSURANCEPOLICYNO = AttributesEnum.InsurancePolicyNo.index();
    public static final int UDAMENDMENTNO = AttributesEnum.UdAmendmentNo.index();
    public static final int LCSTATUS = AttributesEnum.LcStatus.index();
    public static final int LASTUPDATELOGIN = AttributesEnum.LastUpdateLogin.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int ATTRIBUTE1 = AttributesEnum.Attribute1.index();
    public static final int ATTRIBUTE2 = AttributesEnum.Attribute2.index();
    public static final int ATTRIBUTE3 = AttributesEnum.Attribute3.index();
    public static final int ATTRIBUTE4 = AttributesEnum.Attribute4.index();
    public static final int ATTRIBUTE5 = AttributesEnum.Attribute5.index();
    public static final int ATTRIBUTE6 = AttributesEnum.Attribute6.index();
    public static final int ATTRIBUTE7 = AttributesEnum.Attribute7.index();
    public static final int ATTRIBUTE8 = AttributesEnum.Attribute8.index();
    public static final int ATTRIBUTE9 = AttributesEnum.Attribute9.index();
    public static final int ATTRIBUTE10 = AttributesEnum.Attribute10.index();
    public static final int ATTRIBUTE11 = AttributesEnum.Attribute11.index();
    public static final int ATTRIBUTE12 = AttributesEnum.Attribute12.index();
    public static final int ATTRIBUTE13 = AttributesEnum.Attribute13.index();
    public static final int ATTRIBUTE14 = AttributesEnum.Attribute14.index();
    public static final int ATTRIBUTE15 = AttributesEnum.Attribute15.index();
    public static final int ATTRIBUTE16 = AttributesEnum.Attribute16.index();
    public static final int ATTRIBUTE17 = AttributesEnum.Attribute17.index();
    public static final int ATTRIBUTE18 = AttributesEnum.Attribute18.index();
    public static final int ATTRIBUTE19 = AttributesEnum.Attribute19.index();
    public static final int ATTRIBUTE20 = AttributesEnum.Attribute20.index();
    public static final int ATTRIBUTE21 = AttributesEnum.Attribute21.index();
    public static final int ATTRIBUTE22 = AttributesEnum.Attribute22.index();
    public static final int ATTRIBUTE23 = AttributesEnum.Attribute23.index();
    public static final int ATTRIBUTE24 = AttributesEnum.Attribute24.index();
    public static final int ATTRIBUTE25 = AttributesEnum.Attribute25.index();
    public static final int ATTRIBUTE26 = AttributesEnum.Attribute26.index();
    public static final int ATTRIBUTE27 = AttributesEnum.Attribute27.index();
    public static final int ATTRIBUTE28 = AttributesEnum.Attribute28.index();
    public static final int ATTRIBUTE29 = AttributesEnum.Attribute29.index();
    public static final int ATTRIBUTE30 = AttributesEnum.Attribute30.index();
    public static final int COMMUNICATIONTYPE = AttributesEnum.CommunicationType.index();
    public static final int UPASSDAYS = AttributesEnum.UpassDays.index();
    public static final int INSURANCECOVERNOTEDATE = AttributesEnum.InsuranceCoverNoteDate.index();
    public static final int CURRENCY = AttributesEnum.Currency.index();
    public static final int CONVERSIONRATE = AttributesEnum.ConversionRate.index();
    public static final int CONVERTEDAMOUNT = AttributesEnum.ConvertedAmount.index();
    public static final int UDAMENDMENTNUMBER = AttributesEnum.UdAmendmentNumber.index();
    public static final int AMENDMENTDATE = AttributesEnum.AmendmentDate.index();
    public static final int CURR = AttributesEnum.Curr.index();
    public static final int BENEFICIARYID = AttributesEnum.BeneficiaryId.index();
    public static final int AMENDEDVALUE = AttributesEnum.AmendedValue.index();
    public static final int PAIDAMOUNTFORBBLC = AttributesEnum.PaidAmountForBblc.index();
    public static final int BBLCDETAILS = AttributesEnum.BBLCDetails.index();
    public static final int BBLCPIDETAILS = AttributesEnum.BBLCPiDetails.index();
    public static final int BBLCACCEPTANCE = AttributesEnum.BBLCAcceptance.index();
    public static final int BBLCTYPEVO1 = AttributesEnum.BBLCTypeVO1.index();
    public static final int INCOTERMSVO1 = AttributesEnum.IncoTermsVO1.index();
    public static final int USANCEVO1 = AttributesEnum.UsanceVO1.index();
    public static final int SHIPMODEVO1 = AttributesEnum.ShipModeVO1.index();
    public static final int SUPPLIERVO1 = AttributesEnum.SupplierVO1.index();
    public static final int ITEMTYPEVO1 = AttributesEnum.ItemTypeVO1.index();
    public static final int CONFIRMTYPEVO1 = AttributesEnum.ConfirmTypeVO1.index();
    public static final int LCSTATUSVO1 = AttributesEnum.LCStatusVO1.index();
    public static final int COMMTYPEVO1 = AttributesEnum.CommTypeVO1.index();
    public static final int COUNTRYVO1 = AttributesEnum.CountryVO1.index();
    public static final int CURRENCYVO1 = AttributesEnum.CurrencyVO1.index();
    public static final int AMENDMENTTYPEVO1 = AttributesEnum.AmendmentTypeVO1.index();
    public static final int PAYMENTMODEVO1 = AttributesEnum.PaymentModeVO1.index();
    public static final int INSURANCECOMPANYNAMELOV1 = AttributesEnum.InsuranceCompanyNameLOV1.index();
    public static final int INSURANCECOMPANYVO1 = AttributesEnum.InsuranceCompanyVO1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public BBLCLinesVORowImpl() {
    }

    /**
     * Gets BBLCLinesEO entity object.
     * @return the BBLCLinesEO
     */
    public BBLCLinesEOImpl getBBLCLinesEO() {
        return (BBLCLinesEOImpl)getEntity(0);
    }

    /**
     * Gets the attribute value for IMP_BBLC_LINE_ID using the alias name ImpBblcLineId.
     * @return the IMP_BBLC_LINE_ID
     */
    public Number getImpBblcLineId() {
        return (Number)getAttributeInternal(IMPBBLCLINEID);
    }

    /**
     * Sets <code>value</code> as attribute value for IMP_BBLC_LINE_ID using the alias name ImpBblcLineId.
     * @param value value to set the IMP_BBLC_LINE_ID
     */
    public void setImpBblcLineId(Number value) {
        setAttributeInternal(IMPBBLCLINEID, value);
    }

    /**
     * Gets the attribute value for IMP_BBLC_HEADER_ID using the alias name ImpBblcHeaderId.
     * @return the IMP_BBLC_HEADER_ID
     */
    public Number getImpBblcHeaderId() {
        return (Number)getAttributeInternal(IMPBBLCHEADERID);
    }

    /**
     * Sets <code>value</code> as attribute value for IMP_BBLC_HEADER_ID using the alias name ImpBblcHeaderId.
     * @param value value to set the IMP_BBLC_HEADER_ID
     */
    public void setImpBblcHeaderId(Number value) {
        setAttributeInternal(IMPBBLCHEADERID, value);
    }

    /**
     * Gets the attribute value for BBLC_TYPE using the alias name BblcType.
     * @return the BBLC_TYPE
     */
    public String getBblcType() {
        return (String)getAttributeInternal(BBLCTYPE);
    }

    /**
     * Sets <code>value</code> as attribute value for BBLC_TYPE using the alias name BblcType.
     * @param value value to set the BBLC_TYPE
     */
    public void setBblcType(String value) {
        setAttributeInternal(BBLCTYPE, value);
    }

    /**
     * Gets the attribute value for BBLC_NO using the alias name BblcNo.
     * @return the BBLC_NO
     */
    public String getBblcNo() {
        return (String)getAttributeInternal(BBLCNO);
    }

    /**
     * Sets <code>value</code> as attribute value for BBLC_NO using the alias name BblcNo.
     * @param value value to set the BBLC_NO
     */
    public void setBblcNo(String value) {
        setAttributeInternal(BBLCNO, value);
    }

    /**
     * Gets the attribute value for LC_ISSUE_DATE using the alias name LcIssueDate.
     * @return the LC_ISSUE_DATE
     */
    public Date getLcIssueDate() {
        return (Date)getAttributeInternal(LCISSUEDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for LC_ISSUE_DATE using the alias name LcIssueDate.
     * @param value value to set the LC_ISSUE_DATE
     */
    public void setLcIssueDate(Date value) {
        setAttributeInternal(LCISSUEDATE, value);
    }

    /**
     * Gets the attribute value for LAST_SHIPMENT_DATE using the alias name LastShipmentDate.
     * @return the LAST_SHIPMENT_DATE
     */
    public Date getLastShipmentDate() {
        return (Date)getAttributeInternal(LASTSHIPMENTDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_SHIPMENT_DATE using the alias name LastShipmentDate.
     * @param value value to set the LAST_SHIPMENT_DATE
     */
    public void setLastShipmentDate(Date value) {
        setAttributeInternal(LASTSHIPMENTDATE, value);
    }

    /**
     * Gets the attribute value for NEGOTIATION_DAY using the alias name NegotiationDay.
     * @return the NEGOTIATION_DAY
     */
    public String getNegotiationDay() {
        return (String)getAttributeInternal(NEGOTIATIONDAY);
    }

    /**
     * Sets <code>value</code> as attribute value for NEGOTIATION_DAY using the alias name NegotiationDay.
     * @param value value to set the NEGOTIATION_DAY
     */
    public void setNegotiationDay(String value) {
        setAttributeInternal(NEGOTIATIONDAY, value);
    }

    /**
     * Gets the attribute value for EXPIRY_DATE using the alias name ExpiryDate.
     * @return the EXPIRY_DATE
     */
    public Date getExpiryDate() {
        return (Date)getAttributeInternal(EXPIRYDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for EXPIRY_DATE using the alias name ExpiryDate.
     * @param value value to set the EXPIRY_DATE
     */
    public void setExpiryDate(Date value) {
        setAttributeInternal(EXPIRYDATE, value);
    }

    /**
     * Gets the attribute value for INCO_TERM using the alias name BblcLineIncoTerm.
     * @return the INCO_TERM
     */
    public String getIncoTerm() {
        return (String)getAttributeInternal(INCOTERM);
    }

    /**
     * Sets <code>value</code> as attribute value for INCO_TERM using the alias name BblcLineIncoTerm.
     * @param value value to set the INCO_TERM
     */
    public void setIncoTerm(String value) {
        setAttributeInternal(INCOTERM, value);
    }

    /**
     * Gets the attribute value for USANCE_PERIOD using the alias name UsancePeriod.
     * @return the USANCE_PERIOD
     */
    public String getUsancePeriod() {
        return (String)getAttributeInternal(USANCEPERIOD);
    }

    /**
     * Sets <code>value</code> as attribute value for USANCE_PERIOD using the alias name UsancePeriod.
     * @param value value to set the USANCE_PERIOD
     */
    public void setUsancePeriod(String value) {
        setAttributeInternal(USANCEPERIOD, value);
    }

    /**
     * Gets the attribute value for SHIPMENT_MODE using the alias name ShipmentMode.
     * @return the SHIPMENT_MODE
     */
    public String getShipmentMode() {
        return (String)getAttributeInternal(SHIPMENTMODE);
    }

    /**
     * Sets <code>value</code> as attribute value for SHIPMENT_MODE using the alias name ShipmentMode.
     * @param value value to set the SHIPMENT_MODE
     */
    public void setShipmentMode(String value) {
        setAttributeInternal(SHIPMENTMODE, value);
    }

    /**
     * Gets the attribute value for BENEFICIARY_NAME using the alias name BeneficiaryName.
     * @return the BENEFICIARY_NAME
     */
    public String getBeneficiaryName() {
        return (String)getAttributeInternal(BENEFICIARYNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for BENEFICIARY_NAME using the alias name BeneficiaryName.
     * @param value value to set the BENEFICIARY_NAME
     */
    public void setBeneficiaryName(String value) {
        setAttributeInternal(BENEFICIARYNAME, value);
    }

    /**
     * Gets the attribute value for PI_NO using the alias name PiNo.
     * @return the PI_NO
     */
    public String getPiNo() {
        return (String)getAttributeInternal(PINO);
    }

    /**
     * Sets <code>value</code> as attribute value for PI_NO using the alias name PiNo.
     * @param value value to set the PI_NO
     */
    public void setPiNo(String value) {
        setAttributeInternal(PINO, value);
    }

    /**
     * Gets the attribute value for TOTAL_BBLC_VALUE using the alias name TotalBblcValue.
     * @return the TOTAL_BBLC_VALUE
     */
    public Number getTotalBblcValue() {
        return (Number)getAttributeInternal(TOTALBBLCVALUE);
    }

    /**
     * Sets <code>value</code> as attribute value for TOTAL_BBLC_VALUE using the alias name TotalBblcValue.
     * @param value value to set the TOTAL_BBLC_VALUE
     */
    public void setTotalBblcValue(Number value) {
        setAttributeInternal(TOTALBBLCVALUE, value);
    }

    /**
     * Gets the attribute value for ITEM using the alias name Item.
     * @return the ITEM
     */
    public String getItem() {
        return (String)getAttributeInternal(ITEM);
    }

    /**
     * Sets <code>value</code> as attribute value for ITEM using the alias name Item.
     * @param value value to set the ITEM
     */
    public void setItem(String value) {
        setAttributeInternal(ITEM, value);
    }

    /**
     * Gets the attribute value for LCAF_NO using the alias name LcafNo.
     * @return the LCAF_NO
     */
    public String getLcafNo() {
        return (String)getAttributeInternal(LCAFNO);
    }

    /**
     * Sets <code>value</code> as attribute value for LCAF_NO using the alias name LcafNo.
     * @param value value to set the LCAF_NO
     */
    public void setLcafNo(String value) {
        setAttributeInternal(LCAFNO, value);
    }

    /**
     * Gets the attribute value for COUNTRY_OF_ORIGION using the alias name CountryOfOrigion.
     * @return the COUNTRY_OF_ORIGION
     */
    public String getCountryOfOrigion() {
        return (String)getAttributeInternal(COUNTRYOFORIGION);
    }

    /**
     * Sets <code>value</code> as attribute value for COUNTRY_OF_ORIGION using the alias name CountryOfOrigion.
     * @param value value to set the COUNTRY_OF_ORIGION
     */
    public void setCountryOfOrigion(String value) {
        setAttributeInternal(COUNTRYOFORIGION, value);
    }

    /**
     * Gets the attribute value for CONFIRMATION using the alias name Confirmation.
     * @return the CONFIRMATION
     */
    public String getConfirmation() {
        return (String)getAttributeInternal(CONFIRMATION);
    }

    /**
     * Sets <code>value</code> as attribute value for CONFIRMATION using the alias name Confirmation.
     * @param value value to set the CONFIRMATION
     */
    public void setConfirmation(String value) {
        setAttributeInternal(CONFIRMATION, value);
    }

    /**
     * Gets the attribute value for CONFIRAMTION_CHARGES using the alias name ConfiramtionCharges.
     * @return the CONFIRAMTION_CHARGES
     */
    public Number getConfiramtionCharges() {
        return (Number)getAttributeInternal(CONFIRAMTIONCHARGES);
    }

    /**
     * Sets <code>value</code> as attribute value for CONFIRAMTION_CHARGES using the alias name ConfiramtionCharges.
     * @param value value to set the CONFIRAMTION_CHARGES
     */
    public void setConfiramtionCharges(Number value) {
        setAttributeInternal(CONFIRAMTIONCHARGES, value);
    }

    /**
     * Gets the attribute value for FREIGHT_CHARGE using the alias name FreightCharge.
     * @return the FREIGHT_CHARGE
     */
    public Number getFreightCharge() {
        return (Number)getAttributeInternal(FREIGHTCHARGE);
    }

    /**
     * Sets <code>value</code> as attribute value for FREIGHT_CHARGE using the alias name FreightCharge.
     * @param value value to set the FREIGHT_CHARGE
     */
    public void setFreightCharge(Number value) {
        setAttributeInternal(FREIGHTCHARGE, value);
    }

    /**
     * Gets the attribute value for OTHER_CHARGE using the alias name OtherCharge.
     * @return the OTHER_CHARGE
     */
    public Number getOtherCharge() {
        return (Number)getAttributeInternal(OTHERCHARGE);
    }

    /**
     * Sets <code>value</code> as attribute value for OTHER_CHARGE using the alias name OtherCharge.
     * @param value value to set the OTHER_CHARGE
     */
    public void setOtherCharge(Number value) {
        setAttributeInternal(OTHERCHARGE, value);
    }

    /**
     * Gets the attribute value for COMMISSION using the alias name Commission.
     * @return the COMMISSION
     */
    public String getCommission() {
        return (String)getAttributeInternal(COMMISSION);
    }

    /**
     * Sets <code>value</code> as attribute value for COMMISSION using the alias name Commission.
     * @param value value to set the COMMISSION
     */
    public void setCommission(String value) {
        setAttributeInternal(COMMISSION, value);
    }

    /**
     * Gets the attribute value for INSURANCE_COMPANY_NAME using the alias name InsuranceCompanyName.
     * @return the INSURANCE_COMPANY_NAME
     */
    public String getInsuranceCompanyName() {
        return (String)getAttributeInternal(INSURANCECOMPANYNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for INSURANCE_COMPANY_NAME using the alias name InsuranceCompanyName.
     * @param value value to set the INSURANCE_COMPANY_NAME
     */
    public void setInsuranceCompanyName(String value) {
        setAttributeInternal(INSURANCECOMPANYNAME, value);
    }

    /**
     * Gets the attribute value for INSURANCE_POLICY_NO using the alias name InsurancePolicyNo.
     * @return the INSURANCE_POLICY_NO
     */
    public String getInsurancePolicyNo() {
        return (String)getAttributeInternal(INSURANCEPOLICYNO);
    }

    /**
     * Sets <code>value</code> as attribute value for INSURANCE_POLICY_NO using the alias name InsurancePolicyNo.
     * @param value value to set the INSURANCE_POLICY_NO
     */
    public void setInsurancePolicyNo(String value) {
        setAttributeInternal(INSURANCEPOLICYNO, value);
    }

    /**
     * Gets the attribute value for UD_AMENDMENT_NO using the alias name UdAmendmentNo.
     * @return the UD_AMENDMENT_NO
     */
    public String getUdAmendmentNo() {
        return (String)getAttributeInternal(UDAMENDMENTNO);
    }

    /**
     * Sets <code>value</code> as attribute value for UD_AMENDMENT_NO using the alias name UdAmendmentNo.
     * @param value value to set the UD_AMENDMENT_NO
     */
    public void setUdAmendmentNo(String value) {
        setAttributeInternal(UDAMENDMENTNO, value);
    }

    /**
     * Gets the attribute value for LC_STATUS using the alias name LcStatus.
     * @return the LC_STATUS
     */
    public String getLcStatus() {
        return (String)getAttributeInternal(LCSTATUS);
    }

    /**
     * Sets <code>value</code> as attribute value for LC_STATUS using the alias name LcStatus.
     * @param value value to set the LC_STATUS
     */
    public void setLcStatus(String value) {
        setAttributeInternal(LCSTATUS, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATE_LOGIN using the alias name LastUpdateLogin.
     * @return the LAST_UPDATE_LOGIN
     */
    public Number getLastUpdateLogin() {
        return (Number)getAttributeInternal(LASTUPDATELOGIN);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATE_LOGIN using the alias name LastUpdateLogin.
     * @param value value to set the LAST_UPDATE_LOGIN
     */
    public void setLastUpdateLogin(Number value) {
        setAttributeInternal(LASTUPDATELOGIN, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate.
     * @return the LAST_UPDATE_DATE
     */
    public Date getLastUpdateDate() {
        return (Date)getAttributeInternal(LASTUPDATEDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate.
     * @param value value to set the LAST_UPDATE_DATE
     */
    public void setLastUpdateDate(Date value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @return the LAST_UPDATED_BY
     */
    public Number getLastUpdatedBy() {
        return (Number)getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @param value value to set the LAST_UPDATED_BY
     */
    public void setLastUpdatedBy(Number value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for CREATION_DATE using the alias name CreationDate.
     * @return the CREATION_DATE
     */
    public Date getCreationDate() {
        return (Date)getAttributeInternal(CREATIONDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATION_DATE using the alias name CreationDate.
     * @param value value to set the CREATION_DATE
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**
     * Gets the attribute value for CREATED_BY using the alias name CreatedBy.
     * @return the CREATED_BY
     */
    public Number getCreatedBy() {
        return (Number)getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy.
     * @param value value to set the CREATED_BY
     */
    public void setCreatedBy(Number value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE1 using the alias name Attribute1.
     * @return the ATTRIBUTE1
     */
    public String getAttribute1() {
        return (String)getAttributeInternal(ATTRIBUTE1);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE1 using the alias name Attribute1.
     * @param value value to set the ATTRIBUTE1
     */
    public void setAttribute1(String value) {
        setAttributeInternal(ATTRIBUTE1, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE2 using the alias name Attribute2.
     * @return the ATTRIBUTE2
     */
    public String getAttribute2() {
        return (String)getAttributeInternal(ATTRIBUTE2);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE2 using the alias name Attribute2.
     * @param value value to set the ATTRIBUTE2
     */
    public void setAttribute2(String value) {
        setAttributeInternal(ATTRIBUTE2, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE3 using the alias name Attribute3.
     * @return the ATTRIBUTE3
     */
    public String getAttribute3() {
        return (String)getAttributeInternal(ATTRIBUTE3);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE3 using the alias name Attribute3.
     * @param value value to set the ATTRIBUTE3
     */
    public void setAttribute3(String value) {
        setAttributeInternal(ATTRIBUTE3, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE4 using the alias name Attribute4.
     * @return the ATTRIBUTE4
     */
    public String getAttribute4() {
        return (String)getAttributeInternal(ATTRIBUTE4);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE4 using the alias name Attribute4.
     * @param value value to set the ATTRIBUTE4
     */
    public void setAttribute4(String value) {
        setAttributeInternal(ATTRIBUTE4, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE5 using the alias name Attribute5.
     * @return the ATTRIBUTE5
     */
    public String getAttribute5() {
        return (String)getAttributeInternal(ATTRIBUTE5);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE5 using the alias name Attribute5.
     * @param value value to set the ATTRIBUTE5
     */
    public void setAttribute5(String value) {
        setAttributeInternal(ATTRIBUTE5, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE6 using the alias name Attribute6.
     * @return the ATTRIBUTE6
     */
    public String getAttribute6() {
        return (String)getAttributeInternal(ATTRIBUTE6);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE6 using the alias name Attribute6.
     * @param value value to set the ATTRIBUTE6
     */
    public void setAttribute6(String value) {
        setAttributeInternal(ATTRIBUTE6, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE7 using the alias name Attribute7.
     * @return the ATTRIBUTE7
     */
    public String getAttribute7() {
        return (String)getAttributeInternal(ATTRIBUTE7);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE7 using the alias name Attribute7.
     * @param value value to set the ATTRIBUTE7
     */
    public void setAttribute7(String value) {
        setAttributeInternal(ATTRIBUTE7, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE8 using the alias name Attribute8.
     * @return the ATTRIBUTE8
     */
    public String getAttribute8() {
        return (String)getAttributeInternal(ATTRIBUTE8);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE8 using the alias name Attribute8.
     * @param value value to set the ATTRIBUTE8
     */
    public void setAttribute8(String value) {
        setAttributeInternal(ATTRIBUTE8, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE9 using the alias name Attribute9.
     * @return the ATTRIBUTE9
     */
    public String getAttribute9() {
        return (String)getAttributeInternal(ATTRIBUTE9);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE9 using the alias name Attribute9.
     * @param value value to set the ATTRIBUTE9
     */
    public void setAttribute9(String value) {
        setAttributeInternal(ATTRIBUTE9, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE10 using the alias name Attribute10.
     * @return the ATTRIBUTE10
     */
    public String getAttribute10() {
        return (String)getAttributeInternal(ATTRIBUTE10);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE10 using the alias name Attribute10.
     * @param value value to set the ATTRIBUTE10
     */
    public void setAttribute10(String value) {
        setAttributeInternal(ATTRIBUTE10, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE11 using the alias name Attribute11.
     * @return the ATTRIBUTE11
     */
    public String getAttribute11() {
        return (String)getAttributeInternal(ATTRIBUTE11);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE11 using the alias name Attribute11.
     * @param value value to set the ATTRIBUTE11
     */
    public void setAttribute11(String value) {
        setAttributeInternal(ATTRIBUTE11, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE12 using the alias name Attribute12.
     * @return the ATTRIBUTE12
     */
    public String getAttribute12() {
        return (String)getAttributeInternal(ATTRIBUTE12);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE12 using the alias name Attribute12.
     * @param value value to set the ATTRIBUTE12
     */
    public void setAttribute12(String value) {
        setAttributeInternal(ATTRIBUTE12, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE13 using the alias name Attribute13.
     * @return the ATTRIBUTE13
     */
    public String getAttribute13() {
        return (String)getAttributeInternal(ATTRIBUTE13);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE13 using the alias name Attribute13.
     * @param value value to set the ATTRIBUTE13
     */
    public void setAttribute13(String value) {
        setAttributeInternal(ATTRIBUTE13, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE14 using the alias name Attribute14.
     * @return the ATTRIBUTE14
     */
    public String getAttribute14() {
        return (String)getAttributeInternal(ATTRIBUTE14);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE14 using the alias name Attribute14.
     * @param value value to set the ATTRIBUTE14
     */
    public void setAttribute14(String value) {
        setAttributeInternal(ATTRIBUTE14, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE15 using the alias name Attribute15.
     * @return the ATTRIBUTE15
     */
    public String getAttribute15() {
        return (String)getAttributeInternal(ATTRIBUTE15);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE15 using the alias name Attribute15.
     * @param value value to set the ATTRIBUTE15
     */
    public void setAttribute15(String value) {
        setAttributeInternal(ATTRIBUTE15, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE16 using the alias name Attribute16.
     * @return the ATTRIBUTE16
     */
    public String getAttribute16() {
        return (String)getAttributeInternal(ATTRIBUTE16);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE16 using the alias name Attribute16.
     * @param value value to set the ATTRIBUTE16
     */
    public void setAttribute16(String value) {
        setAttributeInternal(ATTRIBUTE16, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE17 using the alias name Attribute17.
     * @return the ATTRIBUTE17
     */
    public String getAttribute17() {
        return (String)getAttributeInternal(ATTRIBUTE17);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE17 using the alias name Attribute17.
     * @param value value to set the ATTRIBUTE17
     */
    public void setAttribute17(String value) {
        setAttributeInternal(ATTRIBUTE17, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE18 using the alias name Attribute18.
     * @return the ATTRIBUTE18
     */
    public String getAttribute18() {
        return (String)getAttributeInternal(ATTRIBUTE18);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE18 using the alias name Attribute18.
     * @param value value to set the ATTRIBUTE18
     */
    public void setAttribute18(String value) {
        setAttributeInternal(ATTRIBUTE18, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE19 using the alias name Attribute19.
     * @return the ATTRIBUTE19
     */
    public String getAttribute19() {
        return (String)getAttributeInternal(ATTRIBUTE19);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE19 using the alias name Attribute19.
     * @param value value to set the ATTRIBUTE19
     */
    public void setAttribute19(String value) {
        setAttributeInternal(ATTRIBUTE19, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE20 using the alias name Attribute20.
     * @return the ATTRIBUTE20
     */
    public String getAttribute20() {
        return (String)getAttributeInternal(ATTRIBUTE20);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE20 using the alias name Attribute20.
     * @param value value to set the ATTRIBUTE20
     */
    public void setAttribute20(String value) {
        setAttributeInternal(ATTRIBUTE20, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE21 using the alias name Attribute21.
     * @return the ATTRIBUTE21
     */
    public String getAttribute21() {
        return (String)getAttributeInternal(ATTRIBUTE21);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE21 using the alias name Attribute21.
     * @param value value to set the ATTRIBUTE21
     */
    public void setAttribute21(String value) {
        setAttributeInternal(ATTRIBUTE21, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE22 using the alias name Attribute22.
     * @return the ATTRIBUTE22
     */
    public String getAttribute22() {
        return (String)getAttributeInternal(ATTRIBUTE22);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE22 using the alias name Attribute22.
     * @param value value to set the ATTRIBUTE22
     */
    public void setAttribute22(String value) {
        setAttributeInternal(ATTRIBUTE22, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE23 using the alias name Attribute23.
     * @return the ATTRIBUTE23
     */
    public String getAttribute23() {
        return (String)getAttributeInternal(ATTRIBUTE23);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE23 using the alias name Attribute23.
     * @param value value to set the ATTRIBUTE23
     */
    public void setAttribute23(String value) {
        setAttributeInternal(ATTRIBUTE23, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE24 using the alias name Attribute24.
     * @return the ATTRIBUTE24
     */
    public String getAttribute24() {
        return (String)getAttributeInternal(ATTRIBUTE24);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE24 using the alias name Attribute24.
     * @param value value to set the ATTRIBUTE24
     */
    public void setAttribute24(String value) {
        setAttributeInternal(ATTRIBUTE24, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE25 using the alias name Attribute25.
     * @return the ATTRIBUTE25
     */
    public String getAttribute25() {
        return (String)getAttributeInternal(ATTRIBUTE25);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE25 using the alias name Attribute25.
     * @param value value to set the ATTRIBUTE25
     */
    public void setAttribute25(String value) {
        setAttributeInternal(ATTRIBUTE25, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE26 using the alias name Attribute26.
     * @return the ATTRIBUTE26
     */
    public String getAttribute26() {
        return (String)getAttributeInternal(ATTRIBUTE26);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE26 using the alias name Attribute26.
     * @param value value to set the ATTRIBUTE26
     */
    public void setAttribute26(String value) {
        setAttributeInternal(ATTRIBUTE26, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE27 using the alias name Attribute27.
     * @return the ATTRIBUTE27
     */
    public String getAttribute27() {
        return (String)getAttributeInternal(ATTRIBUTE27);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE27 using the alias name Attribute27.
     * @param value value to set the ATTRIBUTE27
     */
    public void setAttribute27(String value) {
        setAttributeInternal(ATTRIBUTE27, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE28 using the alias name Attribute28.
     * @return the ATTRIBUTE28
     */
    public String getAttribute28() {
        return (String)getAttributeInternal(ATTRIBUTE28);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE28 using the alias name Attribute28.
     * @param value value to set the ATTRIBUTE28
     */
    public void setAttribute28(String value) {
        setAttributeInternal(ATTRIBUTE28, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE29 using the alias name Attribute29.
     * @return the ATTRIBUTE29
     */
    public String getAttribute29() {
        return (String)getAttributeInternal(ATTRIBUTE29);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE29 using the alias name Attribute29.
     * @param value value to set the ATTRIBUTE29
     */
    public void setAttribute29(String value) {
        setAttributeInternal(ATTRIBUTE29, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE30 using the alias name Attribute30.
     * @return the ATTRIBUTE30
     */
    public String getAttribute30() {
        return (String)getAttributeInternal(ATTRIBUTE30);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE30 using the alias name Attribute30.
     * @param value value to set the ATTRIBUTE30
     */
    public void setAttribute30(String value) {
        setAttributeInternal(ATTRIBUTE30, value);
    }

    /**
     * Gets the attribute value for COMMUNICATION_TYPE using the alias name CommunicationType.
     * @return the COMMUNICATION_TYPE
     */
    public String getCommunicationType() {
        return (String)getAttributeInternal(COMMUNICATIONTYPE);
    }

    /**
     * Sets <code>value</code> as attribute value for COMMUNICATION_TYPE using the alias name CommunicationType.
     * @param value value to set the COMMUNICATION_TYPE
     */
    public void setCommunicationType(String value) {
        setAttributeInternal(COMMUNICATIONTYPE, value);
    }

    /**
     * Gets the attribute value for UPASS_DAYS using the alias name UpassDays.
     * @return the UPASS_DAYS
     */
    public Number getUpassDays() {
        return (Number)getAttributeInternal(UPASSDAYS);
    }

    /**
     * Sets <code>value</code> as attribute value for UPASS_DAYS using the alias name UpassDays.
     * @param value value to set the UPASS_DAYS
     */
    public void setUpassDays(Number value) {
        setAttributeInternal(UPASSDAYS, value);
    }

    /**
     * Gets the attribute value for INSURANCE_COVER_NOTE_DATE using the alias name InsuranceCoverNoteDate.
     * @return the INSURANCE_COVER_NOTE_DATE
     */
    public Date getInsuranceCoverNoteDate() {
        return (Date)getAttributeInternal(INSURANCECOVERNOTEDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for INSURANCE_COVER_NOTE_DATE using the alias name InsuranceCoverNoteDate.
     * @param value value to set the INSURANCE_COVER_NOTE_DATE
     */
    public void setInsuranceCoverNoteDate(Date value) {
        setAttributeInternal(INSURANCECOVERNOTEDATE, value);
    }

    /**
     * Gets the attribute value for CURRENCY using the alias name Currency.
     * @return the CURRENCY
     */
    public String getCurrency() {
        return (String)getAttributeInternal(CURRENCY);
    }

    /**
     * Sets <code>value</code> as attribute value for CURRENCY using the alias name Currency.
     * @param value value to set the CURRENCY
     */
    public void setCurrency(String value) {
        setAttributeInternal(CURRENCY, value);
    }

    /**
     * Gets the attribute value for CONVERSION_RATE using the alias name ConversionRate.
     * @return the CONVERSION_RATE
     */
    public Number getConversionRate() {
        return (Number)getAttributeInternal(CONVERSIONRATE);
    }

    /**
     * Sets <code>value</code> as attribute value for CONVERSION_RATE using the alias name ConversionRate.
     * @param value value to set the CONVERSION_RATE
     */
    public void setConversionRate(Number value) {
        setAttributeInternal(CONVERSIONRATE, value);
    }

    /**
     * Gets the attribute value for CONVERTED_AMOUNT using the alias name ConvertedAmount.
     * @return the CONVERTED_AMOUNT
     */
    public Number getConvertedAmount() {
        return (Number)getAttributeInternal(CONVERTEDAMOUNT);
    }

    /**
     * Sets <code>value</code> as attribute value for CONVERTED_AMOUNT using the alias name ConvertedAmount.
     * @param value value to set the CONVERTED_AMOUNT
     */
    public void setConvertedAmount(Number value) {
        setAttributeInternal(CONVERTEDAMOUNT, value);
    }

    /**
     * Gets the attribute value for the calculated attribute UdAmendmentNumber.
     * @return the UdAmendmentNumber
     */
    public String getUdAmendmentNumber() {
        StringBuilder sb ;
        try{
            sb = new StringBuilder((String)getAttributeInternal(UDAMENDMENTNUMBER));
        }
        catch(NullPointerException e){
            return (String)getAttributeInternal(UDAMENDMENTNUMBER);
        }
        sb= sb.delete(0,sb.lastIndexOf("UD")+3);
        return sb.toString();
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute UdAmendmentNumber.
     * @param value value to set the  UdAmendmentNumber
     */
    public void setUdAmendmentNumber(String value) {
        setAttributeInternal(UDAMENDMENTNUMBER, value);
    }

    /**
     * Gets the attribute value for AMENDMENT_DATE using the alias name AmendmentDate.
     * @return the AMENDMENT_DATE
     */
    public Date getAmendmentDate() {
        return (Date) getAttributeInternal(AMENDMENTDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for AMENDMENT_DATE using the alias name AmendmentDate.
     * @param value value to set the AMENDMENT_DATE
     */
    public void setAmendmentDate(Date value) {
        setAttributeInternal(AMENDMENTDATE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Curr.
     * @return the Curr
     */
    public String getCurr() {
        return (String) getAttributeInternal(CURR);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Curr.
     * @param value value to set the  Curr
     */
    public void setCurr(String value) {
        setAttributeInternal(CURR, value);
    }


    /**
     * Gets the attribute value for the calculated attribute BeneficiaryId.
     * @return the BeneficiaryId
     */
    public Number getBeneficiaryId() {
        return (Number) getAttributeInternal(BENEFICIARYID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute BeneficiaryId.
     * @param value value to set the  BeneficiaryId
     */
    public void setBeneficiaryId(Number value) {
        setAttributeInternal(BENEFICIARYID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute AmendedValue.
     * @return the AmendedValue
     */
    public Number getAmendedValue() {
        return (Number) getAttributeInternal(AMENDEDVALUE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute AmendedValue.
     * @param value value to set the  AmendedValue
     */
    public void setAmendedValue(Number value) {
        setAttributeInternal(AMENDEDVALUE, value);
    }

    /**
     * Gets the attribute value for PAID_AMOUNT_FOR_BBLC using the alias name PaidAmountForBblc.
     * @return the PAID_AMOUNT_FOR_BBLC
     */
    public Number getPaidAmountForBblc() {
        return (Number) getAttributeInternal(PAIDAMOUNTFORBBLC);
    }

    /**
     * Sets <code>value</code> as attribute value for PAID_AMOUNT_FOR_BBLC using the alias name PaidAmountForBblc.
     * @param value value to set the PAID_AMOUNT_FOR_BBLC
     */
    public void setPaidAmountForBblc(Number value) {
        setAttributeInternal(PAIDAMOUNTFORBBLC, value);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link BBLCDetails.
     */
    public RowIterator getBBLCDetails() {
        return (RowIterator)getAttributeInternal(BBLCDETAILS);
    }


    /**
     * Gets the associated <code>RowIterator</code> using master-detail link BBLCPiDetails.
     */
    public RowIterator getBBLCPiDetails() {
        return (RowIterator)getAttributeInternal(BBLCPIDETAILS);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link BBLCAcceptance.
     */
    public RowIterator getBBLCAcceptance() {
        return (RowIterator)getAttributeInternal(BBLCACCEPTANCE);
    }


    /**
     * Gets the view accessor <code>RowSet</code> BBLCTypeVO1.
     */
    public RowSet getBBLCTypeVO1() {
        return (RowSet)getAttributeInternal(BBLCTYPEVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> IncoTermsVO1.
     */
    public RowSet getIncoTermsVO1() {
        return (RowSet)getAttributeInternal(INCOTERMSVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> UsanceVO1.
     */
    public RowSet getUsanceVO1() {
        return (RowSet)getAttributeInternal(USANCEVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> ShipModeVO1.
     */
    public RowSet getShipModeVO1() {
        return (RowSet)getAttributeInternal(SHIPMODEVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> SupplierVO1.
     */
    public RowSet getSupplierVO1() {
        return (RowSet)getAttributeInternal(SUPPLIERVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> ItemTypeVO1.
     */
    public RowSet getItemTypeVO1() {
        return (RowSet)getAttributeInternal(ITEMTYPEVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> ConfirmTypeVO1.
     */
    public RowSet getConfirmTypeVO1() {
        return (RowSet)getAttributeInternal(CONFIRMTYPEVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> LCStatusVO1.
     */
    public RowSet getLCStatusVO1() {
        return (RowSet)getAttributeInternal(LCSTATUSVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> CommTypeVO1.
     */
    public RowSet getCommTypeVO1() {
        return (RowSet)getAttributeInternal(COMMTYPEVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> CountryVO1.
     */
    public RowSet getCountryVO1() {
        return (RowSet)getAttributeInternal(COUNTRYVO1);
    }


    /**
     * Gets the view accessor <code>RowSet</code> CurrencyVO1.
     */
    public RowSet getCurrencyVO1() {
        return (RowSet)getAttributeInternal(CURRENCYVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AmendmentTypeVO1.
     */
    public RowSet getAmendmentTypeVO1() {
        return (RowSet)getAttributeInternal(AMENDMENTTYPEVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> PaymentModeVO1.
     */
    public RowSet getPaymentModeVO1() {
        return (RowSet)getAttributeInternal(PAYMENTMODEVO1);
    }


    /**
     * Gets the view accessor <code>RowSet</code> InsuranceCompanyNameLOV1.
     */
    public RowSet getInsuranceCompanyNameLOV1() {
        return (RowSet)getAttributeInternal(INSURANCECOMPANYNAMELOV1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> InsuranceCompanyVO1.
     */
    public RowSet getInsuranceCompanyVO1() {
        return (RowSet)getAttributeInternal(INSURANCECOMPANYVO1);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
