package mnj.ont.model.views;

import mnj.ont.model.entities.BBLCHeaderEOImpl;

import oracle.jbo.RowIterator;
import oracle.jbo.RowSet;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Apr 23 17:45:26 BDT 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class BBLCHeaderVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        ImpBblcHeaderId {
            public Object get(BBLCHeaderVORowImpl obj) {
                return obj.getImpBblcHeaderId();
            }

            public void put(BBLCHeaderVORowImpl obj, Object value) {
                obj.setImpBblcHeaderId((Number)value);
            }
        }
        ,
        ProposalNumber {
            public Object get(BBLCHeaderVORowImpl obj) {
                return obj.getProposalNumber();
            }

            public void put(BBLCHeaderVORowImpl obj, Object value) {
                obj.setProposalNumber((String)value);
            }
        }
        ,
        ProposalDate {
            public Object get(BBLCHeaderVORowImpl obj) {
                return obj.getProposalDate();
            }

            public void put(BBLCHeaderVORowImpl obj, Object value) {
                obj.setProposalDate((Date)value);
            }
        }
        ,
        ImportAgainstContract {
            public Object get(BBLCHeaderVORowImpl obj) {
                return obj.getImportAgainstContract();
            }

            public void put(BBLCHeaderVORowImpl obj, Object value) {
                obj.setImportAgainstContract((String)value);
            }
        }
        ,
        NegotiationBank {
            public Object get(BBLCHeaderVORowImpl obj) {
                return obj.getNegotiationBank();
            }

            public void put(BBLCHeaderVORowImpl obj, Object value) {
                obj.setNegotiationBank((String)value);
            }
        }
        ,
        ContractValue {
            public Object get(BBLCHeaderVORowImpl obj) {
                return obj.getContractValue();
            }

            public void put(BBLCHeaderVORowImpl obj, Object value) {
                obj.setContractValue((Number)value);
            }
        }
        ,
        LastShipDate {
            public Object get(BBLCHeaderVORowImpl obj) {
                return obj.getLastShipDate();
            }

            public void put(BBLCHeaderVORowImpl obj, Object value) {
                obj.setLastShipDate((Date)value);
            }
        }
        ,
        EntitleBtbValue {
            public Object get(BBLCHeaderVORowImpl obj) {
                return obj.getEntitleBtbValue();
            }

            public void put(BBLCHeaderVORowImpl obj, Object value) {
                obj.setEntitleBtbValue((Double)value);
            }
        }
        ,
        AvailableBtbValue {
            public Object get(BBLCHeaderVORowImpl obj) {
                return obj.getAvailableBtbValue();
            }

            public void put(BBLCHeaderVORowImpl obj, Object value) {
                obj.setAvailableBtbValue((Double)value);
            }
        }
        ,
        VersionNo {
            public Object get(BBLCHeaderVORowImpl obj) {
                return obj.getVersionNo();
            }

            public void put(BBLCHeaderVORowImpl obj, Object value) {
                obj.setVersionNo((Number)value);
            }
        }
        ,
        VersionDate {
            public Object get(BBLCHeaderVORowImpl obj) {
                return obj.getVersionDate();
            }

            public void put(BBLCHeaderVORowImpl obj, Object value) {
                obj.setVersionDate((Date)value);
            }
        }
        ,
        OrgId {
            public Object get(BBLCHeaderVORowImpl obj) {
                return obj.getOrgId();
            }

            public void put(BBLCHeaderVORowImpl obj, Object value) {
                obj.setOrgId((Number)value);
            }
        }
        ,
        LastUpdateLogin {
            public Object get(BBLCHeaderVORowImpl obj) {
                return obj.getLastUpdateLogin();
            }

            public void put(BBLCHeaderVORowImpl obj, Object value) {
                obj.setLastUpdateLogin((Number)value);
            }
        }
        ,
        LastUpdateDate {
            public Object get(BBLCHeaderVORowImpl obj) {
                return obj.getLastUpdateDate();
            }

            public void put(BBLCHeaderVORowImpl obj, Object value) {
                obj.setLastUpdateDate((Date)value);
            }
        }
        ,
        LastUpdatedBy {
            public Object get(BBLCHeaderVORowImpl obj) {
                return obj.getLastUpdatedBy();
            }

            public void put(BBLCHeaderVORowImpl obj, Object value) {
                obj.setLastUpdatedBy((Number)value);
            }
        }
        ,
        CreationDate {
            public Object get(BBLCHeaderVORowImpl obj) {
                return obj.getCreationDate();
            }

            public void put(BBLCHeaderVORowImpl obj, Object value) {
                obj.setCreationDate((Date)value);
            }
        }
        ,
        CreatedBy {
            public Object get(BBLCHeaderVORowImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(BBLCHeaderVORowImpl obj, Object value) {
                obj.setCreatedBy((Number)value);
            }
        }
        ,
        Attribute1 {
            public Object get(BBLCHeaderVORowImpl obj) {
                return obj.getAttribute1();
            }

            public void put(BBLCHeaderVORowImpl obj, Object value) {
                obj.setAttribute1((Double)value);
            }
        }
        ,
        Attribute2 {
            public Object get(BBLCHeaderVORowImpl obj) {
                return obj.getAttribute2();
            }

            public void put(BBLCHeaderVORowImpl obj, Object value) {
                obj.setAttribute2((Double)value);
            }
        }
        ,
        Attribute3 {
            public Object get(BBLCHeaderVORowImpl obj) {
                return obj.getAttribute3();
            }

            public void put(BBLCHeaderVORowImpl obj, Object value) {
                obj.setAttribute3((Double)value);
            }
        }
        ,
        Attribute4 {
            public Object get(BBLCHeaderVORowImpl obj) {
                return obj.getAttribute4();
            }

            public void put(BBLCHeaderVORowImpl obj, Object value) {
                obj.setAttribute4((Double)value);
            }
        }
        ,
        Attribute5 {
            public Object get(BBLCHeaderVORowImpl obj) {
                return obj.getAttribute5();
            }

            public void put(BBLCHeaderVORowImpl obj, Object value) {
                obj.setAttribute5((Double)value);
            }
        }
        ,
        Attribute6 {
            public Object get(BBLCHeaderVORowImpl obj) {
                return obj.getAttribute6();
            }

            public void put(BBLCHeaderVORowImpl obj, Object value) {
                obj.setAttribute6((Double)value);
            }
        }
        ,
        Attribute7 {
            public Object get(BBLCHeaderVORowImpl obj) {
                return obj.getAttribute7();
            }

            public void put(BBLCHeaderVORowImpl obj, Object value) {
                obj.setAttribute7((String)value);
            }
        }
        ,
        Attribute8 {
            public Object get(BBLCHeaderVORowImpl obj) {
                return obj.getAttribute8();
            }

            public void put(BBLCHeaderVORowImpl obj, Object value) {
                obj.setAttribute8((String)value);
            }
        }
        ,
        Attribute9 {
            public Object get(BBLCHeaderVORowImpl obj) {
                return obj.getAttribute9();
            }

            public void put(BBLCHeaderVORowImpl obj, Object value) {
                obj.setAttribute9((String)value);
            }
        }
        ,
        Attribute10 {
            public Object get(BBLCHeaderVORowImpl obj) {
                return obj.getAttribute10();
            }

            public void put(BBLCHeaderVORowImpl obj, Object value) {
                obj.setAttribute10((String)value);
            }
        }
        ,
        Attribute11 {
            public Object get(BBLCHeaderVORowImpl obj) {
                return obj.getAttribute11();
            }

            public void put(BBLCHeaderVORowImpl obj, Object value) {
                obj.setAttribute11((String)value);
            }
        }
        ,
        Attribute12 {
            public Object get(BBLCHeaderVORowImpl obj) {
                return obj.getAttribute12();
            }

            public void put(BBLCHeaderVORowImpl obj, Object value) {
                obj.setAttribute12((String)value);
            }
        }
        ,
        Attribute13 {
            public Object get(BBLCHeaderVORowImpl obj) {
                return obj.getAttribute13();
            }

            public void put(BBLCHeaderVORowImpl obj, Object value) {
                obj.setAttribute13((String)value);
            }
        }
        ,
        Attribute14 {
            public Object get(BBLCHeaderVORowImpl obj) {
                return obj.getAttribute14();
            }

            public void put(BBLCHeaderVORowImpl obj, Object value) {
                obj.setAttribute14((String)value);
            }
        }
        ,
        Attribute15 {
            public Object get(BBLCHeaderVORowImpl obj) {
                return obj.getAttribute15();
            }

            public void put(BBLCHeaderVORowImpl obj, Object value) {
                obj.setAttribute15((String)value);
            }
        }
        ,
        Attribute16 {
            public Object get(BBLCHeaderVORowImpl obj) {
                return obj.getAttribute16();
            }

            public void put(BBLCHeaderVORowImpl obj, Object value) {
                obj.setAttribute16((String)value);
            }
        }
        ,
        Attribute17 {
            public Object get(BBLCHeaderVORowImpl obj) {
                return obj.getAttribute17();
            }

            public void put(BBLCHeaderVORowImpl obj, Object value) {
                obj.setAttribute17((String)value);
            }
        }
        ,
        Attribute18 {
            public Object get(BBLCHeaderVORowImpl obj) {
                return obj.getAttribute18();
            }

            public void put(BBLCHeaderVORowImpl obj, Object value) {
                obj.setAttribute18((String)value);
            }
        }
        ,
        Attribute19 {
            public Object get(BBLCHeaderVORowImpl obj) {
                return obj.getAttribute19();
            }

            public void put(BBLCHeaderVORowImpl obj, Object value) {
                obj.setAttribute19((String)value);
            }
        }
        ,
        Attribute20 {
            public Object get(BBLCHeaderVORowImpl obj) {
                return obj.getAttribute20();
            }

            public void put(BBLCHeaderVORowImpl obj, Object value) {
                obj.setAttribute20((String)value);
            }
        }
        ,
        Attribute21 {
            public Object get(BBLCHeaderVORowImpl obj) {
                return obj.getAttribute21();
            }

            public void put(BBLCHeaderVORowImpl obj, Object value) {
                obj.setAttribute21((String)value);
            }
        }
        ,
        Attribute22 {
            public Object get(BBLCHeaderVORowImpl obj) {
                return obj.getAttribute22();
            }

            public void put(BBLCHeaderVORowImpl obj, Object value) {
                obj.setAttribute22((String)value);
            }
        }
        ,
        Attribute23 {
            public Object get(BBLCHeaderVORowImpl obj) {
                return obj.getAttribute23();
            }

            public void put(BBLCHeaderVORowImpl obj, Object value) {
                obj.setAttribute23((String)value);
            }
        }
        ,
        Attribute24 {
            public Object get(BBLCHeaderVORowImpl obj) {
                return obj.getAttribute24();
            }

            public void put(BBLCHeaderVORowImpl obj, Object value) {
                obj.setAttribute24((String)value);
            }
        }
        ,
        Attribute25 {
            public Object get(BBLCHeaderVORowImpl obj) {
                return obj.getAttribute25();
            }

            public void put(BBLCHeaderVORowImpl obj, Object value) {
                obj.setAttribute25((String)value);
            }
        }
        ,
        Attribute26 {
            public Object get(BBLCHeaderVORowImpl obj) {
                return obj.getAttribute26();
            }

            public void put(BBLCHeaderVORowImpl obj, Object value) {
                obj.setAttribute26((String)value);
            }
        }
        ,
        Attribute27 {
            public Object get(BBLCHeaderVORowImpl obj) {
                return obj.getAttribute27();
            }

            public void put(BBLCHeaderVORowImpl obj, Object value) {
                obj.setAttribute27((String)value);
            }
        }
        ,
        Attribute28 {
            public Object get(BBLCHeaderVORowImpl obj) {
                return obj.getAttribute28();
            }

            public void put(BBLCHeaderVORowImpl obj, Object value) {
                obj.setAttribute28((String)value);
            }
        }
        ,
        Attribute29 {
            public Object get(BBLCHeaderVORowImpl obj) {
                return obj.getAttribute29();
            }

            public void put(BBLCHeaderVORowImpl obj, Object value) {
                obj.setAttribute29((String)value);
            }
        }
        ,
        OrgName {
            public Object get(BBLCHeaderVORowImpl obj) {
                return obj.getOrgName();
            }

            public void put(BBLCHeaderVORowImpl obj, Object value) {
                obj.setOrgName((String)value);
            }
        }
        ,
        OrgShortName {
            public Object get(BBLCHeaderVORowImpl obj) {
                return obj.getOrgShortName();
            }

            public void put(BBLCHeaderVORowImpl obj, Object value) {
                obj.setOrgShortName((String)value);
            }
        }
        ,
        Attribute30 {
            public Object get(BBLCHeaderVORowImpl obj) {
                return obj.getAttribute30();
            }

            public void put(BBLCHeaderVORowImpl obj, Object value) {
                obj.setAttribute30((String)value);
            }
        }
        ,
        BblcDocNumber {
            public Object get(BBLCHeaderVORowImpl obj) {
                return obj.getBblcDocNumber();
            }

            public void put(BBLCHeaderVORowImpl obj, Object value) {
                obj.setBblcDocNumber((Number)value);
            }
        }
        ,
        PaidAmountForProposal {
            public Object get(BBLCHeaderVORowImpl obj) {
                return obj.getPaidAmountForProposal();
            }

            public void put(BBLCHeaderVORowImpl obj, Object value) {
                obj.setPaidAmountForProposal((Number)value);
            }
        }
        ,
        ProposalNoNew {
            public Object get(BBLCHeaderVORowImpl obj) {
                return obj.getProposalNoNew();
            }

            public void put(BBLCHeaderVORowImpl obj, Object value) {
                obj.setProposalNoNew((String)value);
            }
        }
        ,
        NegotiationBankId {
            public Object get(BBLCHeaderVORowImpl obj) {
                return obj.getNegotiationBankId();
            }

            public void put(BBLCHeaderVORowImpl obj, Object value) {
                obj.setNegotiationBankId((Number)value);
            }
        }
        ,
        CreatedByName {
            public Object get(BBLCHeaderVORowImpl obj) {
                return obj.getCreatedByName();
            }

            public void put(BBLCHeaderVORowImpl obj, Object value) {
                obj.setCreatedByName((String)value);
            }
        }
        ,
        CreatedByOriginal {
            public Object get(BBLCHeaderVORowImpl obj) {
                return obj.getCreatedByOriginal();
            }

            public void put(BBLCHeaderVORowImpl obj, Object value) {
                obj.setCreatedByOriginal((Number)value);
            }
        }
        ,
        CreatedByChangeDate {
            public Object get(BBLCHeaderVORowImpl obj) {
                return obj.getCreatedByChangeDate();
            }

            public void put(BBLCHeaderVORowImpl obj, Object value) {
                obj.setCreatedByChangeDate((Date)value);
            }
        }
        ,
        TtFddValue {
            public Object get(BBLCHeaderVORowImpl obj) {
                return obj.getTtFddValue();
            }

            public void put(BBLCHeaderVORowImpl obj, Object value) {
                obj.setTtFddValue((Number)value);
            }
        }
        ,
        ContractNumbers {
            public Object get(BBLCHeaderVORowImpl obj) {
                return obj.getContractNumbers();
            }

            public void put(BBLCHeaderVORowImpl obj, Object value) {
                obj.setContractNumbers((String)value);
            }
        }
        ,
        ShippingGuranteeNumber {
            public Object get(BBLCHeaderVORowImpl obj) {
                return obj.getShippingGuranteeNumber();
            }

            public void put(BBLCHeaderVORowImpl obj, Object value) {
                obj.setShippingGuranteeNumber((String)value);
            }
        }
        ,
        TotalContractLiability {
            public Object get(BBLCHeaderVORowImpl obj) {
                return obj.getTotalContractLiability();
            }

            public void put(BBLCHeaderVORowImpl obj, Object value) {
                obj.setTotalContractLiability((Number)value);
            }
        }
        ,
        TotalCommissionValue {
            public Object get(BBLCHeaderVORowImpl obj) {
                return obj.getTotalCommissionValue();
            }

            public void put(BBLCHeaderVORowImpl obj, Object value) {
                obj.setTotalCommissionValue((Number)value);
            }
        }
        ,
        TotalGoodsValue {
            public Object get(BBLCHeaderVORowImpl obj) {
                return obj.getTotalGoodsValue();
            }

            public void put(BBLCHeaderVORowImpl obj, Object value) {
                obj.setTotalGoodsValue((Number)value);
            }
        }
        ,
        ProposalOpenStatus {
            public Object get(BBLCHeaderVORowImpl obj) {
                return obj.getProposalOpenStatus();
            }

            public void put(BBLCHeaderVORowImpl obj, Object value) {
                obj.setProposalOpenStatus((String)value);
            }
        }
        ,
        TotalBblcValue {
            public Object get(BBLCHeaderVORowImpl obj) {
                return obj.getTotalBblcValue();
            }

            public void put(BBLCHeaderVORowImpl obj, Object value) {
                obj.setTotalBblcValue((Number)value);
            }
        }
        ,
        BblcNo {
            public Object get(BBLCHeaderVORowImpl obj) {
                return obj.getBblcNo();
            }

            public void put(BBLCHeaderVORowImpl obj, Object value) {
                obj.setBblcNo((String)value);
            }
        }
        ,
        BblcContractNo {
            public Object get(BBLCHeaderVORowImpl obj) {
                return obj.getBblcContractNo();
            }

            public void put(BBLCHeaderVORowImpl obj, Object value) {
                obj.setBblcContractNo((String)value);
            }
        }
        ,
        InvoiceNo {
            public Object get(BBLCHeaderVORowImpl obj) {
                return obj.getInvoiceNo();
            }

            public void put(BBLCHeaderVORowImpl obj, Object value) {
                obj.setInvoiceNo((String)value);
            }
        }
        ,
        AcceptanceNumber {
            public Object get(BBLCHeaderVORowImpl obj) {
                return obj.getAcceptanceNumber();
            }

            public void put(BBLCHeaderVORowImpl obj, Object value) {
                obj.setAcceptanceNumber((String)value);
            }
        }
        ,
        BblcPercentOfContract {
            public Object get(BBLCHeaderVORowImpl obj) {
                return obj.getBblcPercentOfContract();
            }

            public void put(BBLCHeaderVORowImpl obj, Object value) {
                obj.setBblcPercentOfContract((Double)value);
            }
        }
        ,
        BBLCLines {
            public Object get(BBLCHeaderVORowImpl obj) {
                return obj.getBBLCLines();
            }

            public void put(BBLCHeaderVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        BBLCCountry {
            public Object get(BBLCHeaderVORowImpl obj) {
                return obj.getBBLCCountry();
            }

            public void put(BBLCHeaderVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        BBLCContract {
            public Object get(BBLCHeaderVORowImpl obj) {
                return obj.getBBLCContract();
            }

            public void put(BBLCHeaderVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        BBLCLines_MaxAmend {
            public Object get(BBLCHeaderVORowImpl obj) {
                return obj.getBBLCLines_MaxAmend();
            }

            public void put(BBLCHeaderVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        AllInvoices {
            public Object get(BBLCHeaderVORowImpl obj) {
                return obj.getAllInvoices();
            }

            public void put(BBLCHeaderVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        BBLCItemPercentage {
            public Object get(BBLCHeaderVORowImpl obj) {
                return obj.getBBLCItemPercentage();
            }

            public void put(BBLCHeaderVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        BankHeadBranches {
            public Object get(BBLCHeaderVORowImpl obj) {
                return obj.getBankHeadBranches();
            }

            public void put(BBLCHeaderVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        BanksVO1 {
            public Object get(BBLCHeaderVORowImpl obj) {
                return obj.getBanksVO1();
            }

            public void put(BBLCHeaderVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        OrgVO1 {
            public Object get(BBLCHeaderVORowImpl obj) {
                return obj.getOrgVO1();
            }

            public void put(BBLCHeaderVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        ProposalOpenStatusLov1 {
            public Object get(BBLCHeaderVORowImpl obj) {
                return obj.getProposalOpenStatusLov1();
            }

            public void put(BBLCHeaderVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(BBLCHeaderVORowImpl object);

        public abstract void put(BBLCHeaderVORowImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int IMPBBLCHEADERID = AttributesEnum.ImpBblcHeaderId.index();
    public static final int PROPOSALNUMBER = AttributesEnum.ProposalNumber.index();
    public static final int PROPOSALDATE = AttributesEnum.ProposalDate.index();
    public static final int IMPORTAGAINSTCONTRACT = AttributesEnum.ImportAgainstContract.index();
    public static final int NEGOTIATIONBANK = AttributesEnum.NegotiationBank.index();
    public static final int CONTRACTVALUE = AttributesEnum.ContractValue.index();
    public static final int LASTSHIPDATE = AttributesEnum.LastShipDate.index();
    public static final int ENTITLEBTBVALUE = AttributesEnum.EntitleBtbValue.index();
    public static final int AVAILABLEBTBVALUE = AttributesEnum.AvailableBtbValue.index();
    public static final int VERSIONNO = AttributesEnum.VersionNo.index();
    public static final int VERSIONDATE = AttributesEnum.VersionDate.index();
    public static final int ORGID = AttributesEnum.OrgId.index();
    public static final int LASTUPDATELOGIN = AttributesEnum.LastUpdateLogin.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int ATTRIBUTE1 = AttributesEnum.Attribute1.index();
    public static final int ATTRIBUTE2 = AttributesEnum.Attribute2.index();
    public static final int ATTRIBUTE3 = AttributesEnum.Attribute3.index();
    public static final int ATTRIBUTE4 = AttributesEnum.Attribute4.index();
    public static final int ATTRIBUTE5 = AttributesEnum.Attribute5.index();
    public static final int ATTRIBUTE6 = AttributesEnum.Attribute6.index();
    public static final int ATTRIBUTE7 = AttributesEnum.Attribute7.index();
    public static final int ATTRIBUTE8 = AttributesEnum.Attribute8.index();
    public static final int ATTRIBUTE9 = AttributesEnum.Attribute9.index();
    public static final int ATTRIBUTE10 = AttributesEnum.Attribute10.index();
    public static final int ATTRIBUTE11 = AttributesEnum.Attribute11.index();
    public static final int ATTRIBUTE12 = AttributesEnum.Attribute12.index();
    public static final int ATTRIBUTE13 = AttributesEnum.Attribute13.index();
    public static final int ATTRIBUTE14 = AttributesEnum.Attribute14.index();
    public static final int ATTRIBUTE15 = AttributesEnum.Attribute15.index();
    public static final int ATTRIBUTE16 = AttributesEnum.Attribute16.index();
    public static final int ATTRIBUTE17 = AttributesEnum.Attribute17.index();
    public static final int ATTRIBUTE18 = AttributesEnum.Attribute18.index();
    public static final int ATTRIBUTE19 = AttributesEnum.Attribute19.index();
    public static final int ATTRIBUTE20 = AttributesEnum.Attribute20.index();
    public static final int ATTRIBUTE21 = AttributesEnum.Attribute21.index();
    public static final int ATTRIBUTE22 = AttributesEnum.Attribute22.index();
    public static final int ATTRIBUTE23 = AttributesEnum.Attribute23.index();
    public static final int ATTRIBUTE24 = AttributesEnum.Attribute24.index();
    public static final int ATTRIBUTE25 = AttributesEnum.Attribute25.index();
    public static final int ATTRIBUTE26 = AttributesEnum.Attribute26.index();
    public static final int ATTRIBUTE27 = AttributesEnum.Attribute27.index();
    public static final int ATTRIBUTE28 = AttributesEnum.Attribute28.index();
    public static final int ATTRIBUTE29 = AttributesEnum.Attribute29.index();
    public static final int ORGNAME = AttributesEnum.OrgName.index();
    public static final int ORGSHORTNAME = AttributesEnum.OrgShortName.index();
    public static final int ATTRIBUTE30 = AttributesEnum.Attribute30.index();
    public static final int BBLCDOCNUMBER = AttributesEnum.BblcDocNumber.index();
    public static final int PAIDAMOUNTFORPROPOSAL = AttributesEnum.PaidAmountForProposal.index();
    public static final int PROPOSALNONEW = AttributesEnum.ProposalNoNew.index();
    public static final int NEGOTIATIONBANKID = AttributesEnum.NegotiationBankId.index();
    public static final int CREATEDBYNAME = AttributesEnum.CreatedByName.index();
    public static final int CREATEDBYORIGINAL = AttributesEnum.CreatedByOriginal.index();
    public static final int CREATEDBYCHANGEDATE = AttributesEnum.CreatedByChangeDate.index();
    public static final int TTFDDVALUE = AttributesEnum.TtFddValue.index();
    public static final int CONTRACTNUMBERS = AttributesEnum.ContractNumbers.index();
    public static final int SHIPPINGGURANTEENUMBER = AttributesEnum.ShippingGuranteeNumber.index();
    public static final int TOTALCONTRACTLIABILITY = AttributesEnum.TotalContractLiability.index();
    public static final int TOTALCOMMISSIONVALUE = AttributesEnum.TotalCommissionValue.index();
    public static final int TOTALGOODSVALUE = AttributesEnum.TotalGoodsValue.index();
    public static final int PROPOSALOPENSTATUS = AttributesEnum.ProposalOpenStatus.index();
    public static final int TOTALBBLCVALUE = AttributesEnum.TotalBblcValue.index();
    public static final int BBLCNO = AttributesEnum.BblcNo.index();
    public static final int BBLCCONTRACTNO = AttributesEnum.BblcContractNo.index();
    public static final int INVOICENO = AttributesEnum.InvoiceNo.index();
    public static final int ACCEPTANCENUMBER = AttributesEnum.AcceptanceNumber.index();
    public static final int BBLCPERCENTOFCONTRACT = AttributesEnum.BblcPercentOfContract.index();
    public static final int BBLCLINES = AttributesEnum.BBLCLines.index();
    public static final int BBLCCOUNTRY = AttributesEnum.BBLCCountry.index();
    public static final int BBLCCONTRACT = AttributesEnum.BBLCContract.index();
    public static final int BBLCLINES_MAXAMEND = AttributesEnum.BBLCLines_MaxAmend.index();
    public static final int ALLINVOICES = AttributesEnum.AllInvoices.index();
    public static final int BBLCITEMPERCENTAGE = AttributesEnum.BBLCItemPercentage.index();
    public static final int BANKHEADBRANCHES = AttributesEnum.BankHeadBranches.index();
    public static final int BANKSVO1 = AttributesEnum.BanksVO1.index();
    public static final int ORGVO1 = AttributesEnum.OrgVO1.index();
    public static final int PROPOSALOPENSTATUSLOV1 = AttributesEnum.ProposalOpenStatusLov1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public BBLCHeaderVORowImpl() {
    }

    /**
     * Gets BBLCHeaderEO entity object.
     * @return the BBLCHeaderEO
     */
    public BBLCHeaderEOImpl getBBLCHeaderEO() {
        return (BBLCHeaderEOImpl)getEntity(0);
    }

    /**
     * Gets the attribute value for IMP_BBLC_HEADER_ID using the alias name ImpBblcHeaderId.
     * @return the IMP_BBLC_HEADER_ID
     */
    public Number getImpBblcHeaderId() {
        return (Number) getAttributeInternal(IMPBBLCHEADERID);
    }

    /**
     * Sets <code>value</code> as attribute value for IMP_BBLC_HEADER_ID using the alias name ImpBblcHeaderId.
     * @param value value to set the IMP_BBLC_HEADER_ID
     */
    public void setImpBblcHeaderId(Number value) {
        setAttributeInternal(IMPBBLCHEADERID, value);
    }

    /**
     * Gets the attribute value for PROPOSAL_NUMBER using the alias name ProposalNumber.
     * @return the PROPOSAL_NUMBER
     */
    public String getProposalNumber() {
        return (String) getAttributeInternal(PROPOSALNUMBER);
    }

    /**
     * Sets <code>value</code> as attribute value for PROPOSAL_NUMBER using the alias name ProposalNumber.
     * @param value value to set the PROPOSAL_NUMBER
     */
    public void setProposalNumber(String value) {
        setAttributeInternal(PROPOSALNUMBER, value);
    }

    /**
     * Gets the attribute value for PROPOSAL_DATE using the alias name ProposalDate.
     * @return the PROPOSAL_DATE
     */
    public Date getProposalDate() {
        return (Date) getAttributeInternal(PROPOSALDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for PROPOSAL_DATE using the alias name ProposalDate.
     * @param value value to set the PROPOSAL_DATE
     */
    public void setProposalDate(Date value) {
        setAttributeInternal(PROPOSALDATE, value);
    }

    /**
     * Gets the attribute value for IMPORT_AGAINST_CONTRACT using the alias name ImportAgainstContract.
     * @return the IMPORT_AGAINST_CONTRACT
     */
    public String getImportAgainstContract() {
        return (String) getAttributeInternal(IMPORTAGAINSTCONTRACT);
    }

    /**
     * Sets <code>value</code> as attribute value for IMPORT_AGAINST_CONTRACT using the alias name ImportAgainstContract.
     * @param value value to set the IMPORT_AGAINST_CONTRACT
     */
    public void setImportAgainstContract(String value) {
        setAttributeInternal(IMPORTAGAINSTCONTRACT, value);
    }

    /**
     * Gets the attribute value for NEGOTIATION_BANK using the alias name NegotiationBank.
     * @return the NEGOTIATION_BANK
     */
    public String getNegotiationBank() {
        return (String) getAttributeInternal(NEGOTIATIONBANK);
    }

    /**
     * Sets <code>value</code> as attribute value for NEGOTIATION_BANK using the alias name NegotiationBank.
     * @param value value to set the NEGOTIATION_BANK
     */
    public void setNegotiationBank(String value) {
        setAttributeInternal(NEGOTIATIONBANK, value);
    }

    /**
     * Gets the attribute value for CONTRACT_VALUE using the alias name ContractValue.
     * @return the CONTRACT_VALUE
     */
    public Number getContractValue() {
        return (Number) getAttributeInternal(CONTRACTVALUE);
    }

    /**
     * Sets <code>value</code> as attribute value for CONTRACT_VALUE using the alias name ContractValue.
     * @param value value to set the CONTRACT_VALUE
     */
    public void setContractValue(Number value) {
        setAttributeInternal(CONTRACTVALUE, value);
    }

    /**
     * Gets the attribute value for LAST_SHIP_DATE using the alias name LastShipDate.
     * @return the LAST_SHIP_DATE
     */
    public Date getLastShipDate() {
        return (Date) getAttributeInternal(LASTSHIPDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_SHIP_DATE using the alias name LastShipDate.
     * @param value value to set the LAST_SHIP_DATE
     */
    public void setLastShipDate(Date value) {
        setAttributeInternal(LASTSHIPDATE, value);
    }

    /**
     * Gets the attribute value for ENTITLE_BTB_VALUE using the alias name EntitleBtbValue.
     * @return the ENTITLE_BTB_VALUE
     */
    public Double getEntitleBtbValue() {
        return (Double) getAttributeInternal(ENTITLEBTBVALUE);
    }

    /**
     * Sets <code>value</code> as attribute value for ENTITLE_BTB_VALUE using the alias name EntitleBtbValue.
     * @param value value to set the ENTITLE_BTB_VALUE
     */
    public void setEntitleBtbValue(Double value) {
        setAttributeInternal(ENTITLEBTBVALUE, value);
    }

    /**
     * Gets the attribute value for AVAILABLE_BTB_VALUE using the alias name AvailableBtbValue.
     * @return the AVAILABLE_BTB_VALUE
     */
    public Double getAvailableBtbValue() {
        return (Double) getAttributeInternal(AVAILABLEBTBVALUE);
    }

    /**
     * Sets <code>value</code> as attribute value for AVAILABLE_BTB_VALUE using the alias name AvailableBtbValue.
     * @param value value to set the AVAILABLE_BTB_VALUE
     */
    public void setAvailableBtbValue(Double value) {
        setAttributeInternal(AVAILABLEBTBVALUE, value);
    }

    /**
     * Gets the attribute value for VERSION_NO using the alias name VersionNo.
     * @return the VERSION_NO
     */
    public Number getVersionNo() {
        return (Number) getAttributeInternal(VERSIONNO);
    }

    /**
     * Sets <code>value</code> as attribute value for VERSION_NO using the alias name VersionNo.
     * @param value value to set the VERSION_NO
     */
    public void setVersionNo(Number value) {
        setAttributeInternal(VERSIONNO, value);
    }

    /**
     * Gets the attribute value for VERSION_DATE using the alias name VersionDate.
     * @return the VERSION_DATE
     */
    public Date getVersionDate() {
        return (Date) getAttributeInternal(VERSIONDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for VERSION_DATE using the alias name VersionDate.
     * @param value value to set the VERSION_DATE
     */
    public void setVersionDate(Date value) {
        setAttributeInternal(VERSIONDATE, value);
    }

    /**
     * Gets the attribute value for ORG_ID using the alias name OrgId.
     * @return the ORG_ID
     */
    public Number getOrgId() {
        return (Number) getAttributeInternal(ORGID);
    }

    /**
     * Sets <code>value</code> as attribute value for ORG_ID using the alias name OrgId.
     * @param value value to set the ORG_ID
     */
    public void setOrgId(Number value) {
        setAttributeInternal(ORGID, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATE_LOGIN using the alias name LastUpdateLogin.
     * @return the LAST_UPDATE_LOGIN
     */
    public Number getLastUpdateLogin() {
        return (Number) getAttributeInternal(LASTUPDATELOGIN);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATE_LOGIN using the alias name LastUpdateLogin.
     * @param value value to set the LAST_UPDATE_LOGIN
     */
    public void setLastUpdateLogin(Number value) {
        setAttributeInternal(LASTUPDATELOGIN, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate.
     * @return the LAST_UPDATE_DATE
     */
    public Date getLastUpdateDate() {
        return (Date) getAttributeInternal(LASTUPDATEDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate.
     * @param value value to set the LAST_UPDATE_DATE
     */
    public void setLastUpdateDate(Date value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @return the LAST_UPDATED_BY
     */
    public Number getLastUpdatedBy() {
        return (Number) getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @param value value to set the LAST_UPDATED_BY
     */
    public void setLastUpdatedBy(Number value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for CREATION_DATE using the alias name CreationDate.
     * @return the CREATION_DATE
     */
    public Date getCreationDate() {
        return (Date) getAttributeInternal(CREATIONDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATION_DATE using the alias name CreationDate.
     * @param value value to set the CREATION_DATE
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**
     * Gets the attribute value for CREATED_BY using the alias name CreatedBy.
     * @return the CREATED_BY
     */
    public Number getCreatedBy() {
        return (Number) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy.
     * @param value value to set the CREATED_BY
     */
    public void setCreatedBy(Number value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE1 using the alias name Attribute1.
     * @return the ATTRIBUTE1
     */
    public Double getAttribute1() {
        return (Double) getAttributeInternal(ATTRIBUTE1);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE1 using the alias name Attribute1.
     * @param value value to set the ATTRIBUTE1
     */
    public void setAttribute1(Double value) {
        setAttributeInternal(ATTRIBUTE1, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE2 using the alias name Attribute2.
     * @return the ATTRIBUTE2
     */
    public Double getAttribute2() {
        return (Double) getAttributeInternal(ATTRIBUTE2);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE2 using the alias name Attribute2.
     * @param value value to set the ATTRIBUTE2
     */
    public void setAttribute2(Double value) {
        setAttributeInternal(ATTRIBUTE2, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE3 using the alias name Attribute3.
     * @return the ATTRIBUTE3
     */
    public Double getAttribute3() {
        return (Double) getAttributeInternal(ATTRIBUTE3);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE3 using the alias name Attribute3.
     * @param value value to set the ATTRIBUTE3
     */
    public void setAttribute3(Double value) {
        setAttributeInternal(ATTRIBUTE3, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE4 using the alias name Attribute4.
     * @return the ATTRIBUTE4
     */
    public Double getAttribute4() {
        return (Double) getAttributeInternal(ATTRIBUTE4);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE4 using the alias name Attribute4.
     * @param value value to set the ATTRIBUTE4
     */
    public void setAttribute4(Double value) {
        setAttributeInternal(ATTRIBUTE4, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE5 using the alias name Attribute5.
     * @return the ATTRIBUTE5
     */
    public Double getAttribute5() {
        return (Double) getAttributeInternal(ATTRIBUTE5);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE5 using the alias name Attribute5.
     * @param value value to set the ATTRIBUTE5
     */
    public void setAttribute5(Double value) {
        setAttributeInternal(ATTRIBUTE5, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE6 using the alias name Attribute6.
     * @return the ATTRIBUTE6
     */
    public Double getAttribute6() {
        return (Double) getAttributeInternal(ATTRIBUTE6);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE6 using the alias name Attribute6.
     * @param value value to set the ATTRIBUTE6
     */
    public void setAttribute6(Double value) {
        setAttributeInternal(ATTRIBUTE6, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE7 using the alias name Attribute7.
     * @return the ATTRIBUTE7
     */
    public String getAttribute7() {
        return (String) getAttributeInternal(ATTRIBUTE7);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE7 using the alias name Attribute7.
     * @param value value to set the ATTRIBUTE7
     */
    public void setAttribute7(String value) {
        setAttributeInternal(ATTRIBUTE7, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE8 using the alias name Attribute8.
     * @return the ATTRIBUTE8
     */
    public String getAttribute8() {
        return (String) getAttributeInternal(ATTRIBUTE8);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE8 using the alias name Attribute8.
     * @param value value to set the ATTRIBUTE8
     */
    public void setAttribute8(String value) {
        setAttributeInternal(ATTRIBUTE8, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE9 using the alias name Attribute9.
     * @return the ATTRIBUTE9
     */
    public String getAttribute9() {
        return (String) getAttributeInternal(ATTRIBUTE9);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE9 using the alias name Attribute9.
     * @param value value to set the ATTRIBUTE9
     */
    public void setAttribute9(String value) {
        setAttributeInternal(ATTRIBUTE9, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE10 using the alias name Attribute10.
     * @return the ATTRIBUTE10
     */
    public String getAttribute10() {
        return (String) getAttributeInternal(ATTRIBUTE10);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE10 using the alias name Attribute10.
     * @param value value to set the ATTRIBUTE10
     */
    public void setAttribute10(String value) {
        setAttributeInternal(ATTRIBUTE10, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE11 using the alias name Attribute11.
     * @return the ATTRIBUTE11
     */
    public String getAttribute11() {
        return (String) getAttributeInternal(ATTRIBUTE11);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE11 using the alias name Attribute11.
     * @param value value to set the ATTRIBUTE11
     */
    public void setAttribute11(String value) {
        setAttributeInternal(ATTRIBUTE11, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE12 using the alias name Attribute12.
     * @return the ATTRIBUTE12
     */
    public String getAttribute12() {
        return (String) getAttributeInternal(ATTRIBUTE12);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE12 using the alias name Attribute12.
     * @param value value to set the ATTRIBUTE12
     */
    public void setAttribute12(String value) {
        setAttributeInternal(ATTRIBUTE12, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE13 using the alias name Attribute13.
     * @return the ATTRIBUTE13
     */
    public String getAttribute13() {
        return (String) getAttributeInternal(ATTRIBUTE13);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE13 using the alias name Attribute13.
     * @param value value to set the ATTRIBUTE13
     */
    public void setAttribute13(String value) {
        setAttributeInternal(ATTRIBUTE13, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE14 using the alias name Attribute14.
     * @return the ATTRIBUTE14
     */
    public String getAttribute14() {
        return (String) getAttributeInternal(ATTRIBUTE14);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE14 using the alias name Attribute14.
     * @param value value to set the ATTRIBUTE14
     */
    public void setAttribute14(String value) {
        setAttributeInternal(ATTRIBUTE14, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE15 using the alias name Attribute15.
     * @return the ATTRIBUTE15
     */
    public String getAttribute15() {
        return (String) getAttributeInternal(ATTRIBUTE15);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE15 using the alias name Attribute15.
     * @param value value to set the ATTRIBUTE15
     */
    public void setAttribute15(String value) {
        setAttributeInternal(ATTRIBUTE15, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE16 using the alias name Attribute16.
     * @return the ATTRIBUTE16
     */
    public String getAttribute16() {
        return (String) getAttributeInternal(ATTRIBUTE16);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE16 using the alias name Attribute16.
     * @param value value to set the ATTRIBUTE16
     */
    public void setAttribute16(String value) {
        setAttributeInternal(ATTRIBUTE16, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE17 using the alias name Attribute17.
     * @return the ATTRIBUTE17
     */
    public String getAttribute17() {
        return (String) getAttributeInternal(ATTRIBUTE17);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE17 using the alias name Attribute17.
     * @param value value to set the ATTRIBUTE17
     */
    public void setAttribute17(String value) {
        setAttributeInternal(ATTRIBUTE17, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE18 using the alias name Attribute18.
     * @return the ATTRIBUTE18
     */
    public String getAttribute18() {
        return (String) getAttributeInternal(ATTRIBUTE18);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE18 using the alias name Attribute18.
     * @param value value to set the ATTRIBUTE18
     */
    public void setAttribute18(String value) {
        setAttributeInternal(ATTRIBUTE18, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE19 using the alias name Attribute19.
     * @return the ATTRIBUTE19
     */
    public String getAttribute19() {
        return (String) getAttributeInternal(ATTRIBUTE19);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE19 using the alias name Attribute19.
     * @param value value to set the ATTRIBUTE19
     */
    public void setAttribute19(String value) {
        setAttributeInternal(ATTRIBUTE19, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE20 using the alias name Attribute20.
     * @return the ATTRIBUTE20
     */
    public String getAttribute20() {
        return (String) getAttributeInternal(ATTRIBUTE20);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE20 using the alias name Attribute20.
     * @param value value to set the ATTRIBUTE20
     */
    public void setAttribute20(String value) {
        setAttributeInternal(ATTRIBUTE20, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE21 using the alias name Attribute21.
     * @return the ATTRIBUTE21
     */
    public String getAttribute21() {
        return (String) getAttributeInternal(ATTRIBUTE21);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE21 using the alias name Attribute21.
     * @param value value to set the ATTRIBUTE21
     */
    public void setAttribute21(String value) {
        setAttributeInternal(ATTRIBUTE21, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE22 using the alias name Attribute22.
     * @return the ATTRIBUTE22
     */
    public String getAttribute22() {
        return (String) getAttributeInternal(ATTRIBUTE22);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE22 using the alias name Attribute22.
     * @param value value to set the ATTRIBUTE22
     */
    public void setAttribute22(String value) {
        setAttributeInternal(ATTRIBUTE22, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE23 using the alias name Attribute23.
     * @return the ATTRIBUTE23
     */
    public String getAttribute23() {
        return (String) getAttributeInternal(ATTRIBUTE23);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE23 using the alias name Attribute23.
     * @param value value to set the ATTRIBUTE23
     */
    public void setAttribute23(String value) {
        setAttributeInternal(ATTRIBUTE23, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE24 using the alias name Attribute24.
     * @return the ATTRIBUTE24
     */
    public String getAttribute24() {
        return (String) getAttributeInternal(ATTRIBUTE24);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE24 using the alias name Attribute24.
     * @param value value to set the ATTRIBUTE24
     */
    public void setAttribute24(String value) {
        setAttributeInternal(ATTRIBUTE24, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE25 using the alias name Attribute25.
     * @return the ATTRIBUTE25
     */
    public String getAttribute25() {
        return (String) getAttributeInternal(ATTRIBUTE25);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE25 using the alias name Attribute25.
     * @param value value to set the ATTRIBUTE25
     */
    public void setAttribute25(String value) {
        setAttributeInternal(ATTRIBUTE25, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE26 using the alias name Attribute26.
     * @return the ATTRIBUTE26
     */
    public String getAttribute26() {
        return (String) getAttributeInternal(ATTRIBUTE26);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE26 using the alias name Attribute26.
     * @param value value to set the ATTRIBUTE26
     */
    public void setAttribute26(String value) {
        setAttributeInternal(ATTRIBUTE26, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE27 using the alias name Attribute27.
     * @return the ATTRIBUTE27
     */
    public String getAttribute27() {
        return (String) getAttributeInternal(ATTRIBUTE27);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE27 using the alias name Attribute27.
     * @param value value to set the ATTRIBUTE27
     */
    public void setAttribute27(String value) {
        setAttributeInternal(ATTRIBUTE27, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE28 using the alias name Attribute28.
     * @return the ATTRIBUTE28
     */
    public String getAttribute28() {
        return (String) getAttributeInternal(ATTRIBUTE28);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE28 using the alias name Attribute28.
     * @param value value to set the ATTRIBUTE28
     */
    public void setAttribute28(String value) {
        setAttributeInternal(ATTRIBUTE28, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE29 using the alias name Attribute29.
     * @return the ATTRIBUTE29
     */
    public String getAttribute29() {
        return (String) getAttributeInternal(ATTRIBUTE29);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE29 using the alias name Attribute29.
     * @param value value to set the ATTRIBUTE29
     */
    public void setAttribute29(String value) {
        setAttributeInternal(ATTRIBUTE29, value);
    }

    /**
     * Gets the attribute value for the calculated attribute OrgName.
     * @return the OrgName
     */
    public String getOrgName() {
        return (String) getAttributeInternal(ORGNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute OrgName.
     * @param value value to set the  OrgName
     */
    public void setOrgName(String value) {
        setAttributeInternal(ORGNAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute OrgShortName.
     * @return the OrgShortName
     */
    public String getOrgShortName() {
        return (String) getAttributeInternal(ORGSHORTNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute OrgShortName.
     * @param value value to set the  OrgShortName
     */
    public void setOrgShortName(String value) {
        setAttributeInternal(ORGSHORTNAME, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE30 using the alias name Attribute30.
     * @return the ATTRIBUTE30
     */
    public String getAttribute30() {
        return (String) getAttributeInternal(ATTRIBUTE30);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE30 using the alias name Attribute30.
     * @param value value to set the ATTRIBUTE30
     */
    public void setAttribute30(String value) {
        setAttributeInternal(ATTRIBUTE30, value);
    }

    /**
     * Gets the attribute value for BBLC_DOC_NUMBER using the alias name BblcDocNumber.
     * @return the BBLC_DOC_NUMBER
     */
    public Number getBblcDocNumber() {
        return (Number) getAttributeInternal(BBLCDOCNUMBER);
    }

    /**
     * Sets <code>value</code> as attribute value for BBLC_DOC_NUMBER using the alias name BblcDocNumber.
     * @param value value to set the BBLC_DOC_NUMBER
     */
    public void setBblcDocNumber(Number value) {
        setAttributeInternal(BBLCDOCNUMBER, value);
    }

    /**
     * Gets the attribute value for PAID_AMOUNT_FOR_PROPOSAL using the alias name PaidAmountForProposal.
     * @return the PAID_AMOUNT_FOR_PROPOSAL
     */
    public Number getPaidAmountForProposal() {
        return (Number) getAttributeInternal(PAIDAMOUNTFORPROPOSAL);
    }

    /**
     * Sets <code>value</code> as attribute value for PAID_AMOUNT_FOR_PROPOSAL using the alias name PaidAmountForProposal.
     * @param value value to set the PAID_AMOUNT_FOR_PROPOSAL
     */
    public void setPaidAmountForProposal(Number value) {
        setAttributeInternal(PAIDAMOUNTFORPROPOSAL, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ProposalNoNew.
     * @return the ProposalNoNew
     */
    public String getProposalNoNew() {
        return (String) getAttributeInternal(PROPOSALNONEW);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ProposalNoNew.
     * @param value value to set the  ProposalNoNew
     */
    public void setProposalNoNew(String value) {
        setAttributeInternal(PROPOSALNONEW, value);
    }

    /**
     * Gets the attribute value for NEGOTIATION_BANK_ID using the alias name NegotiationBankId.
     * @return the NEGOTIATION_BANK_ID
     */
    public Number getNegotiationBankId() {
        return (Number) getAttributeInternal(NEGOTIATIONBANKID);
    }

    /**
     * Sets <code>value</code> as attribute value for NEGOTIATION_BANK_ID using the alias name NegotiationBankId.
     * @param value value to set the NEGOTIATION_BANK_ID
     */
    public void setNegotiationBankId(Number value) {
        setAttributeInternal(NEGOTIATIONBANKID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CreatedByName.
     * @return the CreatedByName
     */
    public String getCreatedByName() {
        return (String) getAttributeInternal(CREATEDBYNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CreatedByName.
     * @param value value to set the  CreatedByName
     */
    public void setCreatedByName(String value) {
        setAttributeInternal(CREATEDBYNAME, value);
    }


    /**
     * Gets the attribute value for the calculated attribute TotalBblcValue.
     * @return the TotalBblcValue
     */
    public Number getTotalBblcValue() {
        return (Number) getAttributeInternal(TOTALBBLCVALUE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TotalBblcValue.
     * @param value value to set the  TotalBblcValue
     */
    public void setTotalBblcValue(Number value) {
        setAttributeInternal(TOTALBBLCVALUE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute BblcNo.
     * @return the BblcNo
     */
    public String getBblcNo() {
        return (String) getAttributeInternal(BBLCNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute BblcNo.
     * @param value value to set the  BblcNo
     */
    public void setBblcNo(String value) {
        setAttributeInternal(BBLCNO, value);
    }

    /**
     * Gets the attribute value for the calculated attribute BblcContractNo.
     * @return the BblcContractNo
     */
    public String getBblcContractNo() {
        return (String) getAttributeInternal(BBLCCONTRACTNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute BblcContractNo.
     * @param value value to set the  BblcContractNo
     */
    public void setBblcContractNo(String value) {
        setAttributeInternal(BBLCCONTRACTNO, value);
    }

    /**
     * Gets the attribute value for the calculated attribute InvoiceNo.
     * @return the InvoiceNo
     */
    public String getInvoiceNo() {
        return (String) getAttributeInternal(INVOICENO);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute InvoiceNo.
     * @param value value to set the  InvoiceNo
     */
    public void setInvoiceNo(String value) {
        setAttributeInternal(INVOICENO, value);
    }

    /**
     * Gets the attribute value for the calculated attribute AcceptanceNumber.
     * @return the AcceptanceNumber
     */
    public String getAcceptanceNumber() {
        return (String) getAttributeInternal(ACCEPTANCENUMBER);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute AcceptanceNumber.
     * @param value value to set the  AcceptanceNumber
     */
    public void setAcceptanceNumber(String value) {
        setAttributeInternal(ACCEPTANCENUMBER, value);
    }


    /**
     * Gets the attribute value for the calculated attribute BblcPercentOfContract.
     * @return the BblcPercentOfContract
     */
    public Double getBblcPercentOfContract() {
        return (Double) getAttributeInternal(BBLCPERCENTOFCONTRACT);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute BblcPercentOfContract.
     * @param value value to set the  BblcPercentOfContract
     */
    public void setBblcPercentOfContract(Double value) {
        setAttributeInternal(BBLCPERCENTOFCONTRACT, value);
    }


    /**
     * Gets the attribute value for TOTAL_CONTRACT_LIABILITY using the alias name TotalContractLiability.
     * @return the TOTAL_CONTRACT_LIABILITY
     */
    public Number getTotalContractLiability() {
        return (Number) getAttributeInternal(TOTALCONTRACTLIABILITY);
    }

    /**
     * Sets <code>value</code> as attribute value for TOTAL_CONTRACT_LIABILITY using the alias name TotalContractLiability.
     * @param value value to set the TOTAL_CONTRACT_LIABILITY
     */
    public void setTotalContractLiability(Number value) {
        setAttributeInternal(TOTALCONTRACTLIABILITY, value);
    }

    /**
     * Gets the attribute value for TOTAL_COMMISSION_VALUE using the alias name TotalCommissionValue.
     * @return the TOTAL_COMMISSION_VALUE
     */
    public Number getTotalCommissionValue() {
        return (Number) getAttributeInternal(TOTALCOMMISSIONVALUE);
    }

    /**
     * Sets <code>value</code> as attribute value for TOTAL_COMMISSION_VALUE using the alias name TotalCommissionValue.
     * @param value value to set the TOTAL_COMMISSION_VALUE
     */
    public void setTotalCommissionValue(Number value) {
        setAttributeInternal(TOTALCOMMISSIONVALUE, value);
    }

    /**
     * Gets the attribute value for TOTAL_GOODS_VALUE using the alias name TotalGoodsValue.
     * @return the TOTAL_GOODS_VALUE
     */
    public Number getTotalGoodsValue() {
        return (Number) getAttributeInternal(TOTALGOODSVALUE);
    }

    /**
     * Sets <code>value</code> as attribute value for TOTAL_GOODS_VALUE using the alias name TotalGoodsValue.
     * @param value value to set the TOTAL_GOODS_VALUE
     */
    public void setTotalGoodsValue(Number value) {
        setAttributeInternal(TOTALGOODSVALUE, value);
    }

    /**
     * Gets the attribute value for PROPOSAL_OPEN_STATUS using the alias name ProposalOpenStatus.
     * @return the PROPOSAL_OPEN_STATUS
     */
    public String getProposalOpenStatus() {
        return (String) getAttributeInternal(PROPOSALOPENSTATUS);
    }

    /**
     * Sets <code>value</code> as attribute value for PROPOSAL_OPEN_STATUS using the alias name ProposalOpenStatus.
     * @param value value to set the PROPOSAL_OPEN_STATUS
     */
    public void setProposalOpenStatus(String value) {
        setAttributeInternal(PROPOSALOPENSTATUS, value);
    }

    /**
     * Gets the attribute value for TT_FDD_VALUE using the alias name TtFddValue.
     * @return the TT_FDD_VALUE
     */
    public Number getTtFddValue() {
        return (Number) getAttributeInternal(TTFDDVALUE);
    }

    /**
     * Sets <code>value</code> as attribute value for TT_FDD_VALUE using the alias name TtFddValue.
     * @param value value to set the TT_FDD_VALUE
     */
    public void setTtFddValue(Number value) {
        setAttributeInternal(TTFDDVALUE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ContractNumbers.
     * @return the ContractNumbers
     */
    public String getContractNumbers() {
        return (String) getAttributeInternal(CONTRACTNUMBERS);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ContractNumbers.
     * @param value value to set the  ContractNumbers
     */
    public void setContractNumbers(String value) {
        setAttributeInternal(CONTRACTNUMBERS, value);
    }

    /**
     * Gets the attribute value for SHIPPING_GURANTEE_NUMBER using the alias name ShippingGuranteeNumber.
     * @return the SHIPPING_GURANTEE_NUMBER
     */
    public String getShippingGuranteeNumber() {
        return (String) getAttributeInternal(SHIPPINGGURANTEENUMBER);
    }

    /**
     * Sets <code>value</code> as attribute value for SHIPPING_GURANTEE_NUMBER using the alias name ShippingGuranteeNumber.
     * @param value value to set the SHIPPING_GURANTEE_NUMBER
     */
    public void setShippingGuranteeNumber(String value) {
        setAttributeInternal(SHIPPINGGURANTEENUMBER, value);
    }

    /**
     * Gets the attribute value for CREATED_BY_CHANGE_DATE using the alias name CreatedByChangeDate.
     * @return the CREATED_BY_CHANGE_DATE
     */
    public Date getCreatedByChangeDate() {
        return (Date) getAttributeInternal(CREATEDBYCHANGEDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_BY_CHANGE_DATE using the alias name CreatedByChangeDate.
     * @param value value to set the CREATED_BY_CHANGE_DATE
     */
    public void setCreatedByChangeDate(Date value) {
        setAttributeInternal(CREATEDBYCHANGEDATE, value);
    }

    /**
     * Gets the attribute value for CREATED_BY_ORIGINAL using the alias name CreatedByOriginal.
     * @return the CREATED_BY_ORIGINAL
     */
    public Number getCreatedByOriginal() {
        return (Number) getAttributeInternal(CREATEDBYORIGINAL);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_BY_ORIGINAL using the alias name CreatedByOriginal.
     * @param value value to set the CREATED_BY_ORIGINAL
     */
    public void setCreatedByOriginal(Number value) {
        setAttributeInternal(CREATEDBYORIGINAL, value);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link BBLCLines.
     */
    public RowIterator getBBLCLines() {
        return (RowIterator)getAttributeInternal(BBLCLINES);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link BBLCCountry.
     */
    public RowIterator getBBLCCountry() {
        return (RowIterator)getAttributeInternal(BBLCCOUNTRY);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link BBLCContract.
     */
    public RowIterator getBBLCContract() {
        return (RowIterator)getAttributeInternal(BBLCCONTRACT);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link BBLCLines_MaxAmend.
     */
    public RowIterator getBBLCLines_MaxAmend() {
        return (RowIterator)getAttributeInternal(BBLCLINES_MAXAMEND);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link AllInvoices.
     */
    public RowIterator getAllInvoices() {
        return (RowIterator)getAttributeInternal(ALLINVOICES);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link BBLCItemPercentage.
     */
    public RowIterator getBBLCItemPercentage() {
        return (RowIterator)getAttributeInternal(BBLCITEMPERCENTAGE);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link BankHeadBranches.
     */
    public RowIterator getBankHeadBranches() {
        return (RowIterator)getAttributeInternal(BANKHEADBRANCHES);
    }

    /**
     * Gets the view accessor <code>RowSet</code> BanksVO1.
     */
    public RowSet getBanksVO1() {
        return (RowSet)getAttributeInternal(BANKSVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> OrgVO1.
     */
    public RowSet getOrgVO1() {
        return (RowSet)getAttributeInternal(ORGVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> ProposalOpenStatusLov1.
     */
    public RowSet getProposalOpenStatusLov1() {
        return (RowSet)getAttributeInternal(PROPOSALOPENSTATUSLOV1);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
