package mnj.ont.model.views;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Mar 19 12:02:18 BDT 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class BBLCAcceptanceVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public BBLCAcceptanceVOImpl() {
    }
}
