package mnj.ont.model.views;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Feb 12 10:01:43 BDT 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class FillGRNImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public FillGRNImpl() {
    }
}
