package mnj.ont.model.views;

import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Dec 13 14:42:15 BDT 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class OrganizationAddressVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        OperatingUnit {
            public Object get(OrganizationAddressVORowImpl obj) {
                return obj.getOperatingUnit();
            }

            public void put(OrganizationAddressVORowImpl obj, Object value) {
                obj.setOperatingUnit((Number)value);
            }
        }
        ,
        OrganizationId {
            public Object get(OrganizationAddressVORowImpl obj) {
                return obj.getOrganizationId();
            }

            public void put(OrganizationAddressVORowImpl obj, Object value) {
                obj.setOrganizationId((Number)value);
            }
        }
        ,
        LocationCode {
            public Object get(OrganizationAddressVORowImpl obj) {
                return obj.getLocationCode();
            }

            public void put(OrganizationAddressVORowImpl obj, Object value) {
                obj.setLocationCode((String)value);
            }
        }
        ,
        FactoryAddress {
            public Object get(OrganizationAddressVORowImpl obj) {
                return obj.getFactoryAddress();
            }

            public void put(OrganizationAddressVORowImpl obj, Object value) {
                obj.setFactoryAddress((String)value);
            }
        }
        ,
        CorporateOfficeAddress {
            public Object get(OrganizationAddressVORowImpl obj) {
                return obj.getCorporateOfficeAddress();
            }

            public void put(OrganizationAddressVORowImpl obj, Object value) {
                obj.setCorporateOfficeAddress((String)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(OrganizationAddressVORowImpl object);

        public abstract void put(OrganizationAddressVORowImpl object,
                                 Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() +
                AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int OPERATINGUNIT = AttributesEnum.OperatingUnit.index();
    public static final int ORGANIZATIONID = AttributesEnum.OrganizationId.index();
    public static final int LOCATIONCODE = AttributesEnum.LocationCode.index();
    public static final int FACTORYADDRESS = AttributesEnum.FactoryAddress.index();
    public static final int CORPORATEOFFICEADDRESS = AttributesEnum.CorporateOfficeAddress.index();

    /**
     * This is the default constructor (do not remove).
     */
    public OrganizationAddressVORowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute OperatingUnit.
     * @return the OperatingUnit
     */
    public Number getOperatingUnit() {
        return (Number)getAttributeInternal(OPERATINGUNIT);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute OperatingUnit.
     * @param value value to set the  OperatingUnit
     */
    public void setOperatingUnit(Number value) {
        setAttributeInternal(OPERATINGUNIT, value);
    }

    /**
     * Gets the attribute value for the calculated attribute OrganizationId.
     * @return the OrganizationId
     */
    public Number getOrganizationId() {
        return (Number)getAttributeInternal(ORGANIZATIONID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute OrganizationId.
     * @param value value to set the  OrganizationId
     */
    public void setOrganizationId(Number value) {
        setAttributeInternal(ORGANIZATIONID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute LocationCode.
     * @return the LocationCode
     */
    public String getLocationCode() {
        return (String)getAttributeInternal(LOCATIONCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute LocationCode.
     * @param value value to set the  LocationCode
     */
    public void setLocationCode(String value) {
        setAttributeInternal(LOCATIONCODE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute FactoryAddress.
     * @return the FactoryAddress
     */
    public String getFactoryAddress() {
        return (String)getAttributeInternal(FACTORYADDRESS);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute FactoryAddress.
     * @param value value to set the  FactoryAddress
     */
    public void setFactoryAddress(String value) {
        setAttributeInternal(FACTORYADDRESS, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CorporateOfficeAddress.
     * @return the CorporateOfficeAddress
     */
    public String getCorporateOfficeAddress() {
        return (String)getAttributeInternal(CORPORATEOFFICEADDRESS);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CorporateOfficeAddress.
     * @param value value to set the  CorporateOfficeAddress
     */
    public void setCorporateOfficeAddress(String value) {
        setAttributeInternal(CORPORATEOFFICEADDRESS, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
