package mnj.ont.model.entities;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Mar 05 17:22:03 BDT 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class BBLC_Acceptance_inv_det_EOImpl extends EntityImpl {
    private static EntityDefImpl mDefinitionObject;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        ImpBblcAcceptInvDetId {
            public Object get(BBLC_Acceptance_inv_det_EOImpl obj) {
                return obj.getImpBblcAcceptInvDetId();
            }

            public void put(BBLC_Acceptance_inv_det_EOImpl obj, Object value) {
                obj.setImpBblcAcceptInvDetId((Number)value);
            }
        }
        ,
        ImpBblcAcceptanceId {
            public Object get(BBLC_Acceptance_inv_det_EOImpl obj) {
                return obj.getImpBblcAcceptanceId();
            }

            public void put(BBLC_Acceptance_inv_det_EOImpl obj, Object value) {
                obj.setImpBblcAcceptanceId((Number)value);
            }
        }
        ,
        InvoiceNo {
            public Object get(BBLC_Acceptance_inv_det_EOImpl obj) {
                return obj.getInvoiceNo();
            }

            public void put(BBLC_Acceptance_inv_det_EOImpl obj, Object value) {
                obj.setInvoiceNo((String)value);
            }
        }
        ,
        ItemsValue {
            public Object get(BBLC_Acceptance_inv_det_EOImpl obj) {
                return obj.getItemsValue();
            }

            public void put(BBLC_Acceptance_inv_det_EOImpl obj, Object value) {
                obj.setItemsValue((Number)value);
            }
        }
        ,
        ImportValue {
            public Object get(BBLC_Acceptance_inv_det_EOImpl obj) {
                return obj.getImportValue();
            }

            public void put(BBLC_Acceptance_inv_det_EOImpl obj, Object value) {
                obj.setImportValue((Number)value);
            }
        }
        ,
        BillReferenceNo {
            public Object get(BBLC_Acceptance_inv_det_EOImpl obj) {
                return obj.getBillReferenceNo();
            }

            public void put(BBLC_Acceptance_inv_det_EOImpl obj, Object value) {
                obj.setBillReferenceNo((String)value);
            }
        }
        ,
        BillValue {
            public Object get(BBLC_Acceptance_inv_det_EOImpl obj) {
                return obj.getBillValue();
            }

            public void put(BBLC_Acceptance_inv_det_EOImpl obj, Object value) {
                obj.setBillValue((String)value);
            }
        }
        ,
        ImpBblcDetailId {
            public Object get(BBLC_Acceptance_inv_det_EOImpl obj) {
                return obj.getImpBblcDetailId();
            }

            public void put(BBLC_Acceptance_inv_det_EOImpl obj, Object value) {
                obj.setImpBblcDetailId((Number)value);
            }
        }
        ,
        Currency {
            public Object get(BBLC_Acceptance_inv_det_EOImpl obj) {
                return obj.getCurrency();
            }

            public void put(BBLC_Acceptance_inv_det_EOImpl obj, Object value) {
                obj.setCurrency((String)value);
            }
        }
        ,
        BBLCAcceptance {
            public Object get(BBLC_Acceptance_inv_det_EOImpl obj) {
                return obj.getBBLCAcceptance();
            }

            public void put(BBLC_Acceptance_inv_det_EOImpl obj, Object value) {
                obj.setBBLCAcceptance((BBLCAcceptanceEOImpl)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(BBLC_Acceptance_inv_det_EOImpl object);

        public abstract void put(BBLC_Acceptance_inv_det_EOImpl object,
                                 Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }

    public static final int IMPBBLCACCEPTINVDETID = AttributesEnum.ImpBblcAcceptInvDetId.index();
    public static final int IMPBBLCACCEPTANCEID = AttributesEnum.ImpBblcAcceptanceId.index();
    public static final int INVOICENO = AttributesEnum.InvoiceNo.index();
    public static final int ITEMSVALUE = AttributesEnum.ItemsValue.index();
    public static final int IMPORTVALUE = AttributesEnum.ImportValue.index();
    public static final int BILLREFERENCENO = AttributesEnum.BillReferenceNo.index();
    public static final int BILLVALUE = AttributesEnum.BillValue.index();
    public static final int IMPBBLCDETAILID = AttributesEnum.ImpBblcDetailId.index();
    public static final int CURRENCY = AttributesEnum.Currency.index();
    public static final int BBLCACCEPTANCE = AttributesEnum.BBLCAcceptance.index();

    /**
     * This is the default constructor (do not remove).
     */
    public BBLC_Acceptance_inv_det_EOImpl() {
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        if (mDefinitionObject == null) {
            mDefinitionObject = EntityDefImpl.findDefObject("mnj.ont.model.entities.BBLC_Acceptance_inv_det_EO");
        }
        return mDefinitionObject;
    }

    /**
     * Gets the attribute value for ImpBblcAcceptInvDetId, using the alias name ImpBblcAcceptInvDetId.
     * @return the ImpBblcAcceptInvDetId
     */
    public Number getImpBblcAcceptInvDetId() {
        return (Number)getAttributeInternal(IMPBBLCACCEPTINVDETID);
    }

    /**
     * Sets <code>value</code> as the attribute value for ImpBblcAcceptInvDetId.
     * @param value value to set the ImpBblcAcceptInvDetId
     */
    public void setImpBblcAcceptInvDetId(Number value) {
        setAttributeInternal(IMPBBLCACCEPTINVDETID, value);
    }

    /**
     * Gets the attribute value for ImpBblcAcceptanceId, using the alias name ImpBblcAcceptanceId.
     * @return the ImpBblcAcceptanceId
     */
    public Number getImpBblcAcceptanceId() {
        return (Number)getAttributeInternal(IMPBBLCACCEPTANCEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for ImpBblcAcceptanceId.
     * @param value value to set the ImpBblcAcceptanceId
     */
    public void setImpBblcAcceptanceId(Number value) {
        setAttributeInternal(IMPBBLCACCEPTANCEID, value);
    }

    /**
     * Gets the attribute value for InvoiceNo, using the alias name InvoiceNo.
     * @return the InvoiceNo
     */
    public String getInvoiceNo() {
        return (String)getAttributeInternal(INVOICENO);
    }

    /**
     * Sets <code>value</code> as the attribute value for InvoiceNo.
     * @param value value to set the InvoiceNo
     */
    public void setInvoiceNo(String value) {
        setAttributeInternal(INVOICENO, value);
    }

    /**
     * Gets the attribute value for ItemsValue, using the alias name ItemsValue.
     * @return the ItemsValue
     */
    public Number getItemsValue() {
        return (Number)getAttributeInternal(ITEMSVALUE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ItemsValue.
     * @param value value to set the ItemsValue
     */
    public void setItemsValue(Number value) {
        setAttributeInternal(ITEMSVALUE, value);
    }

    /**
     * Gets the attribute value for ImportValue, using the alias name ImportValue.
     * @return the ImportValue
     */
    public Number getImportValue() {
        return (Number)getAttributeInternal(IMPORTVALUE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ImportValue.
     * @param value value to set the ImportValue
     */
    public void setImportValue(Number value) {
        setAttributeInternal(IMPORTVALUE, value);
    }

    /**
     * Gets the attribute value for BillReferenceNo, using the alias name BillReferenceNo.
     * @return the BillReferenceNo
     */
    public String getBillReferenceNo() {
        return (String)getAttributeInternal(BILLREFERENCENO);
    }

    /**
     * Sets <code>value</code> as the attribute value for BillReferenceNo.
     * @param value value to set the BillReferenceNo
     */
    public void setBillReferenceNo(String value) {
        setAttributeInternal(BILLREFERENCENO, value);
    }

    /**
     * Gets the attribute value for BillValue, using the alias name BillValue.
     * @return the BillValue
     */
    public String getBillValue() {
        return (String)getAttributeInternal(BILLVALUE);
    }

    /**
     * Sets <code>value</code> as the attribute value for BillValue.
     * @param value value to set the BillValue
     */
    public void setBillValue(String value) {
        setAttributeInternal(BILLVALUE, value);
    }

    /**
     * Gets the attribute value for ImpBblcDetailId, using the alias name ImpBblcDetailId.
     * @return the ImpBblcDetailId
     */
    public Number getImpBblcDetailId() {
        return (Number)getAttributeInternal(IMPBBLCDETAILID);
    }

    /**
     * Sets <code>value</code> as the attribute value for ImpBblcDetailId.
     * @param value value to set the ImpBblcDetailId
     */
    public void setImpBblcDetailId(Number value) {
        setAttributeInternal(IMPBBLCDETAILID, value);
    }

    /**
     * Gets the attribute value for Currency, using the alias name Currency.
     * @return the Currency
     */
    public String getCurrency() {
        return (String)getAttributeInternal(CURRENCY);
    }

    /**
     * Sets <code>value</code> as the attribute value for Currency.
     * @param value value to set the Currency
     */
    public void setCurrency(String value) {
        setAttributeInternal(CURRENCY, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }

    /**
     * @return the associated entity BBLCAcceptanceEOImpl.
     */
    public BBLCAcceptanceEOImpl getBBLCAcceptance() {
        return (BBLCAcceptanceEOImpl)getAttributeInternal(BBLCACCEPTANCE);
    }

    /**
     * Sets <code>value</code> as the associated entity BBLCAcceptanceEOImpl.
     */
    public void setBBLCAcceptance(BBLCAcceptanceEOImpl value) {
        setAttributeInternal(BBLCACCEPTANCE, value);
    }


    /**
     * @param impBblcAcceptInvDetId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Number impBblcAcceptInvDetId) {
        return new Key(new Object[]{impBblcAcceptInvDetId});
    }

    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
    protected void create(AttributeList attributeList) {
        super.create(attributeList);
        oracle.jbo.server.SequenceImpl s =
            new oracle.jbo.server.SequenceImpl("IEDOC_IMP_BBLC_ACCEPT_INV_D_S",
                                               getDBTransaction());
        oracle.jbo.domain.Number sVal = s.getSequenceNumber();
        setImpBblcAcceptInvDetId(sVal);
    }

    /**
     * Add entity remove logic in this method.
     */
    public void remove() {
        super.remove();
    }

    /**
     * Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**
     * Custom DML update/insert/delete logic here.
     * @param operation the operation type
     * @param e the transaction event
     */
    protected void doDML(int operation, TransactionEvent e) {
        super.doDML(operation, e);
    }
}
