package mnj.ont.model.entities;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Nov 27 14:14:33 BDT 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class BBLCContractEOImpl extends EntityImpl {
    private static EntityDefImpl mDefinitionObject;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        ImpBblcContrId {
            public Object get(BBLCContractEOImpl obj) {
                return obj.getImpBblcContrId();
            }

            public void put(BBLCContractEOImpl obj, Object value) {
                obj.setImpBblcContrId((Number)value);
            }
        }
        ,
        ImpBblcHeaderId {
            public Object get(BBLCContractEOImpl obj) {
                return obj.getImpBblcHeaderId();
            }

            public void put(BBLCContractEOImpl obj, Object value) {
                obj.setImpBblcHeaderId((Number)value);
            }
        }
        ,
        BblcContractNo {
            public Object get(BBLCContractEOImpl obj) {
                return obj.getBblcContractNo();
            }

            public void put(BBLCContractEOImpl obj, Object value) {
                obj.setBblcContractNo((String)value);
            }
        }
        ,
        ExportLcNo {
            public Object get(BBLCContractEOImpl obj) {
                return obj.getExportLcNo();
            }

            public void put(BBLCContractEOImpl obj, Object value) {
                obj.setExportLcNo((String)value);
            }
        }
        ,
        ContractDate {
            public Object get(BBLCContractEOImpl obj) {
                return obj.getContractDate();
            }

            public void put(BBLCContractEOImpl obj, Object value) {
                obj.setContractDate((Date)value);
            }
        }
        ,
        ContractValue {
            public Object get(BBLCContractEOImpl obj) {
                return obj.getContractValue();
            }

            public void put(BBLCContractEOImpl obj, Object value) {
                obj.setContractValue((Number)value);
            }
        }
        ,
        ContractQuantity {
            public Object get(BBLCContractEOImpl obj) {
                return obj.getContractQuantity();
            }

            public void put(BBLCContractEOImpl obj, Object value) {
                obj.setContractQuantity((Number)value);
            }
        }
        ,
        LastUpdateLogin {
            public Object get(BBLCContractEOImpl obj) {
                return obj.getLastUpdateLogin();
            }

            public void put(BBLCContractEOImpl obj, Object value) {
                obj.setLastUpdateLogin((Number)value);
            }
        }
        ,
        LastUpdateDate {
            public Object get(BBLCContractEOImpl obj) {
                return obj.getLastUpdateDate();
            }

            public void put(BBLCContractEOImpl obj, Object value) {
                obj.setLastUpdateDate((Date)value);
            }
        }
        ,
        LastUpdatedBy {
            public Object get(BBLCContractEOImpl obj) {
                return obj.getLastUpdatedBy();
            }

            public void put(BBLCContractEOImpl obj, Object value) {
                obj.setLastUpdatedBy((Number)value);
            }
        }
        ,
        CreationDate {
            public Object get(BBLCContractEOImpl obj) {
                return obj.getCreationDate();
            }

            public void put(BBLCContractEOImpl obj, Object value) {
                obj.setCreationDate((Date)value);
            }
        }
        ,
        CreatedBy {
            public Object get(BBLCContractEOImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(BBLCContractEOImpl obj, Object value) {
                obj.setCreatedBy((Number)value);
            }
        }
        ,
        Attribute1 {
            public Object get(BBLCContractEOImpl obj) {
                return obj.getAttribute1();
            }

            public void put(BBLCContractEOImpl obj, Object value) {
                obj.setAttribute1((String)value);
            }
        }
        ,
        Attribute2 {
            public Object get(BBLCContractEOImpl obj) {
                return obj.getAttribute2();
            }

            public void put(BBLCContractEOImpl obj, Object value) {
                obj.setAttribute2((String)value);
            }
        }
        ,
        Attribute3 {
            public Object get(BBLCContractEOImpl obj) {
                return obj.getAttribute3();
            }

            public void put(BBLCContractEOImpl obj, Object value) {
                obj.setAttribute3((String)value);
            }
        }
        ,
        Attribute4 {
            public Object get(BBLCContractEOImpl obj) {
                return obj.getAttribute4();
            }

            public void put(BBLCContractEOImpl obj, Object value) {
                obj.setAttribute4((String)value);
            }
        }
        ,
        Attribute5 {
            public Object get(BBLCContractEOImpl obj) {
                return obj.getAttribute5();
            }

            public void put(BBLCContractEOImpl obj, Object value) {
                obj.setAttribute5((String)value);
            }
        }
        ,
        Attribute6 {
            public Object get(BBLCContractEOImpl obj) {
                return obj.getAttribute6();
            }

            public void put(BBLCContractEOImpl obj, Object value) {
                obj.setAttribute6((String)value);
            }
        }
        ,
        Attribute7 {
            public Object get(BBLCContractEOImpl obj) {
                return obj.getAttribute7();
            }

            public void put(BBLCContractEOImpl obj, Object value) {
                obj.setAttribute7((String)value);
            }
        }
        ,
        Attribute8 {
            public Object get(BBLCContractEOImpl obj) {
                return obj.getAttribute8();
            }

            public void put(BBLCContractEOImpl obj, Object value) {
                obj.setAttribute8((String)value);
            }
        }
        ,
        Attribute9 {
            public Object get(BBLCContractEOImpl obj) {
                return obj.getAttribute9();
            }

            public void put(BBLCContractEOImpl obj, Object value) {
                obj.setAttribute9((String)value);
            }
        }
        ,
        Attribute10 {
            public Object get(BBLCContractEOImpl obj) {
                return obj.getAttribute10();
            }

            public void put(BBLCContractEOImpl obj, Object value) {
                obj.setAttribute10((String)value);
            }
        }
        ,
        GoodsValue {
            public Object get(BBLCContractEOImpl obj) {
                return obj.getGoodsValue();
            }

            public void put(BBLCContractEOImpl obj, Object value) {
                obj.setGoodsValue((Number)value);
            }
        }
        ,
        BuyerId {
            public Object get(BBLCContractEOImpl obj) {
                return obj.getBuyerId();
            }

            public void put(BBLCContractEOImpl obj, Object value) {
                obj.setBuyerId((Number)value);
            }
        }
        ,
        BBLCHeader {
            public Object get(BBLCContractEOImpl obj) {
                return obj.getBBLCHeader();
            }

            public void put(BBLCContractEOImpl obj, Object value) {
                obj.setBBLCHeader((BBLCHeaderEOImpl)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(BBLCContractEOImpl object);

        public abstract void put(BBLCContractEOImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() +
                AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int IMPBBLCCONTRID = AttributesEnum.ImpBblcContrId.index();
    public static final int IMPBBLCHEADERID = AttributesEnum.ImpBblcHeaderId.index();
    public static final int BBLCCONTRACTNO = AttributesEnum.BblcContractNo.index();
    public static final int EXPORTLCNO = AttributesEnum.ExportLcNo.index();
    public static final int CONTRACTDATE = AttributesEnum.ContractDate.index();
    public static final int CONTRACTVALUE = AttributesEnum.ContractValue.index();
    public static final int CONTRACTQUANTITY = AttributesEnum.ContractQuantity.index();
    public static final int LASTUPDATELOGIN = AttributesEnum.LastUpdateLogin.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int ATTRIBUTE1 = AttributesEnum.Attribute1.index();
    public static final int ATTRIBUTE2 = AttributesEnum.Attribute2.index();
    public static final int ATTRIBUTE3 = AttributesEnum.Attribute3.index();
    public static final int ATTRIBUTE4 = AttributesEnum.Attribute4.index();
    public static final int ATTRIBUTE5 = AttributesEnum.Attribute5.index();
    public static final int ATTRIBUTE6 = AttributesEnum.Attribute6.index();
    public static final int ATTRIBUTE7 = AttributesEnum.Attribute7.index();
    public static final int ATTRIBUTE8 = AttributesEnum.Attribute8.index();
    public static final int ATTRIBUTE9 = AttributesEnum.Attribute9.index();
    public static final int ATTRIBUTE10 = AttributesEnum.Attribute10.index();
    public static final int GOODSVALUE = AttributesEnum.GoodsValue.index();
    public static final int BUYERID = AttributesEnum.BuyerId.index();
    public static final int BBLCHEADER = AttributesEnum.BBLCHeader.index();

    /**
     * This is the default constructor (do not remove).
     */
    public BBLCContractEOImpl() {
    }


    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        if (mDefinitionObject == null) {
            mDefinitionObject = EntityDefImpl.findDefObject("mnj.ont.model.entities.BBLCContractEO");
        }
        return mDefinitionObject;
    }

    /**
     * Gets the attribute value for ImpBblcContrId, using the alias name ImpBblcContrId.
     * @return the ImpBblcContrId
     */
    public Number getImpBblcContrId() {
        return (Number)getAttributeInternal(IMPBBLCCONTRID);
    }

    /**
     * Sets <code>value</code> as the attribute value for ImpBblcContrId.
     * @param value value to set the ImpBblcContrId
     */
    public void setImpBblcContrId(Number value) {
        setAttributeInternal(IMPBBLCCONTRID, value);
    }

    /**
     * Gets the attribute value for ImpBblcHeaderId, using the alias name ImpBblcHeaderId.
     * @return the ImpBblcHeaderId
     */
    public Number getImpBblcHeaderId() {
        return (Number)getAttributeInternal(IMPBBLCHEADERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for ImpBblcHeaderId.
     * @param value value to set the ImpBblcHeaderId
     */
    public void setImpBblcHeaderId(Number value) {
        setAttributeInternal(IMPBBLCHEADERID, value);
    }

    /**
     * Gets the attribute value for BblcContractNo, using the alias name BblcContractNo.
     * @return the BblcContractNo
     */
    public String getBblcContractNo() {
        return (String)getAttributeInternal(BBLCCONTRACTNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for BblcContractNo.
     * @param value value to set the BblcContractNo
     */
    public void setBblcContractNo(String value) {
        setAttributeInternal(BBLCCONTRACTNO, value);
    }

    /**
     * Gets the attribute value for ExportLcNo, using the alias name ExportLcNo.
     * @return the ExportLcNo
     */
    public String getExportLcNo() {
        return (String)getAttributeInternal(EXPORTLCNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for ExportLcNo.
     * @param value value to set the ExportLcNo
     */
    public void setExportLcNo(String value) {
        setAttributeInternal(EXPORTLCNO, value);
    }

    /**
     * Gets the attribute value for ContractDate, using the alias name ContractDate.
     * @return the ContractDate
     */
    public Date getContractDate() {
        return (Date)getAttributeInternal(CONTRACTDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ContractDate.
     * @param value value to set the ContractDate
     */
    public void setContractDate(Date value) {
        setAttributeInternal(CONTRACTDATE, value);
    }

    /**
     * Gets the attribute value for ContractValue, using the alias name ContractValue.
     * @return the ContractValue
     */
    public Number getContractValue() {
        return (Number)getAttributeInternal(CONTRACTVALUE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ContractValue.
     * @param value value to set the ContractValue
     */
    public void setContractValue(Number value) {
        setAttributeInternal(CONTRACTVALUE, value);
    }

    /**
     * Gets the attribute value for ContractQuantity, using the alias name ContractQuantity.
     * @return the ContractQuantity
     */
    public Number getContractQuantity() {
        return (Number)getAttributeInternal(CONTRACTQUANTITY);
    }

    /**
     * Sets <code>value</code> as the attribute value for ContractQuantity.
     * @param value value to set the ContractQuantity
     */
    public void setContractQuantity(Number value) {
        setAttributeInternal(CONTRACTQUANTITY, value);
    }

    /**
     * Gets the attribute value for LastUpdateLogin, using the alias name LastUpdateLogin.
     * @return the LastUpdateLogin
     */
    public Number getLastUpdateLogin() {
        return (Number)getAttributeInternal(LASTUPDATELOGIN);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdateLogin.
     * @param value value to set the LastUpdateLogin
     */
    public void setLastUpdateLogin(Number value) {
        setAttributeInternal(LASTUPDATELOGIN, value);
    }

    /**
     * Gets the attribute value for LastUpdateDate, using the alias name LastUpdateDate.
     * @return the LastUpdateDate
     */
    public Date getLastUpdateDate() {
        return (Date)getAttributeInternal(LASTUPDATEDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdateDate.
     * @param value value to set the LastUpdateDate
     */
    public void setLastUpdateDate(Date value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**
     * Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy.
     * @return the LastUpdatedBy
     */
    public Number getLastUpdatedBy() {
        return (Number)getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdatedBy.
     * @param value value to set the LastUpdatedBy
     */
    public void setLastUpdatedBy(Number value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for CreationDate, using the alias name CreationDate.
     * @return the CreationDate
     */
    public Date getCreationDate() {
        return (Date)getAttributeInternal(CREATIONDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreationDate.
     * @param value value to set the CreationDate
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the CreatedBy
     */
    public Number getCreatedBy() {
        return (Number)getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedBy.
     * @param value value to set the CreatedBy
     */
    public void setCreatedBy(Number value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for Attribute1, using the alias name Attribute1.
     * @return the Attribute1
     */
    public String getAttribute1() {
        return (String)getAttributeInternal(ATTRIBUTE1);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute1.
     * @param value value to set the Attribute1
     */
    public void setAttribute1(String value) {
        setAttributeInternal(ATTRIBUTE1, value);
    }

    /**
     * Gets the attribute value for Attribute2, using the alias name Attribute2.
     * @return the Attribute2
     */
    public String getAttribute2() {
        return (String)getAttributeInternal(ATTRIBUTE2);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute2.
     * @param value value to set the Attribute2
     */
    public void setAttribute2(String value) {
        setAttributeInternal(ATTRIBUTE2, value);
    }

    /**
     * Gets the attribute value for Attribute3, using the alias name Attribute3.
     * @return the Attribute3
     */
    public String getAttribute3() {
        return (String)getAttributeInternal(ATTRIBUTE3);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute3.
     * @param value value to set the Attribute3
     */
    public void setAttribute3(String value) {
        setAttributeInternal(ATTRIBUTE3, value);
    }

    /**
     * Gets the attribute value for Attribute4, using the alias name Attribute4.
     * @return the Attribute4
     */
    public String getAttribute4() {
        return (String)getAttributeInternal(ATTRIBUTE4);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute4.
     * @param value value to set the Attribute4
     */
    public void setAttribute4(String value) {
        setAttributeInternal(ATTRIBUTE4, value);
    }

    /**
     * Gets the attribute value for Attribute5, using the alias name Attribute5.
     * @return the Attribute5
     */
    public String getAttribute5() {
        return (String)getAttributeInternal(ATTRIBUTE5);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute5.
     * @param value value to set the Attribute5
     */
    public void setAttribute5(String value) {
        setAttributeInternal(ATTRIBUTE5, value);
    }

    /**
     * Gets the attribute value for Attribute6, using the alias name Attribute6.
     * @return the Attribute6
     */
    public String getAttribute6() {
        return (String)getAttributeInternal(ATTRIBUTE6);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute6.
     * @param value value to set the Attribute6
     */
    public void setAttribute6(String value) {
        setAttributeInternal(ATTRIBUTE6, value);
    }

    /**
     * Gets the attribute value for Attribute7, using the alias name Attribute7.
     * @return the Attribute7
     */
    public String getAttribute7() {
        return (String)getAttributeInternal(ATTRIBUTE7);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute7.
     * @param value value to set the Attribute7
     */
    public void setAttribute7(String value) {
        setAttributeInternal(ATTRIBUTE7, value);
    }

    /**
     * Gets the attribute value for Attribute8, using the alias name Attribute8.
     * @return the Attribute8
     */
    public String getAttribute8() {
        return (String)getAttributeInternal(ATTRIBUTE8);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute8.
     * @param value value to set the Attribute8
     */
    public void setAttribute8(String value) {
        setAttributeInternal(ATTRIBUTE8, value);
    }

    /**
     * Gets the attribute value for Attribute9, using the alias name Attribute9.
     * @return the Attribute9
     */
    public String getAttribute9() {
        return (String)getAttributeInternal(ATTRIBUTE9);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute9.
     * @param value value to set the Attribute9
     */
    public void setAttribute9(String value) {
        setAttributeInternal(ATTRIBUTE9, value);
    }

    /**
     * Gets the attribute value for Attribute10, using the alias name Attribute10.
     * @return the Attribute10
     */
    public String getAttribute10() {
        return (String)getAttributeInternal(ATTRIBUTE10);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute10.
     * @param value value to set the Attribute10
     */
    public void setAttribute10(String value) {
        setAttributeInternal(ATTRIBUTE10, value);
    }

    /**
     * Gets the attribute value for GoodsValue, using the alias name GoodsValue.
     * @return the GoodsValue
     */
    public Number getGoodsValue() {
        return (Number)getAttributeInternal(GOODSVALUE);
    }

    /**
     * Sets <code>value</code> as the attribute value for GoodsValue.
     * @param value value to set the GoodsValue
     */
    public void setGoodsValue(Number value) {
        setAttributeInternal(GOODSVALUE, value);
    }

    /**
     * Gets the attribute value for BuyerId, using the alias name BuyerId.
     * @return the BuyerId
     */
    public Number getBuyerId() {
        return (Number)getAttributeInternal(BUYERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for BuyerId.
     * @param value value to set the BuyerId
     */
    public void setBuyerId(Number value) {
        setAttributeInternal(BUYERID, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }

    /**
     * @return the associated entity BBLCHeaderEOImpl.
     */
    public BBLCHeaderEOImpl getBBLCHeader() {
        return (BBLCHeaderEOImpl)getAttributeInternal(BBLCHEADER);
    }

    /**
     * Sets <code>value</code> as the associated entity BBLCHeaderEOImpl.
     */
    public void setBBLCHeader(BBLCHeaderEOImpl value) {
        setAttributeInternal(BBLCHEADER, value);
    }


    /**
     * @param impBblcContrId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Number impBblcContrId) {
        return new Key(new Object[]{impBblcContrId});
    }

    protected void create(AttributeList attributeList) {
        super.create(attributeList);
        oracle.jbo.server.SequenceImpl s =
            new oracle.jbo.server.SequenceImpl("IEDOC_IMP_BBLC_CONTRACTS_S",
                                               getDBTransaction());
        oracle.jbo.domain.Number sVal = s.getSequenceNumber();
        setImpBblcContrId(sVal);
    }


}
