package mnj.ont.model.entities;

import java.sql.CallableStatement;
import java.sql.SQLException;

import java.util.Map;

import oracle.adf.share.ADFContext;

import oracle.jbo.AttributeList;
import oracle.jbo.JboException;
import oracle.jbo.Key;
import oracle.jbo.RowIterator;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.TransactionEvent;

import oracle.jdbc.OracleTypes;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Nov 04 17:43:01 BDT 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class BBLCLinesEOImpl extends EntityImpl {
    private static EntityDefImpl mDefinitionObject;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        ImpBblcLineId {
            public Object get(BBLCLinesEOImpl obj) {
                return obj.getImpBblcLineId();
            }

            public void put(BBLCLinesEOImpl obj, Object value) {
                obj.setImpBblcLineId((Number)value);
            }
        }
        ,
        ImpBblcHeaderId {
            public Object get(BBLCLinesEOImpl obj) {
                return obj.getImpBblcHeaderId();
            }

            public void put(BBLCLinesEOImpl obj, Object value) {
                obj.setImpBblcHeaderId((Number)value);
            }
        }
        ,
        BblcType {
            public Object get(BBLCLinesEOImpl obj) {
                return obj.getBblcType();
            }

            public void put(BBLCLinesEOImpl obj, Object value) {
                obj.setBblcType((String)value);
            }
        }
        ,
        BblcNo {
            public Object get(BBLCLinesEOImpl obj) {
                return obj.getBblcNo();
            }

            public void put(BBLCLinesEOImpl obj, Object value) {
                obj.setBblcNo((String)value);
            }
        }
        ,
        LcIssueDate {
            public Object get(BBLCLinesEOImpl obj) {
                return obj.getLcIssueDate();
            }

            public void put(BBLCLinesEOImpl obj, Object value) {
                obj.setLcIssueDate((Date)value);
            }
        }
        ,
        LastShipmentDate {
            public Object get(BBLCLinesEOImpl obj) {
                return obj.getLastShipmentDate();
            }

            public void put(BBLCLinesEOImpl obj, Object value) {
                obj.setLastShipmentDate((Date)value);
            }
        }
        ,
        NegotiationDay {
            public Object get(BBLCLinesEOImpl obj) {
                return obj.getNegotiationDay();
            }

            public void put(BBLCLinesEOImpl obj, Object value) {
                obj.setNegotiationDay((String)value);
            }
        }
        ,
        ExpiryDate {
            public Object get(BBLCLinesEOImpl obj) {
                return obj.getExpiryDate();
            }

            public void put(BBLCLinesEOImpl obj, Object value) {
                obj.setExpiryDate((Date)value);
            }
        }
        ,
        IncoTerm {
            public Object get(BBLCLinesEOImpl obj) {
                return obj.getIncoTerm();
            }

            public void put(BBLCLinesEOImpl obj, Object value) {
                obj.setIncoTerm((String)value);
            }
        }
        ,
        UsancePeriod {
            public Object get(BBLCLinesEOImpl obj) {
                return obj.getUsancePeriod();
            }

            public void put(BBLCLinesEOImpl obj, Object value) {
                obj.setUsancePeriod((String)value);
            }
        }
        ,
        ShipmentMode {
            public Object get(BBLCLinesEOImpl obj) {
                return obj.getShipmentMode();
            }

            public void put(BBLCLinesEOImpl obj, Object value) {
                obj.setShipmentMode((String)value);
            }
        }
        ,
        BeneficiaryName {
            public Object get(BBLCLinesEOImpl obj) {
                return obj.getBeneficiaryName();
            }

            public void put(BBLCLinesEOImpl obj, Object value) {
                obj.setBeneficiaryName((String)value);
            }
        }
        ,
        PiNo {
            public Object get(BBLCLinesEOImpl obj) {
                return obj.getPiNo();
            }

            public void put(BBLCLinesEOImpl obj, Object value) {
                obj.setPiNo((String)value);
            }
        }
        ,
        TotalBblcValue {
            public Object get(BBLCLinesEOImpl obj) {
                return obj.getTotalBblcValue();
            }

            public void put(BBLCLinesEOImpl obj, Object value) {
                obj.setTotalBblcValue((Number)value);
            }
        }
        ,
        Item {
            public Object get(BBLCLinesEOImpl obj) {
                return obj.getItem();
            }

            public void put(BBLCLinesEOImpl obj, Object value) {
                obj.setItem((String)value);
            }
        }
        ,
        LcafNo {
            public Object get(BBLCLinesEOImpl obj) {
                return obj.getLcafNo();
            }

            public void put(BBLCLinesEOImpl obj, Object value) {
                obj.setLcafNo((String)value);
            }
        }
        ,
        CountryOfOrigion {
            public Object get(BBLCLinesEOImpl obj) {
                return obj.getCountryOfOrigion();
            }

            public void put(BBLCLinesEOImpl obj, Object value) {
                obj.setCountryOfOrigion((String)value);
            }
        }
        ,
        Confirmation {
            public Object get(BBLCLinesEOImpl obj) {
                return obj.getConfirmation();
            }

            public void put(BBLCLinesEOImpl obj, Object value) {
                obj.setConfirmation((String)value);
            }
        }
        ,
        ConfiramtionCharges {
            public Object get(BBLCLinesEOImpl obj) {
                return obj.getConfiramtionCharges();
            }

            public void put(BBLCLinesEOImpl obj, Object value) {
                obj.setConfiramtionCharges((Number)value);
            }
        }
        ,
        FreightCharge {
            public Object get(BBLCLinesEOImpl obj) {
                return obj.getFreightCharge();
            }

            public void put(BBLCLinesEOImpl obj, Object value) {
                obj.setFreightCharge((Number)value);
            }
        }
        ,
        OtherCharge {
            public Object get(BBLCLinesEOImpl obj) {
                return obj.getOtherCharge();
            }

            public void put(BBLCLinesEOImpl obj, Object value) {
                obj.setOtherCharge((Number)value);
            }
        }
        ,
        Commission {
            public Object get(BBLCLinesEOImpl obj) {
                return obj.getCommission();
            }

            public void put(BBLCLinesEOImpl obj, Object value) {
                obj.setCommission((String)value);
            }
        }
        ,
        InsuranceCompanyName {
            public Object get(BBLCLinesEOImpl obj) {
                return obj.getInsuranceCompanyName();
            }

            public void put(BBLCLinesEOImpl obj, Object value) {
                obj.setInsuranceCompanyName((String)value);
            }
        }
        ,
        InsurancePolicyNo {
            public Object get(BBLCLinesEOImpl obj) {
                return obj.getInsurancePolicyNo();
            }

            public void put(BBLCLinesEOImpl obj, Object value) {
                obj.setInsurancePolicyNo((String)value);
            }
        }
        ,
        UdAmendmentNo {
            public Object get(BBLCLinesEOImpl obj) {
                return obj.getUdAmendmentNo();
            }

            public void put(BBLCLinesEOImpl obj, Object value) {
                obj.setUdAmendmentNo((String)value);
            }
        }
        ,
        LcStatus {
            public Object get(BBLCLinesEOImpl obj) {
                return obj.getLcStatus();
            }

            public void put(BBLCLinesEOImpl obj, Object value) {
                obj.setLcStatus((String)value);
            }
        }
        ,
        LastUpdateLogin {
            public Object get(BBLCLinesEOImpl obj) {
                return obj.getLastUpdateLogin();
            }

            public void put(BBLCLinesEOImpl obj, Object value) {
                obj.setLastUpdateLogin((Number)value);
            }
        }
        ,
        LastUpdateDate {
            public Object get(BBLCLinesEOImpl obj) {
                return obj.getLastUpdateDate();
            }

            public void put(BBLCLinesEOImpl obj, Object value) {
                obj.setLastUpdateDate((Date)value);
            }
        }
        ,
        LastUpdatedBy {
            public Object get(BBLCLinesEOImpl obj) {
                return obj.getLastUpdatedBy();
            }

            public void put(BBLCLinesEOImpl obj, Object value) {
                obj.setLastUpdatedBy((Number)value);
            }
        }
        ,
        CreationDate {
            public Object get(BBLCLinesEOImpl obj) {
                return obj.getCreationDate();
            }

            public void put(BBLCLinesEOImpl obj, Object value) {
                obj.setCreationDate((Date)value);
            }
        }
        ,
        CreatedBy {
            public Object get(BBLCLinesEOImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(BBLCLinesEOImpl obj, Object value) {
                obj.setCreatedBy((Number)value);
            }
        }
        ,
        Attribute1 {
            public Object get(BBLCLinesEOImpl obj) {
                return obj.getAttribute1();
            }

            public void put(BBLCLinesEOImpl obj, Object value) {
                obj.setAttribute1((String)value);
            }
        }
        ,
        Attribute2 {
            public Object get(BBLCLinesEOImpl obj) {
                return obj.getAttribute2();
            }

            public void put(BBLCLinesEOImpl obj, Object value) {
                obj.setAttribute2((String)value);
            }
        }
        ,
        Attribute3 {
            public Object get(BBLCLinesEOImpl obj) {
                return obj.getAttribute3();
            }

            public void put(BBLCLinesEOImpl obj, Object value) {
                obj.setAttribute3((String)value);
            }
        }
        ,
        Attribute4 {
            public Object get(BBLCLinesEOImpl obj) {
                return obj.getAttribute4();
            }

            public void put(BBLCLinesEOImpl obj, Object value) {
                obj.setAttribute4((String)value);
            }
        }
        ,
        Attribute5 {
            public Object get(BBLCLinesEOImpl obj) {
                return obj.getAttribute5();
            }

            public void put(BBLCLinesEOImpl obj, Object value) {
                obj.setAttribute5((String)value);
            }
        }
        ,
        Attribute6 {
            public Object get(BBLCLinesEOImpl obj) {
                return obj.getAttribute6();
            }

            public void put(BBLCLinesEOImpl obj, Object value) {
                obj.setAttribute6((String)value);
            }
        }
        ,
        Attribute7 {
            public Object get(BBLCLinesEOImpl obj) {
                return obj.getAttribute7();
            }

            public void put(BBLCLinesEOImpl obj, Object value) {
                obj.setAttribute7((String)value);
            }
        }
        ,
        Attribute8 {
            public Object get(BBLCLinesEOImpl obj) {
                return obj.getAttribute8();
            }

            public void put(BBLCLinesEOImpl obj, Object value) {
                obj.setAttribute8((String)value);
            }
        }
        ,
        Attribute9 {
            public Object get(BBLCLinesEOImpl obj) {
                return obj.getAttribute9();
            }

            public void put(BBLCLinesEOImpl obj, Object value) {
                obj.setAttribute9((String)value);
            }
        }
        ,
        Attribute10 {
            public Object get(BBLCLinesEOImpl obj) {
                return obj.getAttribute10();
            }

            public void put(BBLCLinesEOImpl obj, Object value) {
                obj.setAttribute10((String)value);
            }
        }
        ,
        Attribute11 {
            public Object get(BBLCLinesEOImpl obj) {
                return obj.getAttribute11();
            }

            public void put(BBLCLinesEOImpl obj, Object value) {
                obj.setAttribute11((String)value);
            }
        }
        ,
        Attribute12 {
            public Object get(BBLCLinesEOImpl obj) {
                return obj.getAttribute12();
            }

            public void put(BBLCLinesEOImpl obj, Object value) {
                obj.setAttribute12((String)value);
            }
        }
        ,
        Attribute13 {
            public Object get(BBLCLinesEOImpl obj) {
                return obj.getAttribute13();
            }

            public void put(BBLCLinesEOImpl obj, Object value) {
                obj.setAttribute13((String)value);
            }
        }
        ,
        Attribute14 {
            public Object get(BBLCLinesEOImpl obj) {
                return obj.getAttribute14();
            }

            public void put(BBLCLinesEOImpl obj, Object value) {
                obj.setAttribute14((String)value);
            }
        }
        ,
        Attribute15 {
            public Object get(BBLCLinesEOImpl obj) {
                return obj.getAttribute15();
            }

            public void put(BBLCLinesEOImpl obj, Object value) {
                obj.setAttribute15((String)value);
            }
        }
        ,
        Attribute16 {
            public Object get(BBLCLinesEOImpl obj) {
                return obj.getAttribute16();
            }

            public void put(BBLCLinesEOImpl obj, Object value) {
                obj.setAttribute16((String)value);
            }
        }
        ,
        Attribute17 {
            public Object get(BBLCLinesEOImpl obj) {
                return obj.getAttribute17();
            }

            public void put(BBLCLinesEOImpl obj, Object value) {
                obj.setAttribute17((String)value);
            }
        }
        ,
        Attribute18 {
            public Object get(BBLCLinesEOImpl obj) {
                return obj.getAttribute18();
            }

            public void put(BBLCLinesEOImpl obj, Object value) {
                obj.setAttribute18((String)value);
            }
        }
        ,
        Attribute19 {
            public Object get(BBLCLinesEOImpl obj) {
                return obj.getAttribute19();
            }

            public void put(BBLCLinesEOImpl obj, Object value) {
                obj.setAttribute19((String)value);
            }
        }
        ,
        Attribute20 {
            public Object get(BBLCLinesEOImpl obj) {
                return obj.getAttribute20();
            }

            public void put(BBLCLinesEOImpl obj, Object value) {
                obj.setAttribute20((String)value);
            }
        }
        ,
        Attribute21 {
            public Object get(BBLCLinesEOImpl obj) {
                return obj.getAttribute21();
            }

            public void put(BBLCLinesEOImpl obj, Object value) {
                obj.setAttribute21((String)value);
            }
        }
        ,
        Attribute22 {
            public Object get(BBLCLinesEOImpl obj) {
                return obj.getAttribute22();
            }

            public void put(BBLCLinesEOImpl obj, Object value) {
                obj.setAttribute22((String)value);
            }
        }
        ,
        Attribute23 {
            public Object get(BBLCLinesEOImpl obj) {
                return obj.getAttribute23();
            }

            public void put(BBLCLinesEOImpl obj, Object value) {
                obj.setAttribute23((String)value);
            }
        }
        ,
        Attribute24 {
            public Object get(BBLCLinesEOImpl obj) {
                return obj.getAttribute24();
            }

            public void put(BBLCLinesEOImpl obj, Object value) {
                obj.setAttribute24((String)value);
            }
        }
        ,
        Attribute25 {
            public Object get(BBLCLinesEOImpl obj) {
                return obj.getAttribute25();
            }

            public void put(BBLCLinesEOImpl obj, Object value) {
                obj.setAttribute25((String)value);
            }
        }
        ,
        Attribute26 {
            public Object get(BBLCLinesEOImpl obj) {
                return obj.getAttribute26();
            }

            public void put(BBLCLinesEOImpl obj, Object value) {
                obj.setAttribute26((String)value);
            }
        }
        ,
        Attribute27 {
            public Object get(BBLCLinesEOImpl obj) {
                return obj.getAttribute27();
            }

            public void put(BBLCLinesEOImpl obj, Object value) {
                obj.setAttribute27((String)value);
            }
        }
        ,
        Attribute28 {
            public Object get(BBLCLinesEOImpl obj) {
                return obj.getAttribute28();
            }

            public void put(BBLCLinesEOImpl obj, Object value) {
                obj.setAttribute28((String)value);
            }
        }
        ,
        Attribute29 {
            public Object get(BBLCLinesEOImpl obj) {
                return obj.getAttribute29();
            }

            public void put(BBLCLinesEOImpl obj, Object value) {
                obj.setAttribute29((String)value);
            }
        }
        ,
        Attribute30 {
            public Object get(BBLCLinesEOImpl obj) {
                return obj.getAttribute30();
            }

            public void put(BBLCLinesEOImpl obj, Object value) {
                obj.setAttribute30((String)value);
            }
        }
        ,
        CommunicationType {
            public Object get(BBLCLinesEOImpl obj) {
                return obj.getCommunicationType();
            }

            public void put(BBLCLinesEOImpl obj, Object value) {
                obj.setCommunicationType((String)value);
            }
        }
        ,
        UpassDays {
            public Object get(BBLCLinesEOImpl obj) {
                return obj.getUpassDays();
            }

            public void put(BBLCLinesEOImpl obj, Object value) {
                obj.setUpassDays((Number)value);
            }
        }
        ,
        InsuranceCoverNoteDate {
            public Object get(BBLCLinesEOImpl obj) {
                return obj.getInsuranceCoverNoteDate();
            }

            public void put(BBLCLinesEOImpl obj, Object value) {
                obj.setInsuranceCoverNoteDate((Date)value);
            }
        }
        ,
        Currency {
            public Object get(BBLCLinesEOImpl obj) {
                return obj.getCurrency();
            }

            public void put(BBLCLinesEOImpl obj, Object value) {
                obj.setCurrency((String)value);
            }
        }
        ,
        ConversionRate {
            public Object get(BBLCLinesEOImpl obj) {
                return obj.getConversionRate();
            }

            public void put(BBLCLinesEOImpl obj, Object value) {
                obj.setConversionRate((Number)value);
            }
        }
        ,
        ConvertedAmount {
            public Object get(BBLCLinesEOImpl obj) {
                return obj.getConvertedAmount();
            }

            public void put(BBLCLinesEOImpl obj, Object value) {
                obj.setConvertedAmount((Number)value);
            }
        }
        ,
        AmendmentDate {
            public Object get(BBLCLinesEOImpl obj) {
                return obj.getAmendmentDate();
            }

            public void put(BBLCLinesEOImpl obj, Object value) {
                obj.setAmendmentDate((Date)value);
            }
        }
        ,
        AmendedValue {
            public Object get(BBLCLinesEOImpl obj) {
                return obj.getAmendedValue();
            }

            public void put(BBLCLinesEOImpl obj, Object value) {
                obj.setAmendedValue((Number)value);
            }
        }
        ,
        PaidAmountForBblc {
            public Object get(BBLCLinesEOImpl obj) {
                return obj.getPaidAmountForBblc();
            }

            public void put(BBLCLinesEOImpl obj, Object value) {
                obj.setPaidAmountForBblc((Number)value);
            }
        }
        ,
        BeneficiaryId {
            public Object get(BBLCLinesEOImpl obj) {
                return obj.getBeneficiaryId();
            }

            public void put(BBLCLinesEOImpl obj, Object value) {
                obj.setBeneficiaryId((Number)value);
            }
        }
        ,
        BBLCHeader {
            public Object get(BBLCLinesEOImpl obj) {
                return obj.getBBLCHeader();
            }

            public void put(BBLCLinesEOImpl obj, Object value) {
                obj.setBBLCHeader((BBLCHeaderEOImpl)value);
            }
        }
        ,
        BBLCDetails1 {
            public Object get(BBLCLinesEOImpl obj) {
                return obj.getBBLCDetails1();
            }

            public void put(BBLCLinesEOImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        BBLCPiDetails {
            public Object get(BBLCLinesEOImpl obj) {
                return obj.getBBLCPiDetails();
            }

            public void put(BBLCLinesEOImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        BBLCAcceptance {
            public Object get(BBLCLinesEOImpl obj) {
                return obj.getBBLCAcceptance();
            }

            public void put(BBLCLinesEOImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(BBLCLinesEOImpl object);

        public abstract void put(BBLCLinesEOImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() +
                AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int IMPBBLCLINEID = AttributesEnum.ImpBblcLineId.index();
    public static final int IMPBBLCHEADERID = AttributesEnum.ImpBblcHeaderId.index();
    public static final int BBLCTYPE = AttributesEnum.BblcType.index();
    public static final int BBLCNO = AttributesEnum.BblcNo.index();
    public static final int LCISSUEDATE = AttributesEnum.LcIssueDate.index();
    public static final int LASTSHIPMENTDATE = AttributesEnum.LastShipmentDate.index();
    public static final int NEGOTIATIONDAY = AttributesEnum.NegotiationDay.index();
    public static final int EXPIRYDATE = AttributesEnum.ExpiryDate.index();
    public static final int INCOTERM = AttributesEnum.IncoTerm.index();
    public static final int USANCEPERIOD = AttributesEnum.UsancePeriod.index();
    public static final int SHIPMENTMODE = AttributesEnum.ShipmentMode.index();
    public static final int BENEFICIARYNAME = AttributesEnum.BeneficiaryName.index();
    public static final int PINO = AttributesEnum.PiNo.index();
    public static final int TOTALBBLCVALUE = AttributesEnum.TotalBblcValue.index();
    public static final int ITEM = AttributesEnum.Item.index();
    public static final int LCAFNO = AttributesEnum.LcafNo.index();
    public static final int COUNTRYOFORIGION = AttributesEnum.CountryOfOrigion.index();
    public static final int CONFIRMATION = AttributesEnum.Confirmation.index();
    public static final int CONFIRAMTIONCHARGES = AttributesEnum.ConfiramtionCharges.index();
    public static final int FREIGHTCHARGE = AttributesEnum.FreightCharge.index();
    public static final int OTHERCHARGE = AttributesEnum.OtherCharge.index();
    public static final int COMMISSION = AttributesEnum.Commission.index();
    public static final int INSURANCECOMPANYNAME = AttributesEnum.InsuranceCompanyName.index();
    public static final int INSURANCEPOLICYNO = AttributesEnum.InsurancePolicyNo.index();
    public static final int UDAMENDMENTNO = AttributesEnum.UdAmendmentNo.index();
    public static final int LCSTATUS = AttributesEnum.LcStatus.index();
    public static final int LASTUPDATELOGIN = AttributesEnum.LastUpdateLogin.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int ATTRIBUTE1 = AttributesEnum.Attribute1.index();
    public static final int ATTRIBUTE2 = AttributesEnum.Attribute2.index();
    public static final int ATTRIBUTE3 = AttributesEnum.Attribute3.index();
    public static final int ATTRIBUTE4 = AttributesEnum.Attribute4.index();
    public static final int ATTRIBUTE5 = AttributesEnum.Attribute5.index();
    public static final int ATTRIBUTE6 = AttributesEnum.Attribute6.index();
    public static final int ATTRIBUTE7 = AttributesEnum.Attribute7.index();
    public static final int ATTRIBUTE8 = AttributesEnum.Attribute8.index();
    public static final int ATTRIBUTE9 = AttributesEnum.Attribute9.index();
    public static final int ATTRIBUTE10 = AttributesEnum.Attribute10.index();
    public static final int ATTRIBUTE11 = AttributesEnum.Attribute11.index();
    public static final int ATTRIBUTE12 = AttributesEnum.Attribute12.index();
    public static final int ATTRIBUTE13 = AttributesEnum.Attribute13.index();
    public static final int ATTRIBUTE14 = AttributesEnum.Attribute14.index();
    public static final int ATTRIBUTE15 = AttributesEnum.Attribute15.index();
    public static final int ATTRIBUTE16 = AttributesEnum.Attribute16.index();
    public static final int ATTRIBUTE17 = AttributesEnum.Attribute17.index();
    public static final int ATTRIBUTE18 = AttributesEnum.Attribute18.index();
    public static final int ATTRIBUTE19 = AttributesEnum.Attribute19.index();
    public static final int ATTRIBUTE20 = AttributesEnum.Attribute20.index();
    public static final int ATTRIBUTE21 = AttributesEnum.Attribute21.index();
    public static final int ATTRIBUTE22 = AttributesEnum.Attribute22.index();
    public static final int ATTRIBUTE23 = AttributesEnum.Attribute23.index();
    public static final int ATTRIBUTE24 = AttributesEnum.Attribute24.index();
    public static final int ATTRIBUTE25 = AttributesEnum.Attribute25.index();
    public static final int ATTRIBUTE26 = AttributesEnum.Attribute26.index();
    public static final int ATTRIBUTE27 = AttributesEnum.Attribute27.index();
    public static final int ATTRIBUTE28 = AttributesEnum.Attribute28.index();
    public static final int ATTRIBUTE29 = AttributesEnum.Attribute29.index();
    public static final int ATTRIBUTE30 = AttributesEnum.Attribute30.index();
    public static final int COMMUNICATIONTYPE = AttributesEnum.CommunicationType.index();
    public static final int UPASSDAYS = AttributesEnum.UpassDays.index();
    public static final int INSURANCECOVERNOTEDATE = AttributesEnum.InsuranceCoverNoteDate.index();
    public static final int CURRENCY = AttributesEnum.Currency.index();
    public static final int CONVERSIONRATE = AttributesEnum.ConversionRate.index();
    public static final int CONVERTEDAMOUNT = AttributesEnum.ConvertedAmount.index();
    public static final int AMENDMENTDATE = AttributesEnum.AmendmentDate.index();
    public static final int AMENDEDVALUE = AttributesEnum.AmendedValue.index();
    public static final int PAIDAMOUNTFORBBLC = AttributesEnum.PaidAmountForBblc.index();
    public static final int BENEFICIARYID = AttributesEnum.BeneficiaryId.index();
    public static final int BBLCHEADER = AttributesEnum.BBLCHeader.index();
    public static final int BBLCDETAILS1 = AttributesEnum.BBLCDetails1.index();
    public static final int BBLCPIDETAILS = AttributesEnum.BBLCPiDetails.index();
    public static final int BBLCACCEPTANCE = AttributesEnum.BBLCAcceptance.index();

    /**
     * This is the default constructor (do not remove).
     */
    public BBLCLinesEOImpl() {
    }


    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        if (mDefinitionObject == null) {
            mDefinitionObject = EntityDefImpl.findDefObject("mnj.ont.model.entities.BBLCLinesEO");
        }
        return mDefinitionObject;
    }

    /**
     * Gets the attribute value for ImpBblcLineId, using the alias name ImpBblcLineId.
     * @return the ImpBblcLineId
     */
    public Number getImpBblcLineId() {
        return (Number)getAttributeInternal(IMPBBLCLINEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for ImpBblcLineId.
     * @param value value to set the ImpBblcLineId
     */
    public void setImpBblcLineId(Number value) {
        setAttributeInternal(IMPBBLCLINEID, value);
    }

    /**
     * Gets the attribute value for ImpBblcHeaderId, using the alias name ImpBblcHeaderId.
     * @return the ImpBblcHeaderId
     */
    public Number getImpBblcHeaderId() {
        return (Number)getAttributeInternal(IMPBBLCHEADERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for ImpBblcHeaderId.
     * @param value value to set the ImpBblcHeaderId
     */
    public void setImpBblcHeaderId(Number value) {
        setAttributeInternal(IMPBBLCHEADERID, value);
    }

    /**
     * Gets the attribute value for BblcType, using the alias name BblcType.
     * @return the BblcType
     */
    public String getBblcType() {
        return (String)getAttributeInternal(BBLCTYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for BblcType.
     * @param value value to set the BblcType
     */
    public void setBblcType(String value) {
        setAttributeInternal(BBLCTYPE, value);
    }

    /**
     * Gets the attribute value for BblcNo, using the alias name BblcNo.
     * @return the BblcNo
     */
    public String getBblcNo() {
        return (String)getAttributeInternal(BBLCNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for BblcNo.
     * @param value value to set the BblcNo
     */
    public void setBblcNo(String value) {
        setAttributeInternal(BBLCNO, value);
    }

    /**
     * Gets the attribute value for LcIssueDate, using the alias name LcIssueDate.
     * @return the LcIssueDate
     */
    public Date getLcIssueDate() {
        return (Date)getAttributeInternal(LCISSUEDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for LcIssueDate.
     * @param value value to set the LcIssueDate
     */
    public void setLcIssueDate(Date value) {
        setAttributeInternal(LCISSUEDATE, value);
    }

    /**
     * Gets the attribute value for LastShipmentDate, using the alias name LastShipmentDate.
     * @return the LastShipmentDate
     */
    public Date getLastShipmentDate() {
        return (Date)getAttributeInternal(LASTSHIPMENTDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastShipmentDate.
     * @param value value to set the LastShipmentDate
     */
    public void setLastShipmentDate(Date value) {
        setAttributeInternal(LASTSHIPMENTDATE, value);
    }

    /**
     * Gets the attribute value for NegotiationDay, using the alias name NegotiationDay.
     * @return the NegotiationDay
     */
    public String getNegotiationDay() {
        return (String)getAttributeInternal(NEGOTIATIONDAY);
    }

    /**
     * Sets <code>value</code> as the attribute value for NegotiationDay.
     * @param value value to set the NegotiationDay
     */
    public void setNegotiationDay(String value) {
        setAttributeInternal(NEGOTIATIONDAY, value);
    }

    /**
     * Gets the attribute value for ExpiryDate, using the alias name ExpiryDate.
     * @return the ExpiryDate
     */
    public Date getExpiryDate() {
        return (Date)getAttributeInternal(EXPIRYDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ExpiryDate.
     * @param value value to set the ExpiryDate
     */
    public void setExpiryDate(Date value) {
        setAttributeInternal(EXPIRYDATE, value);
    }

    /**
     * Gets the attribute value for BblcLineIncoTerm, using the alias name BblcLineIncoTerm.
     * @return the BblcLineIncoTerm
     */
    public String getIncoTerm() {
        return (String)getAttributeInternal(INCOTERM);
    }

    /**
     * Sets <code>value</code> as the attribute value for BblcLineIncoTerm.
     * @param value value to set the BblcLineIncoTerm
     */
    public void setIncoTerm(String value) {
        setAttributeInternal(INCOTERM, value);
    }

    /**
     * Gets the attribute value for UsancePeriod, using the alias name UsancePeriod.
     * @return the UsancePeriod
     */
    public String getUsancePeriod() {
        return (String)getAttributeInternal(USANCEPERIOD);
    }

    /**
     * Sets <code>value</code> as the attribute value for UsancePeriod.
     * @param value value to set the UsancePeriod
     */
    public void setUsancePeriod(String value) {
        setAttributeInternal(USANCEPERIOD, value);
    }

    /**
     * Gets the attribute value for ShipmentMode, using the alias name ShipmentMode.
     * @return the ShipmentMode
     */
    public String getShipmentMode() {
        return (String)getAttributeInternal(SHIPMENTMODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ShipmentMode.
     * @param value value to set the ShipmentMode
     */
    public void setShipmentMode(String value) {
        setAttributeInternal(SHIPMENTMODE, value);
    }

    /**
     * Gets the attribute value for BeneficiaryName, using the alias name BeneficiaryName.
     * @return the BeneficiaryName
     */
    public String getBeneficiaryName() {
        return (String)getAttributeInternal(BENEFICIARYNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for BeneficiaryName.
     * @param value value to set the BeneficiaryName
     */
    public void setBeneficiaryName(String value) {
        setAttributeInternal(BENEFICIARYNAME, value);
    }

    /**
     * Gets the attribute value for PiNo, using the alias name PiNo.
     * @return the PiNo
     */
    public String getPiNo() {
        return (String)getAttributeInternal(PINO);
    }

    /**
     * Sets <code>value</code> as the attribute value for PiNo.
     * @param value value to set the PiNo
     */
    public void setPiNo(String value) {
        setAttributeInternal(PINO, value);
    }

    /**
     * Gets the attribute value for TotalBblcValue, using the alias name TotalBblcValue.
     * @return the TotalBblcValue
     */
    public Number getTotalBblcValue() {
        return (Number)getAttributeInternal(TOTALBBLCVALUE);
    }

    /**
     * Sets <code>value</code> as the attribute value for TotalBblcValue.
     * @param value value to set the TotalBblcValue
     */
    public void setTotalBblcValue(Number value) {
        setAttributeInternal(TOTALBBLCVALUE, value);
    }

    /**
     * Gets the attribute value for Item, using the alias name Item.
     * @return the Item
     */
    public String getItem() {
        return (String)getAttributeInternal(ITEM);
    }

    /**
     * Sets <code>value</code> as the attribute value for Item.
     * @param value value to set the Item
     */
    public void setItem(String value) {
        setAttributeInternal(ITEM, value);
    }

    /**
     * Gets the attribute value for LcafNo, using the alias name LcafNo.
     * @return the LcafNo
     */
    public String getLcafNo() {
        return (String)getAttributeInternal(LCAFNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for LcafNo.
     * @param value value to set the LcafNo
     */
    public void setLcafNo(String value) {
        setAttributeInternal(LCAFNO, value);
    }

    /**
     * Gets the attribute value for CountryOfOrigion, using the alias name CountryOfOrigion.
     * @return the CountryOfOrigion
     */
    public String getCountryOfOrigion() {
        return (String)getAttributeInternal(COUNTRYOFORIGION);
    }

    /**
     * Sets <code>value</code> as the attribute value for CountryOfOrigion.
     * @param value value to set the CountryOfOrigion
     */
    public void setCountryOfOrigion(String value) {
        setAttributeInternal(COUNTRYOFORIGION, value);
    }

    /**
     * Gets the attribute value for Confirmation, using the alias name Confirmation.
     * @return the Confirmation
     */
    public String getConfirmation() {
        return (String)getAttributeInternal(CONFIRMATION);
    }

    /**
     * Sets <code>value</code> as the attribute value for Confirmation.
     * @param value value to set the Confirmation
     */
    public void setConfirmation(String value) {
        setAttributeInternal(CONFIRMATION, value);
    }

    /**
     * Gets the attribute value for ConfiramtionCharges, using the alias name ConfiramtionCharges.
     * @return the ConfiramtionCharges
     */
    public Number getConfiramtionCharges() {
        return (Number)getAttributeInternal(CONFIRAMTIONCHARGES);
    }

    /**
     * Sets <code>value</code> as the attribute value for ConfiramtionCharges.
     * @param value value to set the ConfiramtionCharges
     */
    public void setConfiramtionCharges(Number value) {
        setAttributeInternal(CONFIRAMTIONCHARGES, value);
    }

    /**
     * Gets the attribute value for FreightCharge, using the alias name FreightCharge.
     * @return the FreightCharge
     */
    public Number getFreightCharge() {
        return (Number)getAttributeInternal(FREIGHTCHARGE);
    }

    /**
     * Sets <code>value</code> as the attribute value for FreightCharge.
     * @param value value to set the FreightCharge
     */
    public void setFreightCharge(Number value) {
        setAttributeInternal(FREIGHTCHARGE, value);
    }

    /**
     * Gets the attribute value for OtherCharge, using the alias name OtherCharge.
     * @return the OtherCharge
     */
    public Number getOtherCharge() {
        return (Number)getAttributeInternal(OTHERCHARGE);
    }

    /**
     * Sets <code>value</code> as the attribute value for OtherCharge.
     * @param value value to set the OtherCharge
     */
    public void setOtherCharge(Number value) {
        setAttributeInternal(OTHERCHARGE, value);
    }

    /**
     * Gets the attribute value for Commission, using the alias name Commission.
     * @return the Commission
     */
    public String getCommission() {
        return (String)getAttributeInternal(COMMISSION);
    }

    /**
     * Sets <code>value</code> as the attribute value for Commission.
     * @param value value to set the Commission
     */
    public void setCommission(String value) {
        setAttributeInternal(COMMISSION, value);
    }

    /**
     * Gets the attribute value for InsuranceCompanyName, using the alias name InsuranceCompanyName.
     * @return the InsuranceCompanyName
     */
    public String getInsuranceCompanyName() {
        return (String)getAttributeInternal(INSURANCECOMPANYNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for InsuranceCompanyName.
     * @param value value to set the InsuranceCompanyName
     */
    public void setInsuranceCompanyName(String value) {
        setAttributeInternal(INSURANCECOMPANYNAME, value);
    }

    /**
     * Gets the attribute value for InsurancePolicyNo, using the alias name InsurancePolicyNo.
     * @return the InsurancePolicyNo
     */
    public String getInsurancePolicyNo() {
        return (String)getAttributeInternal(INSURANCEPOLICYNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for InsurancePolicyNo.
     * @param value value to set the InsurancePolicyNo
     */
    public void setInsurancePolicyNo(String value) {
        setAttributeInternal(INSURANCEPOLICYNO, value);
    }

    /**
     * Gets the attribute value for UdAmendmentNo, using the alias name UdAmendmentNo.
     * @return the UdAmendmentNo
     */
    public String getUdAmendmentNo() {
        return (String)getAttributeInternal(UDAMENDMENTNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for UdAmendmentNo.
     * @param value value to set the UdAmendmentNo
     */
    public void setUdAmendmentNo(String value) {
        setAttributeInternal(UDAMENDMENTNO, value);
    }

    /**
     * Gets the attribute value for LcStatus, using the alias name LcStatus.
     * @return the LcStatus
     */
    public String getLcStatus() {
        return (String)getAttributeInternal(LCSTATUS);
    }

    /**
     * Sets <code>value</code> as the attribute value for LcStatus.
     * @param value value to set the LcStatus
     */
    public void setLcStatus(String value) {
        setAttributeInternal(LCSTATUS, value);
    }

    /**
     * Gets the attribute value for LastUpdateLogin, using the alias name LastUpdateLogin.
     * @return the LastUpdateLogin
     */
    public Number getLastUpdateLogin() {
        return (Number)getAttributeInternal(LASTUPDATELOGIN);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdateLogin.
     * @param value value to set the LastUpdateLogin
     */
    public void setLastUpdateLogin(Number value) {
        setAttributeInternal(LASTUPDATELOGIN, value);
    }

    /**
     * Gets the attribute value for LastUpdateDate, using the alias name LastUpdateDate.
     * @return the LastUpdateDate
     */
    public Date getLastUpdateDate() {
        return (Date)getAttributeInternal(LASTUPDATEDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdateDate.
     * @param value value to set the LastUpdateDate
     */
    public void setLastUpdateDate(Date value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**
     * Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy.
     * @return the LastUpdatedBy
     */
    public Number getLastUpdatedBy() {
        return (Number)getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdatedBy.
     * @param value value to set the LastUpdatedBy
     */
    public void setLastUpdatedBy(Number value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for CreationDate, using the alias name CreationDate.
     * @return the CreationDate
     */
    public Date getCreationDate() {
        return (Date)getAttributeInternal(CREATIONDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreationDate.
     * @param value value to set the CreationDate
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the CreatedBy
     */
    public Number getCreatedBy() {
        return (Number)getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedBy.
     * @param value value to set the CreatedBy
     */
    public void setCreatedBy(Number value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for Attribute1, using the alias name Attribute1.
     * @return the Attribute1
     */
    public String getAttribute1() {
        return (String)getAttributeInternal(ATTRIBUTE1);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute1.
     * @param value value to set the Attribute1
     */
    public void setAttribute1(String value) {
        setAttributeInternal(ATTRIBUTE1, value);
    }

    /**
     * Gets the attribute value for Attribute2, using the alias name Attribute2.
     * @return the Attribute2
     */
    public String getAttribute2() {
        return (String)getAttributeInternal(ATTRIBUTE2);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute2.
     * @param value value to set the Attribute2
     */
    public void setAttribute2(String value) {
        setAttributeInternal(ATTRIBUTE2, value);
    }

    /**
     * Gets the attribute value for Attribute3, using the alias name Attribute3.
     * @return the Attribute3
     */
    public String getAttribute3() {
        return (String)getAttributeInternal(ATTRIBUTE3);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute3.
     * @param value value to set the Attribute3
     */
    public void setAttribute3(String value) {
        setAttributeInternal(ATTRIBUTE3, value);
    }

    /**
     * Gets the attribute value for Attribute4, using the alias name Attribute4.
     * @return the Attribute4
     */
    public String getAttribute4() {
        return (String)getAttributeInternal(ATTRIBUTE4);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute4.
     * @param value value to set the Attribute4
     */
    public void setAttribute4(String value) {
        setAttributeInternal(ATTRIBUTE4, value);
    }

    /**
     * Gets the attribute value for Attribute5, using the alias name Attribute5.
     * @return the Attribute5
     */
    public String getAttribute5() {
        return (String)getAttributeInternal(ATTRIBUTE5);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute5.
     * @param value value to set the Attribute5
     */
    public void setAttribute5(String value) {
        setAttributeInternal(ATTRIBUTE5, value);
    }

    /**
     * Gets the attribute value for Attribute6, using the alias name Attribute6.
     * @return the Attribute6
     */
    public String getAttribute6() {
        return (String)getAttributeInternal(ATTRIBUTE6);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute6.
     * @param value value to set the Attribute6
     */
    public void setAttribute6(String value) {
        setAttributeInternal(ATTRIBUTE6, value);
    }

    /**
     * Gets the attribute value for Attribute7, using the alias name Attribute7.
     * @return the Attribute7
     */
    public String getAttribute7() {
        return (String)getAttributeInternal(ATTRIBUTE7);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute7.
     * @param value value to set the Attribute7
     */
    public void setAttribute7(String value) {
        setAttributeInternal(ATTRIBUTE7, value);
    }

    /**
     * Gets the attribute value for Attribute8, using the alias name Attribute8.
     * @return the Attribute8
     */
    public String getAttribute8() {
        return (String)getAttributeInternal(ATTRIBUTE8);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute8.
     * @param value value to set the Attribute8
     */
    public void setAttribute8(String value) {
        setAttributeInternal(ATTRIBUTE8, value);
    }

    /**
     * Gets the attribute value for Attribute9, using the alias name Attribute9.
     * @return the Attribute9
     */
    public String getAttribute9() {
        return (String)getAttributeInternal(ATTRIBUTE9);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute9.
     * @param value value to set the Attribute9
     */
    public void setAttribute9(String value) {
        setAttributeInternal(ATTRIBUTE9, value);
    }

    /**
     * Gets the attribute value for Attribute10, using the alias name Attribute10.
     * @return the Attribute10
     */
    public String getAttribute10() {
        return (String)getAttributeInternal(ATTRIBUTE10);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute10.
     * @param value value to set the Attribute10
     */
    public void setAttribute10(String value) {
        setAttributeInternal(ATTRIBUTE10, value);
    }

    /**
     * Gets the attribute value for Attribute11, using the alias name Attribute11.
     * @return the Attribute11
     */
    public String getAttribute11() {
        return (String)getAttributeInternal(ATTRIBUTE11);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute11.
     * @param value value to set the Attribute11
     */
    public void setAttribute11(String value) {
        setAttributeInternal(ATTRIBUTE11, value);
    }

    /**
     * Gets the attribute value for Attribute12, using the alias name Attribute12.
     * @return the Attribute12
     */
    public String getAttribute12() {
        return (String)getAttributeInternal(ATTRIBUTE12);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute12.
     * @param value value to set the Attribute12
     */
    public void setAttribute12(String value) {
        setAttributeInternal(ATTRIBUTE12, value);
    }

    /**
     * Gets the attribute value for Attribute13, using the alias name Attribute13.
     * @return the Attribute13
     */
    public String getAttribute13() {
        return (String)getAttributeInternal(ATTRIBUTE13);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute13.
     * @param value value to set the Attribute13
     */
    public void setAttribute13(String value) {
        setAttributeInternal(ATTRIBUTE13, value);
    }

    /**
     * Gets the attribute value for Attribute14, using the alias name Attribute14.
     * @return the Attribute14
     */
    public String getAttribute14() {
        return (String)getAttributeInternal(ATTRIBUTE14);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute14.
     * @param value value to set the Attribute14
     */
    public void setAttribute14(String value) {
        setAttributeInternal(ATTRIBUTE14, value);
    }

    /**
     * Gets the attribute value for Attribute15, using the alias name Attribute15.
     * @return the Attribute15
     */
    public String getAttribute15() {
        return (String)getAttributeInternal(ATTRIBUTE15);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute15.
     * @param value value to set the Attribute15
     */
    public void setAttribute15(String value) {
        setAttributeInternal(ATTRIBUTE15, value);
    }

    /**
     * Gets the attribute value for Attribute16, using the alias name Attribute16.
     * @return the Attribute16
     */
    public String getAttribute16() {
        return (String)getAttributeInternal(ATTRIBUTE16);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute16.
     * @param value value to set the Attribute16
     */
    public void setAttribute16(String value) {
        setAttributeInternal(ATTRIBUTE16, value);
    }

    /**
     * Gets the attribute value for Attribute17, using the alias name Attribute17.
     * @return the Attribute17
     */
    public String getAttribute17() {
        return (String)getAttributeInternal(ATTRIBUTE17);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute17.
     * @param value value to set the Attribute17
     */
    public void setAttribute17(String value) {
        setAttributeInternal(ATTRIBUTE17, value);
    }

    /**
     * Gets the attribute value for Attribute18, using the alias name Attribute18.
     * @return the Attribute18
     */
    public String getAttribute18() {
        return (String)getAttributeInternal(ATTRIBUTE18);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute18.
     * @param value value to set the Attribute18
     */
    public void setAttribute18(String value) {
        setAttributeInternal(ATTRIBUTE18, value);
    }

    /**
     * Gets the attribute value for Attribute19, using the alias name Attribute19.
     * @return the Attribute19
     */
    public String getAttribute19() {
        return (String)getAttributeInternal(ATTRIBUTE19);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute19.
     * @param value value to set the Attribute19
     */
    public void setAttribute19(String value) {
        setAttributeInternal(ATTRIBUTE19, value);
    }

    /**
     * Gets the attribute value for Attribute20, using the alias name Attribute20.
     * @return the Attribute20
     */
    public String getAttribute20() {
        return (String)getAttributeInternal(ATTRIBUTE20);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute20.
     * @param value value to set the Attribute20
     */
    public void setAttribute20(String value) {
        setAttributeInternal(ATTRIBUTE20, value);
    }

    /**
     * Gets the attribute value for Attribute21, using the alias name Attribute21.
     * @return the Attribute21
     */
    public String getAttribute21() {
        return (String)getAttributeInternal(ATTRIBUTE21);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute21.
     * @param value value to set the Attribute21
     */
    public void setAttribute21(String value) {
        setAttributeInternal(ATTRIBUTE21, value);
    }

    /**
     * Gets the attribute value for Attribute22, using the alias name Attribute22.
     * @return the Attribute22
     */
    public String getAttribute22() {
        return (String)getAttributeInternal(ATTRIBUTE22);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute22.
     * @param value value to set the Attribute22
     */
    public void setAttribute22(String value) {
        setAttributeInternal(ATTRIBUTE22, value);
    }

    /**
     * Gets the attribute value for Attribute23, using the alias name Attribute23.
     * @return the Attribute23
     */
    public String getAttribute23() {
        return (String)getAttributeInternal(ATTRIBUTE23);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute23.
     * @param value value to set the Attribute23
     */
    public void setAttribute23(String value) {
        setAttributeInternal(ATTRIBUTE23, value);
    }

    /**
     * Gets the attribute value for Attribute24, using the alias name Attribute24.
     * @return the Attribute24
     */
    public String getAttribute24() {
        return (String)getAttributeInternal(ATTRIBUTE24);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute24.
     * @param value value to set the Attribute24
     */
    public void setAttribute24(String value) {
        setAttributeInternal(ATTRIBUTE24, value);
    }

    /**
     * Gets the attribute value for Attribute25, using the alias name Attribute25.
     * @return the Attribute25
     */
    public String getAttribute25() {
        return (String)getAttributeInternal(ATTRIBUTE25);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute25.
     * @param value value to set the Attribute25
     */
    public void setAttribute25(String value) {
        setAttributeInternal(ATTRIBUTE25, value);
    }

    /**
     * Gets the attribute value for Attribute26, using the alias name Attribute26.
     * @return the Attribute26
     */
    public String getAttribute26() {
        return (String)getAttributeInternal(ATTRIBUTE26);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute26.
     * @param value value to set the Attribute26
     */
    public void setAttribute26(String value) {
        setAttributeInternal(ATTRIBUTE26, value);
    }

    /**
     * Gets the attribute value for Attribute27, using the alias name Attribute27.
     * @return the Attribute27
     */
    public String getAttribute27() {
        return (String)getAttributeInternal(ATTRIBUTE27);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute27.
     * @param value value to set the Attribute27
     */
    public void setAttribute27(String value) {
        setAttributeInternal(ATTRIBUTE27, value);
    }

    /**
     * Gets the attribute value for Attribute28, using the alias name Attribute28.
     * @return the Attribute28
     */
    public String getAttribute28() {
        return (String)getAttributeInternal(ATTRIBUTE28);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute28.
     * @param value value to set the Attribute28
     */
    public void setAttribute28(String value) {
        setAttributeInternal(ATTRIBUTE28, value);
    }

    /**
     * Gets the attribute value for Attribute29, using the alias name Attribute29.
     * @return the Attribute29
     */
    public String getAttribute29() {
        return (String)getAttributeInternal(ATTRIBUTE29);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute29.
     * @param value value to set the Attribute29
     */
    public void setAttribute29(String value) {
        setAttributeInternal(ATTRIBUTE29, value);
    }

    /**
     * Gets the attribute value for Attribute30, using the alias name Attribute30.
     * @return the Attribute30
     */
    public String getAttribute30() {
        return (String)getAttributeInternal(ATTRIBUTE30);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute30.
     * @param value value to set the Attribute30
     */
    public void setAttribute30(String value) {
        setAttributeInternal(ATTRIBUTE30, value);
    }

    /**
     * Gets the attribute value for CommunicationType, using the alias name CommunicationType.
     * @return the CommunicationType
     */
    public String getCommunicationType() {
        return (String)getAttributeInternal(COMMUNICATIONTYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CommunicationType.
     * @param value value to set the CommunicationType
     */
    public void setCommunicationType(String value) {
        setAttributeInternal(COMMUNICATIONTYPE, value);
    }

    /**
     * Gets the attribute value for UpassDays, using the alias name UpassDays.
     * @return the UpassDays
     */
    public Number getUpassDays() {
        return (Number)getAttributeInternal(UPASSDAYS);
    }

    /**
     * Sets <code>value</code> as the attribute value for UpassDays.
     * @param value value to set the UpassDays
     */
    public void setUpassDays(Number value) {
        setAttributeInternal(UPASSDAYS, value);
    }

    /**
     * Gets the attribute value for InsuranceCoverNoteDate, using the alias name InsuranceCoverNoteDate.
     * @return the InsuranceCoverNoteDate
     */
    public Date getInsuranceCoverNoteDate() {
        return (Date)getAttributeInternal(INSURANCECOVERNOTEDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for InsuranceCoverNoteDate.
     * @param value value to set the InsuranceCoverNoteDate
     */
    public void setInsuranceCoverNoteDate(Date value) {
        setAttributeInternal(INSURANCECOVERNOTEDATE, value);
    }

    /**
     * Gets the attribute value for Currency, using the alias name Currency.
     * @return the Currency
     */
    public String getCurrency() {
        return (String)getAttributeInternal(CURRENCY);
    }

    /**
     * Sets <code>value</code> as the attribute value for Currency.
     * @param value value to set the Currency
     */
    public void setCurrency(String value) {
        setAttributeInternal(CURRENCY, value);
    }

    /**
     * Gets the attribute value for ConversionRate, using the alias name ConversionRate.
     * @return the ConversionRate
     */
    public Number getConversionRate() {
        return (Number)getAttributeInternal(CONVERSIONRATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ConversionRate.
     * @param value value to set the ConversionRate
     */
    public void setConversionRate(Number value) {
        setAttributeInternal(CONVERSIONRATE, value);
    }

    /**
     * Gets the attribute value for ConvertedAmount, using the alias name ConvertedAmount.
     * @return the ConvertedAmount
     */
    public Number getConvertedAmount() {
        return (Number)getAttributeInternal(CONVERTEDAMOUNT);
    }

    /**
     * Sets <code>value</code> as the attribute value for ConvertedAmount.
     * @param value value to set the ConvertedAmount
     */
    public void setConvertedAmount(Number value) {
        setAttributeInternal(CONVERTEDAMOUNT, value);
    }

    /**
     * Gets the attribute value for AmendmentDate, using the alias name AmendmentDate.
     * @return the AmendmentDate
     */
    public Date getAmendmentDate() {
        return (Date)getAttributeInternal(AMENDMENTDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for AmendmentDate.
     * @param value value to set the AmendmentDate
     */
    public void setAmendmentDate(Date value) {
        setAttributeInternal(AMENDMENTDATE, value);
    }

    /**
     * Gets the attribute value for AmendedValue, using the alias name AmendedValue.
     * @return the AmendedValue
     */
    public Number getAmendedValue() {
        return (Number)getAttributeInternal(AMENDEDVALUE);
    }

    /**
     * Sets <code>value</code> as the attribute value for AmendedValue.
     * @param value value to set the AmendedValue
     */
    public void setAmendedValue(Number value) {
        setAttributeInternal(AMENDEDVALUE, value);
    }

    /**
     * Gets the attribute value for PaidAmountForBblc, using the alias name PaidAmountForBblc.
     * @return the PaidAmountForBblc
     */
    public Number getPaidAmountForBblc() {
        return (Number)getAttributeInternal(PAIDAMOUNTFORBBLC);
    }

    /**
     * Sets <code>value</code> as the attribute value for PaidAmountForBblc.
     * @param value value to set the PaidAmountForBblc
     */
    public void setPaidAmountForBblc(Number value) {
        setAttributeInternal(PAIDAMOUNTFORBBLC, value);
    }

    /**
     * Gets the attribute value for BeneficiaryId, using the alias name BeneficiaryId.
     * @return the BeneficiaryId
     */
    public Number getBeneficiaryId() {
        return (Number)getAttributeInternal(BENEFICIARYID);
    }

    /**
     * Sets <code>value</code> as the attribute value for BeneficiaryId.
     * @param value value to set the BeneficiaryId
     */
    public void setBeneficiaryId(Number value) {
        setAttributeInternal(BENEFICIARYID, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }

    /**
     * @return the associated entity BBLCHeaderEOImpl.
     */
    public BBLCHeaderEOImpl getBBLCHeader() {
        return (BBLCHeaderEOImpl)getAttributeInternal(BBLCHEADER);
    }

    /**
     * Sets <code>value</code> as the associated entity BBLCHeaderEOImpl.
     */
    public void setBBLCHeader(BBLCHeaderEOImpl value) {
        setAttributeInternal(BBLCHEADER, value);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getBBLCDetails1() {
        return (RowIterator)getAttributeInternal(BBLCDETAILS1);
    }


    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getBBLCPiDetails() {
        return (RowIterator)getAttributeInternal(BBLCPIDETAILS);
    }


    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getBBLCAcceptance() {
        return (RowIterator)getAttributeInternal(BBLCACCEPTANCE);
    }


    /**
     * @param impBblcLineId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Number impBblcLineId) {
        return new Key(new Object[]{impBblcLineId});
    }
    
    
    protected void doDML(int operation, TransactionEvent e) {
       
       
       
       
         
        if (DML_UPDATE == operation) {
            
            
           
         
            
        } else if (DML_INSERT == operation) {
            
       
          
        }

        super.doDML(operation, e);
    }
    
   
    public void validateEntity() {
        
         
                      
        if (getBblcType() == null ){
            throw new JboException("BBLC Type cannot be Empty." + " BBLC No: "+getBblcNo() );
        }
         else if (getAttribute22() == null ){
                  throw new JboException("Payment Mode cannot be Empty."+ " BBLC No: "+getBblcNo());
         }
         else if (getCommunicationType() == null ){
            
                 throw new JboException("Communication Type cannot be Empty."+ " BBLC No: "+getBblcNo());
        }
         else if (getBblcNo() == null ){
              throw new JboException("BBLC No cannot be Empty.");
        }   
        
        else if (getLcIssueDate() == null ){
            
            if(!getAttribute22().equals("FoC")) {
                throw new JboException("Lc Issue Date No cannot be Empty."+ " BBLC No: "+getBblcNo());
            }
                            
         }
       else if (getIncoTerm()== null ){
                    
               throw new JboException("Inco Term cannot be Empty."+ " BBLC No: "+getBblcNo());          
                           
        }
        
        
             super.validateEntity();
                           
   }
    
  
    protected void create(AttributeList attributeList) {
        super.create(attributeList);
        oracle.jbo.server.SequenceImpl s =
            new oracle.jbo.server.SequenceImpl("IEDOC_IMP_BBLC_LINES_S",
                                               getDBTransaction());
        oracle.jbo.domain.Number sVal = s.getSequenceNumber();
        setImpBblcLineId(sVal);
   }
    


    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    // public RowIterator getBBLCDetails() {
    //     return (RowIterator)getAttributeInternal(BBLCDETAILS);
    // }
    
    
    
    private boolean checkBblcNoDuplicacy(String  bblcnumber) {
        
        
       String  statement , status ;
        int flag ;
       statement =  "BEGIN  IEDOC_DOC_NO_PKG.IMPORT_BBLC_NO_UC (:1,:2); end;";
        CallableStatement cs = this.getDBTransaction().createCallableStatement(statement, 1);
        try {
            cs.registerOutParameter(2, OracleTypes.VARCHAR);
            cs.setString(1, bblcnumber);
            cs.execute();
            flag = cs.getInt(2);
         
            cs.close();

        } catch (Exception e) {
            
            flag=1;
            status = e.getMessage();
        }
        
        if(flag ==1){
            // if duplicate bblc no found
            return true;
        }
        
        return false;
    }

}
